### ISSUE TITLE
The app force closes

### ISSUE THREAD

**Issue by nadiration** [j-hc/revanced-magisk-module#10]
I don't know what the problem is but after flashing the magisk module and rebooting, the app's logo is changed but when i try to use it forecloses i even cleared the app data but that doesn't solve anything.

**Comment by j-hc** [comment]
that is because installed youtube app and module version does not match.

**Comment by RICKYSTER** [comment]
> I don't know what the problem is but after flashing the magisk module and rebooting, the app's logo is changed but when i try to use it forecloses i even cleared the app data but that doesn't solve anything.

Same, YouTube version 17.29.34, latest version quits YouTube instantly and sometimes a bit late.

**Comment by j-hc** [comment]
@RICKYSTER try this:
1. disable module
2. uninstall youtube
3. reboot
4. download from the link given in the release section
5. enable module and reboot

if it still crashes let me know

**Comment by RICKYSTER** [comment]
> @RICKYSTER try this:
> 
> 1. disable module
> 2. uninstall youtube
> 3. reboot
> 4. download and install from the link given in the release section
> 5. enable module and reboot
> 
> if it still crashes let me know

Thanks, worked like a charm. 

Btw, not an issue, but a request, if u can, it would be better if shorts showed in the home like in youtube, it would be easier that way to get some quick relief and then going back to whatever one has been doing.

**Comment by j-hc** [comment]
@RICKYSTER you can enable shorts button from revanced settings inside youtube.

anyways im closing this issue.
