### ISSUE TITLE
How Share in Android with 2 Users

### ISSUE THREAD

**Issue by Milor123** [j-hc/revanced-magisk-module#104]
Hi guys. I am trying use this app with my two user in Android but when i flash it in magisk, youtube only can seen by the Owner of the phone, my second user cant see Revanced as app installed.

How can I solve it?
Thank you very much

**Comment by Tokito-Kun** [comment]
add --user $user_number to [customize.sh](https://pastebin.com/M0N5km0b) for all installation commands
add --user $user_number to [service.sh](https://pastebin.com/VSj7wNZn) for all installation commands
replace user_number with user number you want to install 
note : check pastebin for reference
