### ISSUE TITLE
Yt-Music Patch Failing

### ISSUE THREAD

**Issue by Ravi-Kishor** [j-hc/revanced-magisk-module#105]
https://pastebin.com/LGrmmTxs

**Comment by j-hc** [comment]
there is no patch called `hide-music-cast-button`

**Comment by bw003** [comment]
He is using revanced extended not revanced.

**Comment by bw003** [comment]
in utils.sh file add integrations.apk
local cmd="java................ -o $patched_apk -b $RV_PATCHES_JAR -m $RV_INTEGRATIONS_APK --keystore=ks.keystore $patcher_args"

**Comment by j-hc** [comment]
> in utils.sh file add integrations.apk local cmd="java................ -o $patched_apk -b $RV_PATCHES_JAR -m $RV_INTEGRATIONS_APK --keystore=ks.keystore $patcher_args"

dont do this. it includes integrations in every apk for every app

**Comment by bw003** [comment]
Yeah I know that. He needs to create a separate branch specifically for yt music and then apply this.

**Comment by Smart123s** [comment]
@bw003 https://github.com/j-hc/revanced-magisk-module/commit/996146299715dd9f43cdab0e00815ec14d5fd1c5 would be a better solution, no need for a second branch.

**Comment by bw003** [comment]
Yeah that's cool. I am a noob I didn't know about it. I only know about how to make minor tweaks here and there.
