### ISSUE TITLE
Windy & Backdrops

### ISSUE THREAD

**Issue by Vucko130** [j-hc/revanced-magisk-module#109]
Please add support for the **Windy** & **Backdrops** apps.

Thank You.

**Comment by j-hc** [comment]
its fairly easy to add support for new apps within only 5-6 lines. have a look at here: 
https://github.com/j-hc/revanced-magisk-module/blob/630e423b8f9b9930e5cd43f7bb451afde4f4b5d3/utils.sh#L391

i can accept a pr adding these apps.

**Comment by Vucko130** [comment]
added pull request
