### ISSUE TITLE
Make all apps a magisk module

### ISSUE THREAD

**Issue by miguelglopes** [j-hc/revanced-magisk-module#111]
Hey can't you make all apps as magisk modules (zip files) with auto update?

Thanks

**Comment by j-hc** [comment]
thats not recommended but still possible. see build.conf

**Comment by miguelglopes** [comment]
Why is it not recommended? Thanks

I know I can do it myself, but it would be great if it was automatic in your releases :)

**Comment by j-hc** [comment]
magisk auto update isnt worth the trouble of runtime mounting apks. only yt and yt music will be built as modules since it only makes sense for them (google login). use something like [obtainium](https://github.com/ImranR98/Obtainium) to auto update apks from the repo.

**Comment by ovizii** [comment]
Sorry to open this old thread, but I don't think it is worth starting a fresh one. I am using the latest magisk and have manually downloaded and  installed your yt and mindetach modules as I couldn't find it with fox's magisk module manager. All works great. 

What is the easiest way to keep these two updated?

**Comment by j-hc** [comment]
> What is the easiest way to keep these two updated? 

updating from magisk

**Comment by ovizii** [comment]
> > What is the easiest way to keep these two updated?
> 
> updating from magisk

As in: manually download and update via magisk?

**Comment by j-hc** [comment]
> > > What is the easiest way to keep these two updated?
> > 
> > updating from magisk
> 
> As in: manually download and update via magisk?

as in using the update button in magisk

**Comment by ovizii** [comment]
My apologies, I had a knowledge gap there. That was a really dumb question. For some reason I was firmly convinced that without the ability to browse repositories magisk could not track updates. 

Just before you replied, I had found this link https://forum.xda-developers.com/t/discussion-magisk-the-age-of-zygisk.4393877/ which mentioned:

```
Starting with the Magisk 23 (23017) canary builds.
Magisk supports update channels per module.
Each module can include it's own update link.​
```

so I assume that is how the update button of magisk is still able to update modules.
