### ISSUE TITLE
[Quick notice] - ReVanced patches temporarily down from Github

### ISSUE THREAD

**Issue by 1alessandro1** [j-hc/revanced-magisk-module#113]
Hello, I am very grateful for your work on this project, I'm currently using the youtube-revanced-magisk.zip as my main youtube app

Update on the situation with ReVanced:

Lately, the main ReVanced repo has recieved a DMCA takedown because the main repo contained some patches of a random weather app (used by 1% or less of ReVanced userbase) whose developer was not very happy to know that ReVanced could make a "premium unlock" on his app. 

I suggest to keep yourself updated with the news in their discord server, in order to update the Github Actions scripts when we will have more news (maybe a self hosted solution)
 

One of the mirrors: (afterst0rm is the main dev)

https://notabug.org/afterSt0rm/revanced-patches

**Comment by MatadorProBr** [comment]
or maybe just use this one since it's created by one of the ReVanced team (Palm) and it's more easy to use since it's hosted on GitHub:
https://github.com/PalmDevs/rvp

**Comment by MatadorProBr** [comment]
#114

**Comment by j-hc** [comment]
> or maybe just use this one since it's created by one of the ReVanced team (Palm) and it's more easy to use since it's hosted on GitHub: https://github.com/PalmDevs/rvp
> 
> Probably I will create a PR changing to this mirror repo when I have time

How do you know this repo is "official"? I would rather wait until github.com/revanced comes up with an alternative repo or self-host mine. To the forks of my builder, you can choose to use that repo as the source of patcbes but I will delay this until I am free and can host mine.

**Comment by j-hc** [comment]
the repo is up again.
