### ISSUE TITLE
YT Does not compiled

### ISSUE THREAD

**Issue by cyberboh** [j-hc/revanced-magisk-module#117]
YT Does not compiled even after manually running the job
Log: `https://pastebin.com/1bp1pkJa`
Full log attached
[logs_163.zip](https://github.com/j-hc/revanced-magisk-module/files/10243062/logs_163.zip)
Many errors inside

**Comment by Vucko130** [comment]
It's because of the [revanced cli](https://github.com/j-hc/revanced-cli). It's not updated. We have to wait till it get's updated by j-hc. otherwise nothing can be done.

**Comment by cyberboh** [comment]
> It's because of the [revanced cli](https://github.com/j-hc/revanced-cli). It's not updated. We have to wait till it get's updated by j-hc. otherwise nothing can be done.

Oh, i don't know if j-hc using his own cli, not official cli.
What happen if we change to official cli?

**Comment by Vucko130** [comment]
> > It's because of the [revanced cli](https://github.com/j-hc/revanced-cli). It's not updated. We have to wait till it get's updated by j-hc. otherwise nothing can be done.
> 
> Oh, i don't know if j-hc using his own cli, not official cli. What happen if we change to official cli?

Not gonna work. You need rip lib and unsigned apk function too. That's not available in the official cli.

**Comment by cyberboh** [comment]
> 

Ahh,,ok, waiting for him to update

**Comment by Vucko130** [comment]
> since base revanced-cli [changed so much recently](https://github.com/j-hc/revanced-cli/compare/v2.16.1...revanced:revanced-cli:main), including [removed](https://github.com/revanced/revanced-cli/commit/6e703eb8e8d7da0e52266c4965f37bc8aafb409c#diff-9ac3a3f8db8df53022463e3b9c5483d87a143c0c60422034091b265223842ca3) [stuffs](https://github.com/revanced/revanced-cli/commit/545597959a33e022a3d96821f802daf406f47e23) that j-hc [usually](https://github.com/j-hc/revanced-cli/commit/1d5a1cac966248eda0d4d4f7a54c1c5a964b2cd3#diff-9ac3a3f8db8df53022463e3b9c5483d87a143c0c60422034091b265223842ca3) [use](https://github.com/j-hc/revanced-cli/commit/1d5a1cac966248eda0d4d4f7a54c1c5a964b2cd3#diff-2ef879cbb6ceeae0fcfb94a4d78eba54b5285fd90fcc012c225540a952417d40), so, it gonna be longer than usual i guess

yeah. j-hc needs to do a lot of change.

**Comment by j-hc** [comment]
I am not sure when I will be able to get my hands of revanced-cli again but since everything is fine Im closing this issue.
