### ISSUE TITLE
"Module is too large to be loaded on this device" error on some devices

### ISSUE THREAD

**Issue by andigenn** [j-hc/revanced-magisk-module#118]
- Downloading YouTube ReVanced

! Module is too large to be loaded on this device

Module: latest
Xiaomi Mi 8
MIUI 12.0.3
RAM: 6 STORAGE: 128

**Comment by j-hc** [comment]
this will be fixed. for now as a workaround:
1. install com.google.android.youtube.apk inside the module
2. unzip the module zip and remove com.google.android.youtube.apk 
3. zip again and flash in magisk

**Comment by andigenn** [comment]
![Screenshot_2022-12-20-10-32-35-992_com fox2code mmm](https://user-images.githubusercontent.com/17638454/208633746-e71ac525-c7f1-4dbe-9fa3-e258bd6ae217.jpg)

**Comment by j-hc** [comment]
disable the module, reboot, install the apk, flash in magisk.

**Comment by andigenn** [comment]
Unfortunately it doesn't work.

**Comment by scottdotau** [comment]
@andigenn are you using something apart from magisk to flash the update (for example Fox MMM)?

If so, try use magisk app directly.

I get this error too in Fox but not Magisk app.

**Comment by andigenn** [comment]
Finally I solved by simply deleting the "lib' folder from the "base.apk" file.

**Comment by j-hc** [comment]
this is fixed and next release will include it. im closing the issue.
