### ISSUE TITLE
The app is missing from the app drawer

### ISSUE THREAD

**Issue by parzival-cmd** [j-hc/revanced-magisk-module#119]
Hi this happened after the latest update, I am unable to search or even find the YouTube app after some time. I installed the latest in magisk and also used it for a while and after a reboot(i guess) it's nowhere to be found anymore.

But I still can see the yt module in the list of modules from magisk app.

This is the second time this has happened. 

![Screenshot_20221221-123050_superuser.png](https://user-images.githubusercontent.com/55645257/208841438-c79793e8-1bfb-42b5-a88e-79976b221a3c.png)

![Screenshot_20221221-123040_Niagara_Launcher.png](https://user-images.githubusercontent.com/55645257/208841446-cc291b0f-8794-49ea-873d-252c42708ae3.png)

**Comment by j-hc** [comment]
try increasing the mount delay in build.conf

**Comment by kime01** [comment]
I notice the same behavior: YT app disappears after every reboot. Reinstalling magisk module fixes the issue, until the next restart of the module.

**Comment by j-hc** [comment]
> I notice the same behavior: YT app disappears after every reboot. Reinstalling magisk module fixes the issue, until the next reboot

try increasing the mount delay in build.conf

**Comment by kime01** [comment]
> > I notice the same behavior: YT app disappears after every reboot. Reinstalling magisk module fixes the issue, until the next reboot
> 
> try increasing the mount delay in build.conf

Thanks man but how?

**Comment by j-hc** [comment]
> > > I notice the same behavior: YT app disappears after every reboot. Reinstalling magisk module fixes the issue, until the next reboot
> > 
> > 
> > try increasing the mount delay in build.conf
> 
> Thanks man but how?

this line
https://github.com/j-hc/revanced-magisk-module/blob/031a4a15001e4612f0567af953414666f89b5092/build.conf#L33

increase mount delay, build the module and flash

**Comment by kime01** [comment]
> > > > I notice the same behavior: YT app disappears after every reboot. Reinstalling magisk module fixes the issue, until the next reboot
> > > 
> > > 
> > > try increasing the mount delay in build.conf
> > 
> > 
> > Thanks man but how?
> 
> this line
> 
> https://github.com/j-hc/revanced-magisk-module/blob/031a4a15001e4612f0567af953414666f89b5092/build.conf#L33
> 
> increase mount delay, build the module and flash
> 
> or you can edit the module zip and increase the sleep inside service.sh before mounting. same thing.

I tried to modify the _service.sh_ inside the magisk module (setting sleep "20" instead of "5") but I have the same behavior: the app auto-uninstalls itself after the reboot. Actually it happens during boot (it literally disappears in home screen, 2 seconds after the boot). Same with the latest version (2.147.0).

**Comment by j-hc** [comment]
basically the solution is to increase the mount delay. im closing this issue since it also worked for you.

**Comment by parzival-cmd** [comment]
> basically the solution is to increase the mount delay. im closing this issue since it also worked for you.

Hi I'm facing this issue again now after the latest build.

**Comment by j-hc** [comment]
> > basically the solution is to increase the mount delay. im closing this issue since it also worked for you.
> 
> Hi I'm facing this issue again now after the latest build.

make sure you rebooted after you had flashed the latest module. and put this in termux:
`su -c "sed -i '7s/.*/sleep 10/' /data/adb/modules/ytrv-magisk/service.sh"`

reboot and see if it works fine

**Comment by parzival-cmd** [comment]
> > > basically the solution is to increase the mount delay. im closing this issue since it also worked for you.
> > 
> > Hi I'm facing this issue again now after the latest build.
> 
> make sure you rebooted after you had flashed the latest module. and put this in termux:
> `su -c "sed -i '7s/.*/sleep 10/' /data/adb/modules/ytrv-magisk/service.sh"`
> 
> reboot and see if it works fine

will try and tell you.

**Comment by DeeparthGupta** [comment]
I have the same problem with the current version where the YouTube app disappears after reboot. The line above errors out with no such file or directory.

**Comment by mikulik86** [comment]
I have the same problem with the extended version.
(https://github.com/NoName-exe/revanced-extended)
