### ISSUE TITLE
Back Navigation Not working after sometime 

### ISSUE THREAD

**Issue by syuvraj346** [j-hc/revanced-magisk-module#120]
Back Navigation Key Not working after sometime in Youtube application.
Device : Realme X2 pro
Android sdk level : 29
Installed version : magisk_youtube_revanced_17.49.37
Frequency of issue : Very High

Last build without issue : 17.43.36
I think predictive back gesture is causing the issue.

**Comment by andigenn** [comment]
Same here.

Module: latest
Xiaomi Mi 8
MIUI 12.0.3
RAM: 6 STORAGE: 128

**Comment by j-hc** [comment]
please do not report revanced bugs here in this repo.
