### ISSUE TITLE
Patch Logs 

### ISSUE THREAD

**Issue by nikhilbadyal** [j-hc/revanced-magisk-module#121]
Unable to see Revanced Logs.

I want a patch to be excluded.  But somehow it's not getting excluded. So I want to see what happened to the patch. Whether is failed/succeded or anything. To my surprise they are not there earlier they were there.

This happens because of `build_functions` introduced for parallelization.

**Comment by nikhilbadyal** [comment]
I modified the code a bit to see the build logs. Since i was able to see command getting executed. 

I was able to see in `build.conf` if I add comma separated value they are treated as single values. 
So patches must be space separated.


<img width="1046" alt="image" src="https://user-images.githubusercontent.com/59223300/209353999-e797979c-7b97-478d-a282-4f1255a6567d.png">

**Comment by j-hc** [comment]
comma seperated exclusion list was never supported. the suppression of the output of the commands should be fixed with this commit 2f31c83f15874eaebd66fdccbb9f1e28c4c8b53b .
