### ISSUE TITLE
Placing more that one patch on config.toml makes all patches specified to not work

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#123]
It seems that if you have more that one patch specified on the config.toml file, it simply forgot to add a space between these patches (even if you add the space between the patches on the config.toml) and make the patch on the command look like this: "somepatchhereotherpatchhere" and since this patch doesn't exist, CLI just ignores it and continues the process.

**Comment by j-hc** [comment]
fixed bfd82eb
