### ISSUE TITLE
Mounting issue for YouTube

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#126]
For whatever reason, after some of the recent changes, after reboot the YouTube app is not being mounted. I've tried many different mount delays with no success the only way it will mount is re-flashing the module but a reboot yields it to be unmounted again. I use 4 magisk modules, YouTube, YT Music, TikTok and Twitch. The other 3 mount just fine with no issues after reboot, seems like only YouTube is affected. If there is any testing or steps of debugging I'd love to help, this has only become an issue after all the recent changes, I'm not sure exactly when.

**Comment by j-hc** [comment]
it mounts fine for me. what is the output of this command before and after reboot:
`su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')`

and this one:
su -c dumpsys package com.google.android.youtube | grep versionName

**Comment by E85Addict** [comment]
------------------ Results after flashing ZIP ------------------
su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')

total 54262
-rw-r--r-- 2 system system  55499289 2022-12-27 02:46 base.apk
drwxr-xr-x 3 system system      3452 2022-12-27 00:13 lib
drwxrwx--x 3 system install     3452 2022-12-27 00:13 oat

su -c dumpsys package com.google.android.youtube | grep versionName

versionName=17.49.37
versionName=17.32.38


------------------ Results after rebooting ------------------
su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')

total 138130
-rw-r--r-- 1 system system  141292093 2022-12-27 00:13 base.apk
drwxr-xr-x 3 system system       3452 2022-12-27 00:13 lib
drwxrwx--x 3 system install      3452 2022-12-27 00:13 oat

su -c dumpsys package com.google.android.youtube | grep versionName

versionName=17.49.37
versionName=17.32.38

**Comment by j-hc** [comment]
should be fixed with cc1b96d0c42a3321cf97bbd9c9e00d4121d0828a

can you test with the change

**Comment by E85Addict** [comment]
> should be fixed with [cc1b96d](https://github.com/j-hc/revanced-magisk-module/commit/cc1b96d0c42a3321cf97bbd9c9e00d4121d0828a)
> 
> can you test with the change

That fixed it!

**Comment by E85Addict** [comment]
Another thing, on my fork I changed my module prop author name to myself, but when I flash it, its changing back to the default which is yours, is there something changing it when flashing?

**Comment by j-hc** [comment]
> Another thing, on my fork I changed my module prop author name to myself, but when I flash it, its changing back to the default which is yours, is there something changing it when flashing?

yep. too many people were rebranding the module.

im closing the issue. thanks for letting me know.
