### ISSUE TITLE
modules do not work

### ISSUE THREAD

**Issue by dxcvvxd** [j-hc/revanced-magisk-module#129]
after rebooting for a few times (i had to because my RIL and IMS didnt restart properly) yt and yt music just disappeared from device (modules were still installed and enabled, no idea why that happened but it did many times before that so i wasnt really suprised).
i then decided to download and flash these modules again, did that without any issues, rebooted and when using both apps i noticed that they're completely broken:
youtube didnt have pure black theme and just crashed after splash screen
music didnt work in background (it didnt create the media player notification thing too).

i deleted and flashed both again but nothing has changed.

what do i do? any help would be appreciated.

**Comment by j-hc** [comment]
if you force-rebooted and caused a kernel panic, thats expected.
to fix: 
1. remove modules
2. reboot
3. re-flash

**Comment by dxcvvxd** [comment]
i did that and it worked
but after some rebooting again music stopped working properly and doing this method doesnt help it
should i also reboot after i install the module?

**Comment by j-hc** [comment]
you sure thats not a bug of revanced or yt music?
