### ISSUE TITLE
patching failed in latest pre-release

### ISSUE THREAD

**Issue by jwin3** [j-hc/revanced-magisk-module#13]
The youtube-revanced-magisk-v17.29.34-all.zip from 8-6-22 is only about 20mb and doesn't install in magisk. Not a big deal, I just used the one from the previous date. I just don't know why the most recent one was built incorrectly.

**Comment by j-hc** [comment]
yes the patching is done on the device now so instead of shipping the full apk i just ship the patch which is way smaller.

what is the error message you get in magisk? it should flash fine.

**Comment by jwin3** [comment]
![Screenshot_20220806-204918](https://user-images.githubusercontent.com/24281131/183271639-bc8e445c-2dd2-4b58-8a24-9c5916459366.png)

I get a patching failed and installation failed.

**Comment by j-hc** [comment]
make sure you installed youtube from the link given in releases section.

**Comment by jwin3** [comment]
I did. It's working fine after I installed the magisk patch from the day before unless the YouTube apk for 17.29.34 is different from those two days.

**Comment by j-hc** [comment]
ok lets keep this issue opened for now. i will send a debug build later with more explanatory error messages.

**Comment by E85Addict** [comment]
I am facing the same issue and will provide debug error messages when available

**Comment by ramavats** [comment]
same here kindly fix this

**Comment by Ravi-Kishor** [comment]
Same issue here...kindly fix this
![Screenshot_20220807-124231_Settings](https://user-images.githubusercontent.com/97280268/183279858-31a8bcad-43b0-49a8-b99c-324960fd6aa9.png)
![Screenshot_20220807-124248_Magic](https://user-images.githubusercontent.com/97280268/183279860-f3f4b444-9d56-41c5-acf8-67d7e3b18a52.png)

**Comment by j-hc** [comment]
anyone can try with this build and send me the `rvc-log.txt` created in /sdcard
[youtube-revanced-magisk-v17.29.34-all.zip](https://github.com/j-hc/revanced-magisk-module/files/9276524/youtube-revanced-magisk-v17.29.34-all.zip)

**Comment by E85Addict** [comment]
BASEPATH=/data/app/~~G0W6ScydOBWr-KOKRkjJtg==/com.google.android.youtube-0ljJFa4mOzuJ8T8N7W0ikQ==/base.apk
CANNOT LINK EXECUTABLE "/data/adb/modules_update/ytrv-magisk/xdelta": library "liblzma.so.5" not found: needed by main executable

**Comment by j-hc** [comment]
@E85Addict does this work
[youtube-revanced-magisk-v17.29.34-all.zip](https://github.com/j-hc/revanced-magisk-module/files/9276570/youtube-revanced-magisk-v17.29.34-all.zip)

**Comment by E85Addict** [comment]
![Screenshot_2022-08-07-03-11-53-41_41b2fabfb8d8a6d03d653b93534a3f6d](https://user-images.githubusercontent.com/77761710/183286025-7c3d341a-e9db-4496-8a0e-1bce70eb8f97.jpg)


BASEPATH=/data/app/~~G0W6ScydOBWr-KOKRkjJtg==/com.google.android.youtube-0ljJFa4mOzuJ8T8N7W0ikQ==/base.apk
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

**Comment by j-hc** [comment]
@E85Addict are you sure you installed youtube from the [link in releases section?](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-29-34-release/youtube-17-29-34-android-apk-download/)

**Comment by E85Addict** [comment]
@j-hc yes, let me start from scratch again to make sure and test, one sec.

**Comment by E85Addict** [comment]
![Screenshot_2022-08-07-03-19-45-05_41b2fabfb8d8a6d03d653b93534a3f6d](https://user-images.githubusercontent.com/77761710/183286261-ab58d668-de6c-489b-bca6-9f0198577eb3.jpg)


BASEPATH=/data/app/~~kK3JNkzx-2QCGuHm0uz3dg==/com.google.android.youtube-6HJF5cEOzpMdxtYUWRUHdQ==/base.apk

**Comment by E85Addict** [comment]
Seems to be working now

**Comment by E85Addict** [comment]
Using the apk from link provided

**Comment by j-hc** [comment]
@E85Addict thanks for testing. i will push the fix to the repo.

**Comment by E85Addict** [comment]
My pleasure, I'm glad I could help!

**Comment by j-hc** [comment]
here is the latest [pre-build](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220737)
please install and test and if everything is ok i will close this issue.

**Comment by E85Addict** [comment]
@j-hc worked perfectly sorry for late reply, fell asleep haha.

**Comment by j-hc** [comment]
then guessing it works for others too im closing the issue
