### ISSUE TITLE
Modules won't load after boot

### ISSUE THREAD

**Issue by NBruderman** [j-hc/revanced-magisk-module#131]
In the latest version, even after boot is complete (and boot complete flag is triggered), the app won't load the module when opening it for the first time after a boot. After closing and opening again, everything works again.

**Comment by konradpabijan** [comment]
I have the same issue

**Comment by j-hc** [comment]
pushed a new update, try that one.

**Comment by NBruderman** [comment]
Seems to work fine now, thanks!
