### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ramanveerji** [j-hc/revanced-magisk-module#137]
Add an option to upload the built modules and apk's directly to telegram channel.

**Comment by nikhilbadyal** [comment]
It's already there. See [here.](https://github.com/j-hc/revanced-magisk-module/blob/main/.github/workflows/build.yml#L101)

**Comment by MatadorProBr** [comment]
> It's already there. See [here.](https://github.com/j-hc/revanced-magisk-module/blob/main/.github/workflows/build.yml#L101)

I think he meant to upload the APK files to the Telegram since the script just gets the GitHub download links directly and add to the Telegram message instead of uploading to it

**Comment by ramanveerji** [comment]
> > It's already there. See [here.](https://github.com/j-hc/revanced-magisk-module/blob/main/.github/workflows/build.yml#L101)
> 
> I think he meant to upload the APK files to the Telegram since the script just gets the GitHub download links and adds to the Telegram message instead of uploading to Telegram directly

100% correct. In the request also i mentioned about apk's and modules brother, not the links.

**Comment by nikhilbadyal** [comment]
Sorry my bad. Miss-read from my end. @ramanveerji @MatadorProBr

**Comment by j-hc** [comment]
im not planning to add such feature. builds will only uploaded to github releases.

**Comment by ramanveerji** [comment]
Ok, but is it possible if we can do that for personal use? If yes then how?

**Comment by nikhilbadyal** [comment]
Yes it is possible. I do have a builder which uploads to telegram. Refer [this](https://github.com/nikhilbadyal/docker-py-revanced). You can refer [this](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.github/workflows/build-apk.yml#L130) for exact upload.

**Comment by ramanveerji** [comment]
> Yes it is possible. I do have a builder which uploads to telegram. Refer [this](https://github.com/nikhilbadyal/docker-py-revanced). You can refer [this](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.github/workflows/build-apk.yml#L130) for exact upload.

That's good but how can i integrate it in this repo.
