### ISSUE TITLE
Version selection bug with upcoming 18.X.X release

### ISSUE THREAD

**Issue by nikhilbadyal** [j-hc/revanced-magisk-module#138]
Upcoming release will break the `version selection` in script. The [util](https://github.com/fsaintjacques/semver-tool) used used in script is used to compare valid sem versions. 
There is upcoming youtube release versioned as `18.01.35`. (Notice the `.01`) As per semver leading zeros are not allowed which makes `18.01.35` an [invalid version.](https://jubianchi.github.io/semver-check/#/constraint/18.01.35)

Hence `./semver compare 18.01.35 17.49.37` will throw an error. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/59223300/211213860-231318c8-acb5-45b5-ac20-4a2337c43d01.png">

Which when used in comparing current `17.49.37` and future `18.01.35` in script. Script will pick `17.49.37` as latest version instead of `18.01.35`

<img width="714" alt="image" src="https://user-images.githubusercontent.com/59223300/211214327-69a67236-3e2d-4862-b8a5-9b84fd02689b.png">

**Comment by j-hc** [comment]
fixed here f69a8b6641715a655a9a472842066617d2c65fb5. thanks for the notice.
