### ISSUE TITLE
YouTube magisk-module cannot start

### ISSUE THREAD

**Issue by KL7000F** [j-hc/revanced-magisk-module#139]
App is crashing. See in log.
[youtube.txt](https://github.com/j-hc/revanced-magisk-module/files/10380217/youtube.txt)

**Comment by KL7000F** [comment]
Unusual. I had to remove the module, then install the original app and then reinstall the module again. Now she starts again. So done.

**Comment by j-hc** [comment]
what is your android version

**Comment by KL7000F** [comment]
Android 13

**Comment by londek** [comment]
Same issue here, Android 12, Miui 13.0.4. Same fix worked

**Comment by j-hc** [comment]
@londek duplicate issue here https://github.com/j-hc/revanced-magisk-module/issues/148
can you execute the commands i give there and send the output
