### ISSUE TITLE
Youtube renamed to "Self sponsored cards are shown" and crashes

### ISSUE THREAD

**Issue by scmanjarrez** [j-hc/revanced-magisk-module#144]
I've installed latest magisk module and it installs successfully, however, after reboot and clicking the new youtube app, it automatically changes its name to "Self sponsored cards are shown" and starts crashing.
Log files: [2023-01-13_20.18.zip](https://github.com/j-hc/revanced-magisk-module/files/10414741/2023-01-13_20.18.zip)

**Comment by j-hc** [comment]
put this in termux and see if that still happens after a reboot:
`su -c "sed -i '7s/.*/sleep 10/' /data/adb/modules/ytrv-magisk/service.sh"`

**Comment by scmanjarrez** [comment]
Yes, that did the trick. Thank you!
