### ISSUE TITLE
Report to Telegram is throwing error 400

### ISSUE THREAD

**Issue by Vucko130** [j-hc/revanced-magisk-module#146]
Report to Telegram is throwing error 400. Full error is 
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 2143"}

**Comment by j-hc** [comment]
can you send the workflow logs

**Comment by ramanveerji** [comment]
> can you send the workflow logs
I also face that error, The following is the line present at the bottom.

{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 2202"}

**Comment by j-hc** [comment]
i need the full workflow log

**Comment by ramanveerji** [comment]
> i need the full workflow log

https://spaceb.in/tCnlErrd

**Comment by ramanveerji** [comment]
> i need the full workflow log

https://spaceb.in/ipQhTYzB

**Comment by Vucko130** [comment]
> can you send the workflow logs

sure. here it is [https://pastebin.com/HsgFDTLW](url)

**Comment by j-hc** [comment]
fixed with faa444c1ee2d42dfaa1186e706148201b2dcee67

**Comment by Vucko130** [comment]
> fixed with [faa444c](https://github.com/j-hc/revanced-magisk-module/commit/faa444c1ee2d42dfaa1186e706148201b2dcee67)

Run cd build || echo "build folder not found"
sed: can't read build.md: No such file or directory
Error: Process completed with exit code 2.

**Comment by Vucko130** [comment]
Here's the new Workflow Log [New Workflow Log](https://pastebin.com/VP8vFX4h)

**Comment by j-hc** [comment]
should be fine now be359a19c0830ff315ba2c8173309c0842901c79

**Comment by ramanveerji** [comment]
> should be fine now [be359a1](https://github.com/j-hc/revanced-magisk-module/commit/be359a19c0830ff315ba2c8173309c0842901c79)

Even though there is no error in workflow, but still it doesn't show in telegram channel.

**Comment by Vucko130** [comment]
It's not fixed. It's now throwing "{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 1092"}" this error. I have attached [log](https://pastebin.com/eg1wkEhS) file.

**Comment by Vucko130** [comment]
> 

It gives an error but it doesn't fail. Take a look at your logs. That's why it's not showing up in telegram.

**Comment by j-hc** [comment]
fixed again 96ac648b729b48e78681c0d5841745b262ef52fb
_i hate tg markdown_

**Comment by ramanveerji** [comment]
> fixed again 96ac648b729b48e78681c0d5841745b262ef52fb
> _i hate tg markdown_

Now it is finally fixed. Thanks.
