### ISSUE TITLE
App is crashing 

### ISSUE THREAD

**Issue by parzival-cmd** [j-hc/revanced-magisk-module#148]
Hi after the latest update, and also I've executed a command that you wanted me to do in terminal since the app is missing from the app drawer, I am facing app closing issues.

Here is the log
https://paste.evolution-x.org/JVOwbb

**Comment by j-hc** [comment]
what are the output of these commands in termux:
`su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')`

`su -c ls -ZlA $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')/lib/*`

`su -c ls -l /data/data/com.google.android.youtube`

`su -c ls -ZlA /data/data/com.google.android.youtube/app_lib`

**Comment by parzival-cmd** [comment]
> what are the output of these commands in termux:
> `su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')`
> 
> `su -c ls -ZlA $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')/lib/*`
> 
> `su -c ls -l /data/data/com.google.android.youtube`
> 
> `su -c ls -ZlA /data/data/com.google.android.youtube/app_lib`
 
Hi these are outputs:

![Screenshot_20230121-161504_Termux.png](https://user-images.githubusercontent.com/55645257/213863431-6fba38c5-f05b-4eb1-8f85-4b912f26065b.png)

![Screenshot_20230121-161510_Termux.png](https://user-images.githubusercontent.com/55645257/213863432-e35eb6db-9c78-4c70-b435-3345c3db047c.png)

**Comment by j-hc** [comment]
you probably had a soft reboot or a system crash. the soluton  is uninstalling the youtube when the module is not enabled and reflashing it. there is nothing else i can do.
