### ISSUE TITLE
Experimental flag not working

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#151]
When setting the version to "latest", it should automatically add the --experimental flag, but seems like that the config rework broke it.
Here are some logs (probably won't need but who knows): https://github.com/MatadorProBr/revanced-magisk-module/suites/10397397132/artifacts/513403278

**Comment by j-hc** [comment]
should be fixed with 1e8b9f51bd349b1b379faac6199b0b54136dc0a4
