### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ramanveerji** [j-hc/revanced-magisk-module#152]
Please add old artifacts cleaner in the workflow to prevent this error
Create Artifact Container failed: Artifact storage quota has been hit. Unable to upload any new artifacts

**Comment by ramanveerji** [comment]
> where do you get that error

While running the build modules workflow.

**Comment by j-hc** [comment]
nothing seems out of ordinary. you shouldnt get any error about artifact quota. you can try reducing "Artifact and log retention" from repo settings

**Comment by ramanveerji** [comment]
> since you are not linking to the actual repo and workflow logs i cant say anything else.

I just added that remove old releases thing in the repo, nothing else. I think i have to wait for next month so that the quota gets reset.
