### ISSUE TITLE
video timecode problems

### ISSUE THREAD

**Issue by electrifying** [j-hc/revanced-magisk-module#160]
Noticed a problem
1. Turn on the video in which there is support for timecodes
2. Turn on the settings to stretch the video image to full screen
3. Go to full-screen video viewing mode
4. Click on the timecode and instead of getting a list to the right of the video and going to the desired code, it is not there and the scale of the video breaks

you can check it on any video, for example, on this https://youtu.be/SRBkUBqmk4c
Android 11, app installed via module magisk

**Comment by j-hc** [comment]
`report revanced bugs in revanced repositories`
