### ISSUE TITLE
Use revanced extended?

### ISSUE THREAD

**Issue by sarf2k4** [j-hc/revanced-magisk-module#161]
I would like to know how can i used the revanced extended patches and supported youtube versions. At the time of this post, revanced supports youtube v17.4x while revanced extended supports youtube v18.0x

However in this repo, all linked towards revanced. There are explanations of what patches to use, I couldn't find the configuration file nor option to adjust them.

Could you provide a detailed guide?

**Comment by j-hc** [comment]
For building rv extended, all you need to do is to replace [`config-rv-ex.toml`](https://github.com/j-hc/revanced-magisk-module/blob/main/config-rv-ex.toml)  with [`config.toml`](https://github.com/j-hc/revanced-magisk-module/blob/main/config.toml).
