### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by Vucko130** [j-hc/revanced-magisk-module#162]
After the January 27th Commit till now all the packages are giving parsing errors when trying to install apks. It's creating corrupted apks. The full log is [here](https://pastebin.com/kUruuhVZ)

![Screenshot_2023-01-29-17-59-20-22_3d73e98b1ad3bd2575f7a56513d89a0c](https://user-images.githubusercontent.com/92352731/215324716-0f6da814-063f-46d2-94fa-8f4798a1c469.jpg)

![Screenshot_2023-01-29-17-58-59-67_e5d3893ac03954c6bb675ef2555b879b](https://user-images.githubusercontent.com/92352731/215324709-1e7cef0a-8619-4397-b31b-27e63c721b41.jpg)

**Comment by j-hc** [comment]
it is fine here: https://github.com/j-hc/revanced-magisk-module/releases

probably something to do with your fork so i cant fix it.
