### ISSUE TITLE
Cannot see comments section in landscape view

### ISSUE THREAD

**Issue by aadish151** [j-hc/revanced-magisk-module#169]
Hi,

I've installed youtube revanced using the magisk module released on Feb 3. The issue I'm having is I can't see the comments section when I switch to landscape mode nor can I see the button for comments on the bottom left. Comments show up in the regular version of youtube 18.03.36. Is there any toggle in the settings for it? I could not find anything. Otherwise everything works flawlessly.

**Comment by j-hc** [comment]
do not reporr revanced bugs in this repo
