### ISSUE TITLE
youtube magisk invalid URI

### ISSUE THREAD

**Issue by wasteoinc** [j-hc/revanced-magisk-module#170]
I followed your module creator in my PC and everything seems to compile nicely. I try to install magisk-module youtube 17.34.36 (the last one supporting android6) but the magisk module installer fails with an invalid URI error. 

Do you have any idea what causes this?

thanks

**Comment by j-hc** [comment]
can you send an ss of the error

**Comment by wasteoinc** [comment]
I think I was messing up a lot of things to make this a valid issue. I went further from there so I close this issue and make a new discussion
