### ISSUE TITLE
Latest doesn't check for the latest YouTube version

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#172]
It seems that it just checks for stable updates from the APKMirror YouTube page but not the ones that has "beta" to the name

As a example here:
latest yt version: '18.04.41'
![image](https://user-images.githubusercontent.com/71022656/216835596-6d642cdf-6b2d-461a-bd61-62853fe64d97.png)

**Comment by j-hc** [comment]
is this what you need?
https://github.com/j-hc/revanced-magisk-module/blob/4d35c6ea697f9d58c1a0f8582e3d487eca94c758/CONFIG.md?plain=1#L33

**Comment by MatadorProBr** [comment]
Oh yeah, didn't see that in CONFIG.md my bad
