### ISSUE TITLE
Add instagram support

### ISSUE THREAD

**Issue by cyberboh** [j-hc/revanced-magisk-module#173]
**Describe the bug**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**

Yesterday release, revanced add support to instagram, so i edited my config :
[Instagram-arm64]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"

[Instagram-arm]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm-v7a"

Separate version because instagram has many lib type. While building arm64 it failed, armv7 is fine but it downloaded 560-640dpi which is high dpi for older phone
Log attached
[instagram-arm64.log](https://github.com/j-hc/revanced-magisk-module/files/10715253/instagram-arm64.log)
[instagram-arm.log](https://github.com/j-hc/revanced-magisk-module/files/10715311/instagram-arm.log)

Likely, its trying to patch bundle files for arm64-v8, it should downloaded this release with `no-dpi`
`https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-269-0-0-18-75-release/instagram-269-0-0-18-75-3-android-apk-download/`
need to rework the tool then to download `no-dpi` variant

**Comment by j-hc** [comment]
added here e5b7f47
