### ISSUE TITLE
[Question] New rework module logic

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#18]
So it works fine, just used it the only problem is, since the module reinstalls the the correct apk everytime, it also erases the revanced settings in the process. So basically its like installing completely fresh even from just a regular update through magisk. My suggestion to a possible solution is to maybe have a cheksum check/match and if the apk is already the correct one skip the apk reinstall? The way it was simply only patching before was working completely fine in terms of updating and not resetting the revanced settings. Or whatever you think might work. I can test/debug anything you need me too. I hope I make sense I can clarify if needed.

**Comment by j-hc** [comment]
well actually that's exactly what i did. pushed the changes just now.
