### ISSUE TITLE
Why the music version going backward?

### ISSUE THREAD

**Issue by acwcanada** [j-hc/revanced-magisk-module#181]
**Describe the bug**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
There is no explanation why this happen, can someone tell?

**Comment by coderx546** [comment]
> **Describe the bug**
> **DO NOT REPORT REVANCED BUGS IN THIS REPO**
> There is no explanation why this happen, can someone tell?

What

**Comment by acwcanada** [comment]
> > **Describe the bug**
> > **DO NOT REPORT REVANCED BUGS IN THIS REPO**
> > There is no explanation why this happen, can someone tell?
> 
> What
2.162.0 (2023-02-14) the revanced music version is 5.41.50 and now 2.163.0 (22023-02-22) revanced music version is 5.39.52, that's what I am talking

**Comment by coderx546** [comment]
> > > **Describe the bug**
> > > **DO NOT REPORT REVANCED BUGS IN THIS REPO**
> > > There is no explanation why this happen, can someone tell?
> > 
> > 
> > What
> > 2.162.0 (2023-02-14) the revanced music version is 5.41.50 and now 2.163.0 (22023-02-22) revanced music version is 5.39.52, that's what I am talking

That's the recommended version for YT Music. It must have changed, there is nothing to worry about.

**Comment by MatadorProBr** [comment]
> **Describe the bug** **DO NOT REPORT REVANCED BUGS IN THIS REPO** There is no explanation why this happen, can someone tell?

It's because they now allow any version of YT Music to be patched (as seen on https://github.com/revanced/revanced-patches/commit/fe64881c83a7dd42761dbd67689fbc0ddcb73d78) but for some reason they didn't make this change to the `hide-get-premium` patch (as seen on https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt#L26) so this is probably why it downgrade the YT Music version

**Comment by j-hc** [comment]
This is not an "issue" and basically this:

> It's because they now allow any version of YT Music to be patched with all patches (as seen on https://github.com/revanced/revanced-patches/commit/fe64881c83a7dd42761dbd67689fbc0ddcb73d78) but for some reason they didn't make this change to one patch, with is the hide-get-premium patch (as seen on https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt#L26) so this is probably why it automatically downgraded the YT Music version
