### ISSUE TITLE
Youtube Revanced App Force Quits

### ISSUE THREAD

**Issue by HeyItsJono** [j-hc/revanced-magisk-module#188]
Hey there,
I don't believe this is a Revanced issue but correct me if I'm wrong. I think there may be something wrong with the mounting at the moment since the app force-quits with an error in logcat `ziparchive: Unable to open '/data/app/~~XDLmSqKhJKUWaUZNZgK7bQ==/com.google.android.youtube-oyXnc2MryHarJ9RDfTfNpA==/base.dm': No such file or directory`.

My System: Pixel 5, Android 12.1, rooted with latest Magisk, Zygisk enabled. Mindetach already installed.

My steps:

1. Uninstall Youtube Updates (can't completely uninstall YT as it's a system app on Pixel 5)
2. Install Youtube 18.03.36 (Arm64 single APK from APKMirror)
3. Install Youtube Revanced module generated from my fork of this repo, default settings for module build, installed via Magisk Manager
4. Reboot -> app crashing & Magisk Manager reporting version mismatch
5. Disabled module
6. Uninstall Youtube Updates (Resets YT app)
7. Reboot
8. Install YT 18.03.36 as previous
9. Enable Module
10. Reboot
11. App now opens and loads front page for an instant before force-quitting

The logcat can be found attached if it helps. Any help you could offer would be greatly appreciated, thanks for the module!
[Log_2023-03-07_11-06-54.txt](https://github.com/j-hc/revanced-magisk-module/files/10904032/Log_2023-03-07_11-06-54.txt)

**Comment by j-hc** [comment]
do this:
1. disable all modules related to revanced (including yt music) and reboot
2. uninstall all updates of youtube and flash youtube revanced module

**Comment by Switch123456789** [comment]
I had the same issue, @j-hc suggestion fixed it for me. It is important to NOT uninstall the modules and to just disable them in step 1.
