### ISSUE TITLE
Youtube Versions are not latest from APKMirror

### ISSUE THREAD

**Issue by rabilrbl** [j-hc/revanced-magisk-module#19]
This is the latest stable version on apkmirror
![image](https://user-images.githubusercontent.com/63334479/183613126-768789a6-48dd-413c-8f77-30bd81bfcd00.png)
But latest build is only giving v17.29.34

**Comment by j-hc** [comment]
this is intended. it only patches the version latest revanced-patches support which is 17.29.34. other version are not tested.

but if you still want to build with the latest version. put `--experimental` in `YT_PATCHER_ARGS` and set [this line](https://github.com/j-hc/revanced-magisk-module/blob/7c83c3ed56ee69c83efa7032d97536bd5932893f/utils.sh#L195) to:
`declare -r last_ver=$(get_apk_vers "https://www.apkmirror.com/apk/google-inc/youtube/" | head -n 1)}`

**Comment by j-hc** [comment]
fwiw i added the feature to fetch the latest version once you add the `--experimental` arg so no more need to change the `last_ver` variable.
