### ISSUE TITLE
Missing Youtube apps and zip

### ISSUE THREAD

**Issue by violesec** [j-hc/revanced-magisk-module#191]
Hi i'am fork and try to release with github action, but youtube apps and zip missing on release

**Comment by j-hc** [comment]
send logs

**Comment by violesec** [comment]
This log from github-action [logs](https://pipelines.actions.githubusercontent.com/serviceHosts/78c866ff-6b30-44a7-bded-88a651a9cee1/_apis/pipelines/1/runs/24/signedlogcontent/2?urlExpires=2023-03-10T14%3A33%3A35.2116825Z&urlSigningMethod=HMACV1&urlSignature=LNmd6kJsJXRyQ6oD0fSO3XEc7T8MrU9vl%2FCZmDXfTf0%3D)

**Comment by violesec** [comment]
Also on your release there is only zip available no application, but previous releases are available

**Comment by violesec** [comment]
Oh here the [Repo](https://github.com/Nimow-Project/revanced-magisk-module)

**Comment by violesec** [comment]
Ah solved, just need sync branch update
Sorry, thanks for answering my stupid question
