### ISSUE TITLE
The app is missing from the app drawer

### ISSUE THREAD

**Issue by mikulik86** [j-hc/revanced-magisk-module#195]
https://github.com/j-hc/revanced-magisk-module/issues/119

I have the same issue with the extended version. (https://github.com/NoName-exe/revanced-extended)

**Comment by j-hc** [comment]
That repo changes the module code to a buggy one. Do not report issues of forks. If you want revanced extended, build it with the config.

https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md#building-revanced-extended
