### ISSUE TITLE
Inactive KernelSU Module

### ISSUE THREAD

**Issue by mohamedamrnady** [j-hc/revanced-magisk-module#196]
**Describe the bug**
'mount failed' after flashing module and YouTube app crashes

A13
Kernelsu version: 10679

**Comment by j-hc** [comment]
flash the module, dont reboot and see if it still crashes.

**Comment by mohamedamrnady** [comment]
it works, the installation also goes smoothly,
`
_ __       
/\ /\___ _ __ _ __   ___| / _\/\ /\ 
/ //_/ _ \ '__| '_ \ / _ \ \ \/ / \ \
/ __ \  __/ |  | | | |  __/ |\ \ \_/ /
\/  \/\___|_|  |_| |_|\___|_\__/\___/

- Preparing image
- Module size: 116.95 MB
- Estimated minimum size of the filesystem: 63168
- Target image size: 248.75 MB
resize2fs 1.46.2 (28-Feb-2021)
- Mounting image
- Device is system-as-root
*************
 YouTube RVX 
 by j-hc 
*************
*********************
 Powered by KernelSU 
*********************
- Extracting module files

* Updating com.google.android.youtube (v18.10.37)
* Extracting native libs
* Setting Permissions
* Mounting com.google.android.youtube
* Optimizing com.google.android.youtube
* Cleanup
* Done
  by j-hc (github.com/j-hc)
 
- Done

`

**Comment by mohamedamrnady** [comment]
> 
> Changing $NVBASE in customize.sh to /data/adb did got the module working.

So setting RVPATH in service.sh to `${NVBASE}/rvhc/com.google.android.youtube_rv.apk` would fix the problem

**Comment by H1mJT** [comment]
> > Changing $NVBASE in customize.sh to /data/adb did got the module working.
> 
> So setting RVPATH in service.sh to `${NVBASE}/rvhc/com.google.android.youtube_rv.apk` would fix the problem

That also won't work, it's because how kernelsu operates. During installation of module it operates from /data/adb/ksu but after installation the module operates in /data/adb, so $NVBASE will be different for both cases.

**Comment by j-hc** [comment]
fixed with 805c22a
