### ISSUE TITLE
Doesn't seem to work with googleless roms

### ISSUE THREAD

**Issue by gaining** [j-hc/revanced-magisk-module#198]
I have micro g installed with no other google apps like play store, though I have the fake store but the revanced youtube always says it will not run without google play services. Could there be something else that I need to do?

**Comment by j-hc** [comment]
that shouldnt happen if you are using the magisk module. since you did not specify im going to assume you are using the apk and close the issue.
you need vancedmicrog regardless since it's different from the regular microg.
