### ISSUE TITLE
Instagram and Spotify APK missing

### ISSUE THREAD

**Issue by Othmane-ElAlami** [j-hc/revanced-magisk-module#199]
Is there any reason why the APKs of those two popular apps aren't included with the other releases?

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module#to-includeexclude-patches-or-patch-more-revanced-apps

**Comment by Othmane-ElAlami** [comment]
I know it's possible to do that but I was asking because adding them directly here would helpful for the average person and time saving for many.

**Comment by j-hc** [comment]
I dont use them so I dont add them, thats the reason. And the patches for those apps are not worth the risk of getting banned by instagram.
