### ISSUE TITLE
Fix kernelsu mount failed 

### ISSUE THREAD

**Issue by chostdz** [j-hc/revanced-magisk-module#202]
**Describe the bug**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
![Screenshot_20230323-174935_KernelSU](https://user-images.githubusercontent.com/50846777/227277249-3d6cf617-ae49-4bc9-9e8d-9ba2dca91cf4.png)
YouTube crash when open after reboot and can't mount 
Kernelsu is better way to root the device using overlay

**Comment by j-hc** [comment]
this is already fixed and the fix will be included in the next release. you can build yourself with the fix included.

**Comment by chostdz** [comment]
> this is already fixed and the fix will be included in the next release. you can build yourself with the fix included.

Thanks 👍

**Comment by j-hc** [comment]
assuming the issue is fixed with the latest build, im closing this.
