### ISSUE TITLE
YouTube automaticly updates 

### ISSUE THREAD

**Issue by BotAndis** [j-hc/revanced-magisk-module#204]
**Everytime I reboot YouTube updates**

I used multiple apps and the playstore option, but YouTube updates anyways everytime I restart.

-Rooted (one UI 5.1 android 13)
-Samsung S21 FE
-youtube (pre installed)
-detach (magisk module)
-update locker (lsposed module)
- playstore (Auto updates off)

**Comment by Transcan** [comment]
> [mindetach module](https://github.com/j-hc/mindetach-magisk) in the releases section detaches YouTube and YouTube Music from Play Store and blocks it from updating them.

**Comment by lordrak007** [comment]
Hi,
I have minidetach from revanced repo installed but youtube still wants update...
Even when i clear g play data.
What could be wrong?

**Comment by Transcan** [comment]
> Hi, I have minidetach from revanced repo installed but youtube still wants update... Even when i clear g play data. What could be wrong?

Check the file detach.txt inside the .zip module contains:
`com.google.android.youtube`

To be sure you you installed the correct one. Deinstall the module, reboot and then install the .zip with the correct detach.txt.

Alternatively, you can put the detach.txt file in the SDcard root and it will be used when you install the module.

Although both are the same version and has the same filename, the .zip in this repo already has all the apps detached.
https://github.com/j-hc/revanced-magisk-module/releases/download/20220861/mindetach-v3.3.zip

But the file in mindetach repo, has an empty detach.txt:
https://github.com/j-hc/mindetach-magisk

**Comment by lordrak007** [comment]
Probably causet i go from minidetach 2.4 to 3.3. After completely deletion and install again works. Thank you
