### ISSUE TITLE
Possible to add Old Youtube V15 UI?

### ISSUE THREAD

**Issue by veso266** [j-hc/revanced-magisk-module#206]
Hello there, is it possible to add old UI from version 15, because from today, version 15 does not work anymore: https://www.reddit.com/r/Vanced/comments/11xdhuw/other_i_think_today_marks_the_death_of_150554/?utm_medium=android_app&utm_source=share

I realy liked it, it was better for slower devices and you could choose a different channel while uploading video

Here is a detailed reddit post explaining the difference: https://www.reddit.com/r/Vanced/comments/zip3y0/question_i_cannot_upload_a_video_or_broadcast/?utm_medium=android_app&utm_source=share
And some more pictures (incase anyone forgot how old UI looked like)
Playlist: https://i.imgur.com/2NB39ik.jpg
Description: https://i.imgur.com/W9s4QRq.jpg
Comment section: https://i.imgur.com/VAQEzev.jpg

Old UI can also sort by oldest video (nedavno naloženi)
https://i.imgur.com/U8ZIY5G.jpg
https://i.imgur.com/oPRupii.jpg
https://i.imgur.com/T8UYHv4.jpg

As you can see the new version does not have an option to sort by oldest (only by recent and favourites): https://i.imgur.com/okMc8lS.jpg

And here are pictures that demonstrate upload feature

Old UI:
https://i.imgur.com/XXmY5JK.jpg
https://i.imgur.com/hLl465w.jpg

New (notice there is no option to change channel): https://i.imgur.com/XjdBJf2.jpg

Also video player is better in the old version
Old: https://i.imgur.com/Et2k84H.jpg
New: https://i.imgur.com/zYWFRYx.jpg

reVanced can do many thing, I am not sure how but I realy hope its possible to eather add the old UI back in the latest version or somehow patch youtube v15 (I use 15.05.54, but any v15 will do, I believe new ui was introduced at v15.20.33) to continue to work again 

Not sure whats got into it that it doesnt work anymore ((I found that package version is in the youtube API Post request, and if package version is < the 16, google will just block you with 400 error, not sure why there are doing like that)

Now I know that a lot of UI comes from the server (I tried to modify package version of my Youtbe Vanced, but sadly only half of the app worked then (new UI came, some things were broken) so that it will be impossible to add all the old UI, not realy sure how much old UI could even be added

Thanks for Anwsering and Best Regards

**Comment by j-hc** [comment]
do not report revance related stuff in this repo.

**Comment by Craftyawesome** [comment]
Both that and this repo are just for building revanced. Actual repos for issues/requests about revanced itself seem to be
https://github.com/revanced/revanced-patches/issues
https://github.com/inotia00/ReVanced_Extended/issues
