### ISSUE TITLE
APKMonk: 403 Forbidden

### ISSUE THREAD

**Issue by Smart123s** [j-hc/revanced-magisk-module#207]
APKMonk has started to return 403 Forbidden errors. The issues occurs only when the script is run via Actions. I've tested it locally today (after cleaning cache), and it worked without any issues. I've even tested it with a VPN.
The breakage is probably caused by a server-side change, as run [4502763885](https://github.com/Smart123s/revanced-extended-autobuild/actions/runs/4502763885) was successful, but run [4525483417](https://github.com/Smart123s/revanced-extended-autobuild/actions/runs/4525483417) failed, even tho both of them are on commit https://github.com/Smart123s/revanced-extended-autobuild/commit/f56ae00e206e58b4e550d0856839e3c4c803f93a.
I know I've written the APKMonk downloader, but absolutely have no idea how to fix it, and I just wanted to let you know that it's currently not working.
Update: the issue is that Cloudflare (rightfully) detects the request as coming from bots, and block them.
Edit2: a workaround is to build locally.

**Comment by quyleanh** [comment]
I notice same issue when patching photomath.

**Comment by j-hc** [comment]
yeah there is no way to fix this. apkmonk downloaded can stay as a local option.
