### ISSUE TITLE
[Suggestion] Check if there is a new YT version on CI workflow

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#21]
Currently CI only checks if there are any new release on the [revanced-patches](https://github.com/revanced/revanced-patches) repo before it builds with makes sense since to support a new version of YT, the devs need to release a new version of the patches but, when you gonna use the ``--experimental`` flag and there is a new release on APKMirror but no new release is made on the revanced-patches repo, CI just skips since the workflow only checks the revanced-patches repo.

My suggestion is to check if there is a new release on APKMirror (with --experimental flag, check for the latest version and without --experimental flag, check for the latest supported version or for a more pratical solution, only check when using --experimental flag).

**Comment by j-hc** [comment]
well that makes sense. i will add that feature.

**Comment by j-hc** [comment]
this should work: 2759f71
