### ISSUE TITLE
Apps without Magisk Modules uninstall on reboot

### ISSUE THREAD

**Issue by deltaxsingh** [j-hc/revanced-magisk-module#210]
I'm not sure why this would be the case as the other apks are not being mounted with the patches as the apks themselves contain the mods. At least, to my knowledge. So they really shouldn't get uninstalled on reboot.

I had the same issue for YouTube and YouTube music uninstalling on reboot and that's how I found your modules.

Would you consider making modules for the other apps as well please?

**Comment by j-hc** [comment]
> Would you consider making modules for the other apps as well please?

you can do that
https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md#if-youd-like-to-get-to-know-more-about-other-options
