### ISSUE TITLE
Problem installing youtube revanced extended Magisk Module

### ISSUE THREAD

**Issue by elsahy22** [j-hc/revanced-magisk-module#218]
When I Try install youtube revanced extended Magisk Module it type to me all done and when i reboot to use module youtube app disappears

but when i use normal youtube revanced Magisk Module every things works fine after reboot

my phone is redmi note 9s

**Comment by j-hc** [comment]
where is the extended module?

**Comment by elsahy22** [comment]
https://github.com/NoName-exe/revanced-extended/releases/tag/57

**Comment by j-hc** [comment]
that not my github account. what makes you think that's from me? why are you reporting the issue here?

**Comment by elsahy22** [comment]
i think that is your project

**Comment by elsahy22** [comment]
i also hove error in normal revanced module the error is when i lock screen while i watching video YouTube crash and close
another small problem also small control panel that appear when you use floating video it is not appear just play button is only thing appear

sorry for my bad English

**Comment by j-hc** [comment]
> i think that is your project

the repo you linked replaces my module code with a buggy one so its not my code, not my responsibility. dont report issues here unless you build extended like i write in the readme
