### ISSUE TITLE
No patched app, when apk is missing in apkmirror.

### ISSUE THREAD

**Issue by archit9169** [j-hc/revanced-magisk-module#219]
**Describe the bug**

Error when apk is not available in apkmirror, build completes but no output is given for that apk in release.

Logs:
[-] ERROR: Could not find any release of 'YouTube-Music' with version '5.55.53', arch 'arm64-v8a' and dpi 'nodpi' from APKMirror
Error: utils.sh [-] ERROR: Could not find any release of 'YouTube-Music' with version '5.55.53', arch 'arm64-v8a' and dpi 'nodpi' from APKMirror

Possible Solutions:
1. Add multiple sources so that it can get the apk from there.
2. Check for previous version supported by patches.

Workflow:
Using revnaced-extended, mode as apk only, and version set to auto.

**Comment by j-hc** [comment]
falling back to other sources is a good idea. added here 9c026f2
