### ISSUE TITLE
Auto play next not working

### ISSUE THREAD

**Issue by RANZN** [j-hc/revanced-magisk-module#22]
When youtube video ends it auto replay by default and when try to enable and disable again auto replay option form revanced setting it does not auto play neither does it play next...

any solution for it??

**Comment by j-hc** [comment]
do not create issues related to revanced in this repo

**Comment by RANZN** [comment]
Hey dude... can u once release a build with excluding the hide-autoplay-button patch..
Was searching for solution and got this... if this creating issue then remove this patch and auto play will work.

**Comment by j-hc** [comment]
it explained in the readme how to include/exclude patches and build yourself https://github.com/j-hc/revanced-magisk-module#to-includeexclude-patches-or-build-non-root-variant
