### ISSUE TITLE
Telegram message does not include download links.

### ISSUE THREAD

**Issue by archit9169** [j-hc/revanced-magisk-module#226]
**Describe the bug**
When rv_brand is changed in config file, the build modules workflow does not work correctly when making telegram message. The download links are not included due to hard coded strings in build modules workflow.

Solution:

Change *revanced* occurences in [Build Modules] workflow with updated *rv_brand* value give in config file.

Currently this is hardcoded and need to be changed manually. It should refer to rv_brand in config file.

**Comment by archit9169** [comment]
https://github.com/archit9169/youtube-rvx/commit/5fcbc5ddc45f3fc39c3990c04dbee9ab7a963c92

Please see this commit for my repo. Also there are similar occurances of revanced in one other step for changelog.

**Comment by j-hc** [comment]
should be fine now df09488
