### ISSUE TITLE
Not working for YouTube 

### ISSUE THREAD

**Issue by laleeroy** [j-hc/revanced-magisk-module#23]
Tried 2 version of magisk modules and Installed different version of YouTube app, arm64-v8a/xhdpi.

The modules works with YT music though, unfortunately I cannot get it to work for YT app

**Comment by j-hc** [comment]
try completely uninstalling youtube before flashing the module

**Comment by laleeroy** [comment]
> try completely uninstalling youtube before flashing the module

Yeah I did that, uninstalling, clearing data/cache, rebooting still no luck

**Comment by j-hc** [comment]
do you get any errors in the installation? do you reboot after flashing the module? try not rebooting after flashing.

**Comment by laleeroy** [comment]
> do you get any errors in the installation? do you reboot after flashing the module? try not rebooting after flashing.

I do not get any errors while installing the module, yes I did reboot and I uninstall it again, and reboot for clean installation and I quickly launch the YouTube app without rebooting after the installation but still no luck.

The installation logs says like this

Skipping stock apk installation
Patching YouTube music app
Patching done
Setting permission
Mounting YouTube music app
Done

Seems like the module doesn't detect the YT app, I tried to diff ways to install it, first install the module without YouTube app and second install the module with YouTube app, but it's still not detecting

**Comment by j-hc** [comment]
this is logs of the music module? you are aware that youtube revanced is seperate module right?

**Comment by laleeroy** [comment]
> this is logs of the music module? you are aware that youtube revanced is seperate module right?

That's the log of your modules installing in magisk, nvm, It's working now, ended up using with different repo from others

**Comment by j-hc** [comment]
are you claming that youtube module spits out music module's logs? well thats stupid lol

**Comment by laleeroy** [comment]
> are you claming that youtube module spits out music module's logs? well thats stupid lol

Sheet, Im so dumb 😅, I keep flashing and flashing the Music module instead of the YouTube module
