### ISSUE TITLE
Do I need to uninstall the revanced extended module and delete the related directory in /data/adb before installing an update for the revanced extended module?

### ISSUE THREAD

**Issue by lequangcuong123** [j-hc/revanced-magisk-module#234]
I've been a revanced extended module user for 2 months so my experience isn't much.  I'm happy that the extended version is regularly updated but at the same time it's a concern for me. I heard that when installing the youtube vanced module, it is necessary to remove the related YouTube modules and delete the folders in data/adb/service.d, /data/adb/post-fs-data.d, /data/adb/revanced then restart the phone and install revanced extended. So is this necessary when installing an update for the revanced extended module that I installed before? If this is necessary then I think you should improve it. The best and most convenient way to update the module that I can think of is to press the update button in the magisk app. You can imagine the benefits of that, right?

**Comment by j-hc** [comment]
no

**Comment by lequangcuong123** [comment]
> no

so I don't need to delete the revanced extended module every time I install an update for it right?

**Comment by j-hc** [comment]
there is no need. if there was, i would have stated in the readme

**Comment by lequangcuong123** [comment]
> không có nhu cầu. nếu có, tôi đã nói trong readme

thank guy

**Comment by lequangcuong123** [comment]
> there is no need. if there was, i would have stated in the readme

May I ask an unrelated question, how do I export a JSON file from the revanced extended and store it? I found where the export and import feature is displayed but when I press export it doesn't work (or maybe it's somewhere I don't know)
