### ISSUE TITLE
Youtube vanced strange behaviour (minimized) see pic attached

### ISSUE THREAD

**Issue by Broukmiken** [j-hc/revanced-magisk-module#238]
**Describe the bug**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**

Hello,
first, i would like to thank you for this great module, it's really helpful.
I noticed that when there is a youtube embeded and then i click on it, youtube vanced starts but the video is in a strange window and i can't do anything on it.
i have wipe all cache and datas, at first launch it's ok but on the next time the bug appears again.
i tried many options (pip, no pip, old player etc. but it's can't make it work normally)
could someone help me because i did't find anything about this.
(i'm rooted)
thanks so much
![Screenshot_20230515-145523](https://github.com/j-hc/revanced-magisk-module/assets/109454001/8ab48018-6a54-49c0-9e11-b280da270c9d)

**Comment by j-hc** [comment]
revanced bug
