### ISSUE TITLE
Either Revanced YouTube or Shamiko - but NOT both.

### ISSUE THREAD

**Issue by sconim** [j-hc/revanced-magisk-module#239]
Samsung SM-G990F (S20), running stock Android 13, Magisk 26.1, microG.

As soon as I install Revanced YouTube Magisk module and reboot, Shamiko module gets corrupted and it stops working. Practically, installing any one of these two modules results in the other being corrupted - cannot have both modules working together. I believe this has started with Magisk 25.2 or 26. 

[Edited] I have another identical S20, with exact same configuration however, instead of A13 it's running stock Android 10, Magisk 26.1 and microG and it has the exact same problem. 

I tried installing the two modules both through Magisk directly as well as through Fox's Androidacy Magisk module. Both installations end up successfully however, after reboot, one module gets corrupted - depending on which was installed first.

**Comment by ramanveerji** [comment]
> Samsung SM-G990F (S20), running stock Android 13, Magisk 26.1, microG.
> 
> As soon as I install Revanced YouTube Magisk module and reboot, Shamiko module gets corrupted and it stops working. Practically, installing any one of these two modules results in the other being corrupted - cannot have both modules working together. I believe this has started with Magisk 25.2 or 26.
> 
> What's interesting is that I have another identical S20, with exact same configuration however, instead of A13 it's running stock Android 10, Magisk 26.1 and microG and it seems on A10 this conflict doesnt exist.
> 
> I tried installing the two modules both through Magisk directly as well as through Fox's Androidacy Magisk module. Both installations end up successfully however, after reboot, one module gets corrupted - depending on which was installed first.

Actually, I also use both, no issues so far, must be the samsung rom itself is causing the issue.

**Comment by sconim** [comment]
Are you sure you installed ReVanced extended[](https://github.com/j-hc/revanced-magisk-module/releases) ?

**Comment by ramanveerji** [comment]
> Are you sure you installed ReVanced extended ?

I use normal revanced and not extended one. Extended one should also work fine

**Comment by ramanveerji** [comment]
> I solved the problem by just uninstalling Shamiko and enabling "Enforce Deny List" in Magisk. I don't use any app that would require SafetyNet and the built-in root hiding feature works perfectly fine with all apps that otherwise would not work.

how you can be so sure that it is shamiko only, maybe you are using some other module that is causing the trouble, anyways shamiko is not necessarily needed for safetynet, it just hides root from some of the apps that still detect root even after safetynet is passed.

**Comment by sconim** [comment]
Like I said in my initial description, installing one module results in the other one being corrupted, while all other modules behave normally. 

My understanding is that Shamiko is no longer needed (Magisk 26.1) for hiding root. You can try yourself disabling the module and enabling Enforce DenyList. Reboot and test with the same apps in the Configure DenyList and you'll most likely see that root remains hidden to all intended apps.

**Comment by ramanveerji** [comment]
> Like I said in my initial description, installing one module results in the other one being corrupted, while all other modules behave normally.
> 
> My understanding is that Shamiko is no longer needed (Magisk 26.1) for root hiding. You can try yourself disabling the module and enabling Enforce DenyList. Reboot and test with the same apps in the Configure DenyList and you'll most likely see that root remains hidden to all intended apps.

Yes shamiko is not needed but still some apps like YONO SBI, doesn't work without shamiko because of their super protection.

**Comment by sconim** [comment]
> > Like I said in my initial description, installing one module results in the other one being corrupted, while all other modules behave normally.
> > My understanding is that Shamiko is no longer needed (Magisk 26.1) for root hiding. You can try yourself disabling the module and enabling Enforce DenyList. Reboot and test with the same apps in the Configure DenyList and you'll most likely see that root remains hidden to all intended apps.
> 
> Yes shamiko is not needed but still some apps like YONO SBI, doesn't work without shamiko because of their super protection.

Well, luckily all my apps still work without Shamiko - including ReVanced 😁

**Comment by MatadorProBr** [comment]
It seems that the new version of Shamiko fixes this issue, maybe @sconim or anyone that haves this issue can install it again just to see if it really works now?
