### ISSUE TITLE
[Feature Request] Add TikTok support

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#24]
Recently, ReVanced added support to TikTok patches and it should be good if this project supported that.

I even tried adding support myself but for some reason, it just fails and I don't know exactly why so yeah.
https://github.com/MatadorProBr/revanced-magisk-module/runs/7837890366?check_suite_focus=true

**Comment by j-hc** [comment]
> it just fails and I don't know exactly why so yeah.

it fails because you probably edited the config file in a windows text editor in CRLF mode. you can set it to LF and maybe make a pr?

**Comment by MatadorProBr** [comment]
> it fails because you probably edited the config file in a windows text editor in CRLF mode. you can set it to LF and maybe make a pr?

Fixed but now it seems to give a other error because it doesn't recognize the "-" on the https://www.apkmirror.com/uploads/?appcategory=tik-tok URL.

https://github.com/MatadorProBr/revanced-magisk-module/runs/7841584729?check_suite_focus=true

**Comment by j-hc** [comment]
i added the support 66b402b
