### ISSUE TITLE
Build modules failed, tried many times but same error

### ISSUE THREAD

**Issue by maruashok** [j-hc/revanced-magisk-module#244]
I am trying to build YouTube-Extended using inotia00 patches but its getting failed, here's my config.toml

https://github.com/maruashok/RevancedMagiskModules/blob/main/config.toml
 
[logs_6.zip](https://github.com/j-hc/revanced-magisk-module/files/11565622/logs_6.zip)

and build logs are attached, please help me.

**Comment by j-hc** [comment]
revanced extended patches need to be updated with the latest revanced-patcher

**Comment by maruashok** [comment]
Still same error, Its already using latest version of all( As I didn't mentioned any specific version in my config.toml),
please check logs
1- https://github.com/j-hc/revanced-cli/releases/
2 - https://github.com/inotia00/revanced-patches/releases/
3 - https://github.com/inotia00/revanced-integrations/releases/

**Comment by j-hc** [comment]
like i said, revanced extended patches needs to be updated.

**Comment by maruashok** [comment]
Then why its working with revanced-builder-win.exe  ?
