### ISSUE TITLE
Revanced Extended failing

### ISSUE THREAD

**Issue by ovizii** [j-hc/revanced-magisk-module#245]
It's description says:

YouTube-Extended: 18.17.43

And yet there's no such asset attached. What am I missing here?

**Comment by j-hc** [comment]
because patching fails with extended patches and will continue to fail until they are updated by its author

**Comment by oldman20** [comment]
> because patching fails with extended patches and will continue to fail until they are updated by its author with latest revanced patcher

thank, so this repo and forks will be auto update too?
![2](https://github.com/j-hc/revanced-magisk-module/assets/39668756/f38ae983-2464-42e7-8a1c-e065daa2b227)

Can you look at this is has syntax properly ?
`[YouTube]
build-mode = "apk"                                                   # 'both', 'apk' or 'module'
excluded-patches = "disable-hdr-video hide-account-menu hide-auto-player-popup-panels hide-autoplay-preview hide-breaking-news-shelf hide-button-container hide-email-address hide-filmstrip-overlay hide-endscreen-overlay hide-endscreen-cards hide-info-cards hide-mix-playlists hide-seekbar"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "materialyou"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[YouTube-Extended]
app-name = "YouTube-Extended"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "apk"
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"`
