### ISSUE TITLE
Messenger Revanced

### ISSUE THREAD

**Issue by Reepzvan25** [j-hc/revanced-magisk-module#248]
Same problem on my end, when I type my email or username the apk will exit. What to do?

**Comment by j-hc** [comment]
do not revanced bugs.
try confirming messenger patched with revanced manager does not crash then we can see.

**Comment by Reepzvan25** [comment]
Where to get revanced manager?

**Comment by j-hc** [comment]
google will show you

**Comment by j-hc** [comment]
fixed for the next release

**Comment by Reepzvan25** [comment]
Works on my end I install first the revanced manager then download fresh
messenger from apkmirror then patch the apk and install as root

**Comment by Reepzvan25** [comment]
How to fix that failed thing?
