### ISSUE TITLE
Youtube Music Arm v7a

### ISSUE THREAD

**Issue by Fa3l** [j-hc/revanced-magisk-module#25]
hi i wanted to ask you to release a version of youtube music Revanced 5.17.51 for Arm v7a devices.

YouTube Music 5.17.51 arm v7a link nodpi apk mirror ( https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-5-17-51-release/youtube-music-5-17-51-android-apk-download/ )

**Comment by j-hc** [comment]
that link is a zip which is the bundle format. apkmirror for some reason dont have the apk version. music armv7 will need to wait until next release.

**Comment by j-hc** [comment]
6efe3d9
