### ISSUE TITLE
Revanced patches not applying to revanced yt

### ISSUE THREAD

**Issue by subhashis-barad** [j-hc/revanced-magisk-module#250]
Like, the YouTube icon stays as revanced default icon, even if excluded the patches for it.
And plox add apk name changing options in config.toml

**Comment by j-hc** [comment]
> Like, the YouTube icon stays as revanced default icon, even if excluded the patches for it. 

check your build logs. nothing to do with revanced-magisk-module

> And plox add apk name changing options in config.toml
you need to specify it in the options.json. again, nothing to do with revanced-magisk-module

**Comment by subhashis-barad** [comment]
Can you guide, for custom name for revanced music, to "YouTube Music"?
