### ISSUE TITLE
About set icon buid

### ISSUE THREAD

**Issue by oldman20** [j-hc/revanced-magisk-module#251]
**Describe the bug**
**DO NOT REPORT REVANCED BUGS IN THIS REPO**

In `config.toml` i set this
excluded-patches = "custom-branding-icon-afn-blue custom-branding-icon-afn-red custom-branding-icon-revancify-blue custom-branding-icon-revancify-red"
And from this [your post](https://github.com/j-hc/revanced-magisk-module/issues/250#issuecomment-1581212311
) i know to do need be set in `options.json`  but dont know syntax. Can you give a sample?
Thank you!

**Comment by j-hc** [comment]
patch options is a feature of revanced. its there for people how know what to put in it. idk about every patch option. basically, this is not the place to ask this quesion.

**Comment by oldman20** [comment]
> patch options is a feature of revanced. its there for people how know what to put in it. idk about every patch option. basically, this is not the place to ask this quesion.

Thank, so these patches not relevant for custom brand icon?
excluded-patches = "custom-branding-icon-afn-blue custom-branding-icon-afn-red custom-branding-icon-revancify-blue custom-branding-icon-revancify-red"

**Comment by j-hc** [comment]
i really dont have an idea. i dont follow patch name changes, their options etc. etc. that info is gotten from revanced-cli but you need to do it yourself. i just develop the builder and magisk modules
