### ISSUE TITLE
App crash (Magisk version)

### ISSUE THREAD

**Issue by Aditduck** [j-hc/revanced-magisk-module#256]
I instaled magisk version and got crash. I am running A13 rooted. Here the log. Thanks

https://bin.kv2.dev/~6495166ce599576ea02cd7e7

**Comment by j-hc** [comment]
try this one: https://drive.google.com/file/d/1kk0f4tgSjxwFLdxutuoOmU7w6jLd0I_b/view

do a clean installation (remove module, reboot, uninstall youtube, reflash the new one)
