### ISSUE TITLE
{"ok":false,"error_code":400,"description":"Bad Request: message is too long"}

### ISSUE THREAD

**Issue by AmirulAndalib** [j-hc/revanced-magisk-module#262]
Hi,

When sending upload logs to telegram chat using github workflow from your repository, I get this message:

`{"ok":false,"error_code":400,"description":"Bad Request: message is too long"}` , I didn't edit any part of this code.

Please look into this kindly, Thank You.

**Comment by Tokito-Kun** [comment]
Telegram has character limit of 9500 for markdown 
Refer : https://stackoverflow.com/questions/68768069/telegram-error-badrequest-entities-too-long-error-when-trying-to-send-long-ma
