### ISSUE TITLE
request: facebook

### ISSUE THREAD

**Issue by elektrinis** [j-hc/revanced-magisk-module#264]
Would really love to have revanced facebook, as it's a pain to use stock one, or other solutions.

Also, when stock facebook is installed, revanced messenger install fails, error says it conflicts with existing package, even though messenger is not installed.

**Comment by j-hc** [comment]
there is no need for a "revanced facebook" . just add facebook to the config.toml and it will be signed with the same signature and you will be able to install it with the messenger

**Comment by elektrinis** [comment]
Yes, but I wany facebook without ads. Revanced facebook would be so cool.

**Comment by j-hc** [comment]
i dont make revanced patches so idk
