### ISSUE TITLE
[Feature Request] Ability to pass reddit change-oauth-client-id as environment variable

### ISSUE THREAD

**Issue by aaxyat-old** [j-hc/revanced-magisk-module#265]
It would be fantastic if it were feasible to utilize the Reddit OAuth client ID for Boost, Sync, and similar applications as an environment variable to avoid exposing the client ID on a public repository. This approach would greatly enhance security and privacy.

**Comment by j-hc** [comment]
client ids are not something private. anyone can extract it from the patched apk. why would you wanna hide it?

**Comment by aaxyat-old** [comment]
Sorry, I thought it was private.. Thanks for the reply :)
