### ISSUE TITLE
Split apk structure to reduce installation file size

### ISSUE THREAD

**Issue by tuthanika** [j-hc/revanced-magisk-module#270]
Hope you support splitting apk structure to reduce installation file size.

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module/issues/252

**Comment by tuthanika** [comment]
> #252

"why do you need that exactly?"

to reduce installation file size, save phone storage space, make apps load faster and smoother

**Comment by j-hc** [comment]
that does not change anything related to "speed". and does not really make sense for ~30mb reduction.

**Comment by tuthanika** [comment]
For other applications like tiktok, it reduces quite a lot of space. For new phone models, this shouldn't be a problem. But with some older devices, it significantly reduces the space that apps take up. This is good for RAM and internal storage, which improves smoothness significantly.

**Comment by j-hc** [comment]
you are making this up. only the required native libs are loaded into the memory as they are uncompressed and aligned
