### ISSUE TITLE
microg_not_installed_warning/magisk module asking for MicroG/YT doesn't start

### ISSUE THREAD

**Issue by sixstrings** [j-hc/revanced-magisk-module#273]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

Since yesterday the RVX magisk module shows a toast message `microg_not_installed_warning` 
and doesn't start.
I saw you changed some parts in utils.sh regarding MicroG (commits on July 11th):

**Fix auto detection of microg patch:**

and

**concert microg patch to kebab case:**

Maybe it has something to do with these fixes.

![IMG_20230712_175819](https://github.com/j-hc/revanced-magisk-module/assets/132693162/cd32b7d4-8553-4db8-9ad2-005e118d5357)

**Comment by j-hc** [comment]
thats already fixed. only way you can get that error is you downloaded the module from somewhere else.

**Comment by sixstrings** [comment]
> thats already fixed. only way you can get that error is.because you downloaded the module from somewhere else which i dont provide support for.

Yes,it's from my fork of your repo. Will have to check the code. Thx.
