### ISSUE TITLE
Module invalid 

### ISSUE THREAD

**Issue by ggkameleon** [j-hc/revanced-magisk-module#274]
Hi ! On my Pixel A13 Root after installing module with magisk when I sleep at night every morning revanced invalid and uninstall.
I uncheck auto update of play store.
I don't understand why every day invalid module

**Comment by j-hc** [comment]
make sure your phone doesnt reboot by itself every night.

**Comment by j-hc** [comment]
its either play store ignores that option and updates youtube anyways or your phone reboots by itself every night.

**Comment by raycekar** [comment]
Sorry for this question but why does restarting the phone cause revanced to revert back to normal youtube?
