### ISSUE TITLE
Cannot open youtube revanced extended magisk module

### ISSUE THREAD

**Issue by user1680** [j-hc/revanced-magisk-module#277]
It is asking for MicroG but it didn't in previous versions of youtube revanced extended magisk module. 
![Screenshot_20230713_220203_ReVanced Extended](https://github.com/j-hc/revanced-magisk-module/assets/53784071/4b0c39a4-c283-42d8-8de7-070a986b0be5)

**Comment by j-hc** [comment]
since you are not responding i will assume its most likely you are using the module from this repo but from one of the forks. refrain from making non-existent bug reports or you will be blocked.
