### ISSUE TITLE
Consider offering Messenger with a changed package name

### ISSUE THREAD

**Issue by Dyras** [j-hc/revanced-magisk-module#278]
Hello! Since there is currently no Facebook Revanced, it is sadly impossible to install Messenger Revanced without the "change package name" patch if the user has the default Facebook app installed.

Any chance you could post a version using that patch?

Thanks in advance!

**Comment by j-hc** [comment]
try that yourself and if it works it will be added

**Comment by Dyras** [comment]
I tried building it and there seems to be an issue with that patch. Hmm.

https://github.com/revanced/revanced-patches/issues/2025#issuecomment-1537213488
I'll ping you when/if that issue is resolved.

**Comment by badawoll** [comment]
@Dyras it's not really a patch issue, more a patcher issue. It's trivial to fix after [arsclib](https://github.com/ReVanced/revanced-patcher/pull/165) gets merged.
