### ISSUE TITLE
Mindetach 2.1 not working

### ISSUE THREAD

**Issue by otharion** [j-hc/revanced-magisk-module#28]
After installing mindetach 2.1 PlayStore stills showing me the YouTube app update.

**Comment by j-hc** [comment]
can you send a screenshot of the logs in magisk after flasing

**Comment by otharion** [comment]
![Screenshot_2022-08-17-19-00-24-933_com topjohnwu magisk](https://user-images.githubusercontent.com/15057660/185199431-5f1e743f-57ed-4f5e-8c7b-ccad8d1d9349.jpg)
![IMG_20220817_190008](https://user-images.githubusercontent.com/15057660/185199458-6711ba0d-ec5f-4106-8310-d843734b914b.jpg)

**Comment by j-hc** [comment]
@otharion i mean the logs of mindetach

**Comment by otharion** [comment]
![Screenshot_2022-08-17-19-09-52-425_com topjohnwu magisk](https://user-images.githubusercontent.com/15057660/185201434-479f0c4e-f243-4b4b-a434-4127bb12b35b.jpg)

**Comment by j-hc** [comment]
and the screenshot of play store showing youtube

**Comment by otharion** [comment]
Sorry man, I didn't mean to bother you. Seems like it's working again. I had to uninstall it and reinstall it. Anyway thanks you very much for your concern and work. Here is the PlayStore update page:
![Screenshot_2022-08-17-19-27-17-639_com android vending](https://user-images.githubusercontent.com/15057660/185204193-1ae21099-bb4f-4d9b-9537-e5eca7cc78f7.jpg)

**Comment by j-hc** [comment]
can you try to add a new account in play store and see if the update shows up again?

**Comment by otharion** [comment]
> can you try to add a new account in play store and see if the update shows up again?

I would have to get a new Google account and a new email, things that I don't have. It would be a problem for me. Sorry 😐

**Comment by otharion** [comment]
It's happening again over the night.
![Screenshot_2022-08-18-09-01-51-385_com android vending](https://user-images.githubusercontent.com/15057660/185325964-c9b710cd-c305-47e9-b539-ea9674296ff3.jpg)

**Comment by j-hc** [comment]
If you wont be able to test with the steps I give, I cant help you.
