### ISSUE TITLE
YouTube history is broken 

### ISSUE THREAD

**Issue by mijingbty** [j-hc/revanced-magisk-module#280]
YouTube revanced (not extended) is not taking history

**Comment by mijingbty** [comment]
> History is broken for me since the last two versions. The latest items in my history are from monday. Re-installation and wiping Youtube cache/data didn't fix it.

Working bro, if you do use ad blocker app then 
Add s.youtube.com in allowed list 👍🏻

**Comment by dtrail** [comment]
> > History is broken for me since the last two versions. The latest items in my history are from monday. Re-installation and wiping Youtube cache/data didn't fix it.
> 
> Working bro, if you do use ad blocker app then Add s.youtube.com in allowed list 👍🏻

Holy sh*t! That's it! I'm using multiple layers of blocking, not only ads and stuff, but also trackers, malware and routing all traffic through tor and dnscrypt. So the solution was to whitelist s.youtube.com from my hosts file and attach it to TC.
Thank  you!
