### ISSUE TITLE
YouTube uninstalled when installing latest release

### ISSUE THREAD

**Issue by kenny070287** [j-hc/revanced-magisk-module#281]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
When I installed the latest release (18.25.40), the YouTube app will be uninstalled instead.

Phone model: s20+, rooted
OS: lineage

**Comment by j-hc** [comment]
send module flash log

**Comment by kenny070287** [comment]
![Screenshot_20230721-094222_Trebuchet](https://github.com/j-hc/revanced-magisk-module/assets/28558112/c007749f-1f06-490c-a431-75fcd946ba25)

**Comment by j-hc** [comment]
- disable module
- reboot twice
- flash again

**Comment by j-hc** [comment]
and only official magisk app is supported

**Comment by kenny070287** [comment]
tried it, still the same. im currently running older version of the revanced extended.
also yeah this is the official magisk app

**Comment by j-hc** [comment]
flash the module and dont reboot. check if its working.
