### ISSUE TITLE
Unable to open YouTube on latest build 

### ISSUE THREAD

**Issue by Supposedly-Sam** [j-hc/revanced-magisk-module#283]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
Whenever I try to open YouTube after it was patched with the magisk module, it automatically closes and gives me the following error message ```
StringRef: Resource not found: microg_not_installed_warning```

attached is a video of this behavior

https://github.com/j-hc/revanced-magisk-module/assets/44325112/c2595a74-263c-4222-8438-8b6361e78d34

**Comment by j-hc** [comment]
run this in termux and send output:
`su -c cat /data/adb/modules/ytrv-magisk/module.prop`

**Comment by Supposedly-Sam** [comment]
id=ytrv-magisk
name=YouTube ReVanced
version=v18.23.35
versionCode=19
author=j-hc
description=YouTube ReVanced Magisk module
updateJson=https://raw.githubusercontent.com/Supposedly-Sam/sams-revanced-magisk/update/youtube-update.json

**Comment by j-hc** [comment]
dont create issues for forks. 
try syncing your repo.
