### ISSUE TITLE
Feature request: options.json file setting from config file

### ISSUE THREAD

**Issue by xfilesee34** [j-hc/revanced-magisk-module#290]
Currently cli, patches etc. can be customized from config file. It would be good also to be able pick different options.json file i.e options2.json..

**Comment by j-hc** [comment]
they are different and seperate things.
one is for rvmm builder other is read by the cli. combining them wouldnt make sense and i try to keep config.toml concise.

**Comment by TidalMist** [comment]
https://github.com/j-hc/revanced-magisk-module/pull/385
