### ISSUE TITLE
Triggers root detection

### ISSUE THREAD

**Issue by nikhilgauri** [j-hc/revanced-magisk-module#294]
I'm using KernelSU with revanced module (built locally) and lately I've found some of the apps have started detecting root, 3 of them are:

1. [Axis Bank](https://play.google.com/store/apps/details?id=com.axis.mobile)
2. [Kotak Bank](https://play.google.com/store/apps/details?id=com.msf.kbank.mobile)
3. [IndusInd Bank](https://play.google.com/store/apps/details?id=com.fss.indus)

My build configuration is as follows:
```
[YouTube]
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = "always-autorepeat change-package-name custom-branding disable-zoom-haptics enable-android-debugging enable-debugging export-all-activities predictive-back-gesture remove-screen-capture-restriction remove-screenshot-restriction spoof-wifi-connection tablet-mini-player wide-searchbar"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
```
I did some hit and try, it found out that "detach" module doesn't have any role in this, but the "revanced" module is responsible for the detection.
I've visited [#46](https://github.com/j-hc/revanced-magisk-module/issues/46) and [#56](https://github.com/j-hc/revanced-magisk-module/issues/56) and the latest thread mentions that this could happen. 
So I'm not sure if it is my build configuration or apps have been updated to look at different places.

**Comment by erik9012** [comment]
Rename the folder of the magisk module

**Comment by j-hc** [comment]
is there a way to test the root detection without sending an sms via the banking app?

**Comment by Lu5ck** [comment]
No issue for me. If you are using old kernels below 5.10 (gki 2.0), you are required to install https://github.com/HuskyDG/ksu_unmount_injector

Zygisk also is detectable atm, even with shamiko installed.
