### ISSUE TITLE
Use dev patch?

### ISSUE THREAD

**Issue by KevinNitroG** [j-hc/revanced-magisk-module#296]
Hi, is there a way to use dev patch to build apps? Perhaps the code might need to be changed. But I just ask if it is possible or not 😁 If not, can you implement it when you are free? Thank you.

**Comment by j-hc** [comment]
see [CONFIG.md](https://github.com/j-hc/revanced-magisk-module/blob/44aa8c732d60fd14e644246fd6621ef80bc94750/CONFIG.md?plain=1#L23)

**Comment by j-hc** [comment]
yeah thats possible but wont be added since that'd be an overkill. dev versions are for testing.
