### ISSUE TITLE
YouTube Custom Branding! Noob

### ISSUE THREAD

**Issue by GollumArain** [j-hc/revanced-magisk-module#299]
"SEVERE: Custom branding failed: 
app.revanced.patcher.patch.PatchResultError: https:/example.com/Folder/mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png (No such file or directory)"

I inserted the following in IconPath:
https://example.com/Folder/

The folder has all the icons from mdpi to xxxhdpi. I even renamed the xxxhdpi.png file to "mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png" and to "adaptiveproduct_youtube_background_color_108.png" but still unable to resolve the error. What I'm missing here?

I even experimented the same with local folder as C:\Users\Folder etc.

**Comment by j-hc** [comment]
wrong place to ask. idk what that patch expects you to put there
