### ISSUE TITLE
(BUG/ERRO) Module installation error 

### ISSUE THREAD

**Issue by Fa3l** [j-hc/revanced-magisk-module#30]
![Screenshot_20220821-170413](https://user-images.githubusercontent.com/109783042/185808962-c23dbdf8-56df-4e82-857c-e12fcd030cc8.png)
(Youtube Music 5.17.51 Arm v7a módulo magisk)

Additional Information I AM NOT A PROGRAMMER

**Comment by j-hc** [comment]
i think i know the reason for this issue. will fix it later.

**Comment by j-hc** [comment]
this should fix it. 939d7c
can you try with the latest build

**Comment by Fa3l** [comment]
Bug fixed thanks
