### ISSUE TITLE
Spoofing app to 4.27.53 for canadian users break the library tab

### ISSUE THREAD

**Issue by jacobyo7** [j-hc/revanced-magisk-module#301]
As the title say, Spoofing app to 4.27.53 for canadian users break the library tab, as it show "no internet connection" error when selecting the library tab, rendering it useless and making the user unable to select his/her playlist, artists etc.
I belive this is not a feature offered by the revanced patches, as I can not see this patch aviliable in the revanced manager app, so this is why I posted it here.
To reproduce the bug, activate the 4.27.53 spoofing in settings, restart the app then go to the library tab. At first it seem to work, but refresh the page (pull up) and the no internet error appear and stay until the spoof option is disabled in settings.

**Comment by j-hc** [comment]
revanced bug

> I belive this is not a feature offered by the revanced patches, as I can not see this patch aviliable in the revanced manager app

no this repo does not provide any additional patches
