### ISSUE TITLE
Library button missing

### ISSUE THREAD

**Issue by Zubros** [j-hc/revanced-magisk-module#303]
* Latest Magisk Module Version *

Library button is completely missing and the annoying upgrade button is there. Please replace the upgrade button with Library button. 

Also if possible add an option to hide the samples section. It's super useless, never use it so there is no point in me just clicking it accidentally.
![Screenshot_20230827-063938_ReVanced_Extended_Music](https://github.com/j-hc/revanced-magisk-module/assets/80120399/920e39f6-fa5f-419b-bc7a-6db3873a44fd)

**Comment by Vucko130** [comment]
Well that's not this builder issue. it's patches issue.
