### ISSUE TITLE
KernelSU Installation Error - "su" not found & Mounting Failure

### ISSUE THREAD

**Issue by starraiderx** [j-hc/revanced-magisk-module#306]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

While attempting to flash the "YouTube ReVanced" module using KernelSU, I encountered two primary errors:

1. The su command was not found during the execution of the customize.sh script.
2. The mounting of com.google.android.youtube failed.

Log Excerpt:

```
sh: /data/adb/modules_update/youtube-jhc/customize.sh: line 17: su: not found
* com.google.android.youtube is up-to-date
* Setting Permissions
* Mounting com.google.android.youtube
ERROR: Mount failed!
sh: /data/adb/modules_update/youtube-jhc/customize.sh: line 100: su: not found
* Optimizing com.google.android.youtube
* Cleanup
* Done
```

**Comment by j-hc** [comment]
"su" must be available. probably a kernelsu bug.
