### ISSUE TITLE
Phone boots to recovery after flashing YT Revanced Extended v18.30.37

### ISSUE THREAD

**Issue by ovizii** [j-hc/revanced-magisk-module#308]
I had to reformat my phone and I am starting from scratch. Installed this magisk module via: install from storage:

![Screenshot_20230904-140809_Magisk](https://github.com/j-hc/revanced-magisk-module/assets/837902/ad1360a6-de11-40df-b8d7-ed7dbd2543a1)

I have also installed zygisk-detach v1.3 and detached Youtube.

Btw. before reformatting I was using mindetach but when I saw you recommend the zygisk version, I went with this one. Should I remove it and switch back? 

Open for any hints how to fix this. Is there a particular order for installing/detaching? I did not have YT installed and installed YT Revanced Extended v18.30.37 first, then detached it.

Also, after flashing YT Revanced Extended v18.30.37 and rebooting I end up in Recovery. All subsequent reboots work just fine without going to recovery. Rebooting to System all looks well, all modules are active no problems in the logs.

**Comment by ovizii** [comment]
Just wanted to add that Youtube shows as not installed in the play store. 

![Screenshot_20230904-142144_Google Play Store](https://github.com/j-hc/revanced-magisk-module/assets/837902/8b72c0b1-1d58-4fba-829a-cbb3322addd3)

**Comment by j-hc** [comment]
all the module does is to bind mount revanced apk. that cant possibly cause a rescue party. if you have other modules that mounts - umounts  /data, those are the responsible.

detach modules are not relevant either so there isnt an issue to solve for me.
