### ISSUE TITLE
Build task fails (release works though)

### ISSUE THREAD

**Issue by shivanshkverma** [j-hc/revanced-magisk-module#31]
I just built YouTube app non-root apk and there's this error that I'm getting, just wanted to report it. Thanks a lot for this script!
![Screenshot_20220822-071838](https://user-images.githubusercontent.com/15206857/185823381-e061db7c-a659-4efa-8eb2-8aa3f19ff2b2.png)

**Comment by j-hc** [comment]
should be fixed now 3d8b69c
