### ISSUE TITLE
Slow opening revanced YouTube and yt music magisk module arm 64 version 

### ISSUE THREAD

**Issue by Romanludju** [j-hc/revanced-magisk-module#312]
It took 10 seconds to open youtube and youtube music latest magisk module. 12 July version works the best. This bug only occurs in versions after July 12.

https://github.com/j-hc/revanced-magisk-module/assets/49837296/80ff7b09-32a0-48ce-835c-e759e49051d7

**Comment by j-hc** [comment]
module code did not change since july 12. so unrelated. try running this in termux:
`nohup cmd package compile --reset __PKGNAME >/dev/null 2>&1 &`

if still slow, idk.
