### ISSUE TITLE
Cant install on oneplus 3t (android 9, magisk 23.0) 

### ISSUE THREAD

**Issue by mixalbl4-127** [j-hc/revanced-magisk-module#316]
Moved from: https://github.com/revanced-apks/build-apps/issues/48

**Describe the bug**
Cant install on oneplus 3t (android 9, magisk 23.0) but works perfect on oneplus 9pro

log:
- Copying zip to temp directory
- Installing youtube-revanced-magisk-v18.19.35-all.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
******************
 YouTube ReVanced 
 by j-hc 
******************
*******************
 Powered by Magisk 
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
  inflating: base.apk
  inflating: com.google.android.youtube.apk
  inflating: uninstall.sh
   creating: bin/
   creating: bin/arm64/
  inflating: bin/arm64/cmpr
   creating: bin/arm/
  inflating: bin/arm/cmpr
  inflating: customize.sh
  inflating: service.sh

/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/ytrv-magisk/customize.sh: line 17: nsenter: not found
* com.google.android.youtube is a system app
* Updating com.google.android.youtube to 18.19.35
ls: /data/app/com.google.android.youtube--XQsoOCmsZsqeD_U1RqSiA==/lib/arm64: No such file or directory
* Extracting native libs
* Setting Permissions
* Mounting com.google.android.youtube
ERROR: Mount failed!
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/ytrv-magisk/customize.sh: line 100: nsenter: not found
* Optimizing com.google.android.youtube
* Cleanup
* Done
  by j-hc (github.com/j-hc)
 
rmdir: '/data/adb/modules_update/ytrv-magisk': Directory not empty
- Done

**Comment by mixalbl4-127** [comment]
> try updating your magisk

I have same Magisk (latest with Magisk hide) on other device and no problem with it.

**Comment by j-hc** [comment]
it should still work after a reboot irregardless of the error message
