### ISSUE TITLE
Tiktok Download Option Is not working!

### ISSUE THREAD

**Issue by AdibSadman192** [j-hc/revanced-magisk-module#317]
**Describe the bug**
Until this version TikTok: 31.2.5  download option was working just fine.
but after the update from TikTok: 31.3.4 and onward download option is not showing and not working anymore.
  

**Expected behavior**
It should have show the download menu for every video. 

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android 9, MIUI 10]

**Comment by j-hc** [comment]
revanced problem
