### ISSUE TITLE
Latest change to CI

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#318]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

In the latest change to the CI when running " **if ! git checkout update; then** " it causes the branch to switch into the "update" branch if it does exist and by doing so it can't run the ./build.sh command, but when keeping it in the main branch it relies on the build.md file in the update branch which causes conflict so the ci fails. I'm certain if you run it manually right now you will see what I mean

**Comment by j-hc** [comment]
fixed abe4f03

**Comment by E85Addict** [comment]
```
Run if ! git checkout update build.md; then
  if ! git checkout update build.md; then
    echo "first time building!"
    echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
  else
    UPDATE_CFG=$(./build.sh config.toml --config-update)
    if [ "$UPDATE_CFG" ]; then
      echo "$UPDATE_CFG" > config.toml
      echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
    else
      echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
    fi
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
error: pathspec 'update' did not match any file(s) known to git
first time building!
error: pathspec 'build.md' did not match any file(s) known to git
```

Just gave it a try with no luck

**Comment by E85Addict** [comment]
Latest commit fixed it!
