### ISSUE TITLE
Regarding rip-lib

### ISSUE THREAD

**Issue by bw003** [j-hc/revanced-magisk-module#320]
I want to build only the arm64-v8a version for Youtube and want to remove the armeabi-v7a lib. In the latest commit however I can't find a way to do that.

**Comment by j-hc** [comment]
apkmirror-arch = "arm64-v8a"

**Comment by ramanveerji** [comment]
> apkmirror-arch = "arm64-v8a"

In the magisk version still there are other libs in youtube.apk kindly check.

**Comment by ramanveerji** [comment]
![Screenshot_2023-10-01-23-31-43-702_bin.mt.plus.png](https://github.com/j-hc/revanced-magisk-module/assets/70764724/fd6e99ae-2698-467d-bfb2-33b3f72203c3)

This is the magisk version, and it is having all 4 libs even only arm64 is set. The normal non root version has only 1 arm64 lib.

**Comment by j-hc** [comment]
thats stock apk

**Comment by ramanveerji** [comment]
> thats stock apk
> 

Yes but earlier in stock apk of magisk version there was only 1 lib. And zip was under 100mb. Isn't it possible now?

**Comment by j-hc** [comment]
those were split apks and causing crashes. if you want minimal module zips, disable include-stock in config

**Comment by ramanveerji** [comment]
> those were split apks and causing crashes. if you want minimal module zips, disable include-stock in config

How to do so?

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module/blob/cf35886fd39262ae60142e6a8481aa1c3f49651d/CONFIG.md?plain=1#L32

**Comment by ramanveerji** [comment]
> https://github.com/j-hc/revanced-magisk-module/blob/cf35886fd39262ae60142e6a8481aa1c3f49651d/CONFIG.md?plain=1#L32

Perfect. I must try this. Will it work the same way? I mean without crash?

**Comment by j-hc** [comment]
> > https://github.com/j-hc/revanced-magisk-module/blob/cf35886fd39262ae60142e6a8481aa1c3f49651d/CONFIG.md?plain=1#L32
> 
> Perfect. I must try this. Will it work the same way? I mean without crash?

it stops including stock apk so you need to have youtube installed. thats all

**Comment by ramanveerji** [comment]
Understood thanks
