### ISSUE TITLE
Possible issue with the update.cfg change

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#321]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

I just realized with the last two updates to extended, the build.md gets updated which is needed to see if there needs to be an update, so in example the patches just got updated and it still says no update required since the build,md does not contain revanced/revanced-patches version, only the extended version from inotia is there

**Comment by j-hc** [comment]
should be fixed now a340fb8
