### ISSUE TITLE
Issue with with patches and the new cli changes

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#322]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

The cli now wants to see the patches as -i "Custom branding" -i "Vanced Microg support" instead of the -i custom-branding -i vanced-microg-support"

**Comment by unwillinglyawesome** [comment]
https://github.com/ReVanced/revanced-cli/commit/80a8d88406b2b04d13dca4fb0d7d7d62e1910317

**Comment by j-hc** [comment]
fixed
