### ISSUE TITLE
Unable to exclude and include patches

### ISSUE THREAD

**Issue by ramanveerji** [j-hc/revanced-magisk-module#325]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

Unable to exclude and include patches, I tried adding custom-branding but I got an error. Also, by default when using apkmirror, it is downloading the latest stable version of youtube and not the one recommended by revanced patches.

**Comment by j-hc** [comment]
> I tried adding custom-branding but I got an error

its 'Custom Branding' now (because of revanced). use rvmm-config-gen to generate configs.

> it is downloading the latest stable version of youtube and not the one recommended by revanced patches.

i try and auto selects 18.37.36 which is recommended so its correct

**Comment by ramanveerji** [comment]
> > I tried adding custom-branding but I got an error
> 
> its 'Custom Branding' now (because of revanced). use rvmm-config-gen to generate configs.
> 
> > it is downloading the latest stable version of youtube and not the one recommended by revanced patches.
> 
> i try and with 'auto', it selects 18.37.36 which is recommended so its correct


It got fixed after applying correct patches, thanks for informing about the rvmm-config-gen

**Comment by erickyun** [comment]
> > I tried adding custom-branding but I got an error
> 
> its 'Custom Branding' now (because of revanced). use rvmm-config-gen to generate configs.
> 
> > it is downloading the latest stable version of youtube and not the one recommended by revanced patches.
> 
> i try and with 'auto', it selects 18.37.36 which is recommended so its correct

I'm facing the same problem can you please help?
Must  # config.toml be like this ?

```
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom Branding'"
