### ISSUE TITLE
Use the old keystore?

### ISSUE THREAD

**Issue by trmdi** [j-hc/revanced-magisk-module#326]
Using the new keystore requires reinstalling apps in many devices. It's so annoying. Is it possible to use the old one?

**Comment by j-hc** [comment]
no. you need to uninstall and reinstall for this time

**Comment by trmdi** [comment]
It is possible: https://github.com/ReVanced/revanced-cli/issues/272#issuecomment-1740587534

**Comment by j-hc** [comment]
feel free to that yourself if your data is too important preventing you from uninstalling and reinstalling the apps. previous keystore is in commit history.
