### ISSUE TITLE
[Bug] Script Dowloading Wrong Version of YouTube APK?

### ISSUE THREAD

**Issue by aaxyat** [j-hc/revanced-magisk-module#328]
Hey, I'm getting 
"WARNING: External downloads is incompatible with version 18.39.40. This patch is only compatible with version com.google.android.youtube: 18.16.37, 18.19.35, 18.20.39, 18.23.35, 18.29.38, 18.32.39, 18.37.36, 18.38.44" 
Error When Building modules. My repo is synced with upstream. I've attached logfile for the build below 
[youtube.log](https://github.com/j-hc/revanced-magisk-module/files/12840918/youtube.log)

Here's my config.toml (in txt Format)
[config.txt](https://github.com/j-hc/revanced-magisk-module/files/12840925/config.txt)

**Comment by ramanveerji** [comment]
> Hey, I'm getting 
> "WARNING: External downloads is incompatible with version 18.39.40. This patch is only compatible with version com.google.android.youtube: 18.16.37, 18.19.35, 18.20.39, 18.23.35, 18.29.38, 18.32.39, 18.37.36, 18.38.44" 
> Error When Building modules. My repo is synced with upstream. I've attached logfile for the build below 
> [youtube.log](https://github.com/j-hc/revanced-magisk-module/files/12840918/youtube.log)
> 
> Here's my config.toml (in txt Format)
> [config.txt](https://github.com/j-hc/revanced-magisk-module/files/12840925/config.txt)
> 
> 
> 
> 

I was facing same thing. Generate the config from rvmm config generator and it will be fixed.
