### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#329]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
I have a error when i trying to build app

[-] ABORT: patch names inside excluded-patches must be quoted
Error: utils.sh [-] ABORT: patch names inside excluded-patches must be quoted

While all excluded patches are quoted: 
![Screenshot_20231010_102553_Samsung Internet](https://github.com/j-hc/revanced-magisk-module/assets/133059377/13087d83-9c1f-4703-9b99-d014942b98af)

**Comment by j-hc** [comment]
patches are not in kebabcase anymore. and no your list of patch names in excluded-patches are not quoted.
you can use rvmm-config-gen

**Comment by tgw314** [comment]
> you can use rvmm-config-gen

![Screenshot_20231010-204641_Firefox Nightly_1](https://github.com/j-hc/revanced-magisk-module/assets/52594217/38446bbd-53e5-41f0-b926-4f28fced963b)
Not working in `included-patches`.
