### ISSUE TITLE
RYD Doesn't work

### ISSUE THREAD

**Issue by some1onLSD** [j-hc/revanced-magisk-module#33]
Hello, 
I am using the latest magisk flashable zip of revanced v17.32.35 and dislike count isn't showing up.

EDIT: Return Youtube Dislike is Enabled in settings.

![Screenshot_20220824-000837_YouTube](https://user-images.githubusercontent.com/74503778/186281692-f7f96fa2-f643-4aa0-8be7-bf8916266a7e.png)

**Comment by j-hc** [comment]
> do not create issues related to revanced in this repo
