### ISSUE TITLE
[Feature Request] Build zygisk-detach automatically with the modules.

### ISSUE THREAD

**Issue by aaxyat** [j-hc/revanced-magisk-module#330]
It would be great if we could automatically build zygisk-detach together with the modules. When we used mindtech modules, the built apps automatically got detached by the module. It would be awesome if we could have the same functionality with zygisk-detach.

**Comment by j-hc** [comment]
zygisk-detach already has a very easy to use cli. it also supports detach.txt so you may totally opt out of using the cli.
and if rvmm builds it alongside modules, it will need to include other apps of which people might not be even using the modules.

so i'd say it's a waste for rvmm builder to build it over and over again.
