### ISSUE TITLE
issue regarding rvmm-config-gen

### ISSUE THREAD

**Issue by bw003** [j-hc/revanced-magisk-module#334]
rvmm-config-gen does not work.
It shows the following....

![Screenshot 2023-10-16 184516](https://github.com/j-hc/revanced-magisk-module/assets/116071092/ab642dbc-f7ff-449a-adb3-6f2a31565185)

**Comment by j-hc** [comment]
did you try with a different browser

**Comment by bw003** [comment]
Thanks it's working in another browser.

**Comment by NormTurtle** [comment]
is there any way to use REVANCED like icons? instead of MMT 
? 
![image](https://github.com/j-hc/revanced-magisk-module/assets/108952834/dd480f9d-e8d5-4022-9c7a-aee5aaf7a3c0)
this icon
