### ISSUE TITLE
Regarding youtube stock apk download

### ISSUE THREAD

**Issue by bw003** [j-hc/revanced-magisk-module#335]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

Not able to patch youtube because script is unable to download recommended version from j-hc archive.

**Comment by j-hc** [comment]
which version

**Comment by bw003** [comment]
18.36.39

**Comment by bw003** [comment]
Ok got the error. I added your archive as the source for downloading the stock apk and used apkmirror-arch = "arm64-v8a" with it which was giving error I think. Is there any way I can built arm64-v8a version while keeping your archive as the source.

**Comment by j-hc** [comment]
its for apkmirror only for now. maybe later i will add for others.
