### ISSUE TITLE
Google Play System Update September / October breaks revanced module (data/apex/active)

### ISSUE THREAD

**Issue by amakuramio** [j-hc/revanced-magisk-module#341]
Updating Google Play System to September 2023 breaks the modules, music and revanced magisk not working.
com.android.adservices@341027030.apex & com.android.os.statsd@341010020.apex & com.google.mainline.primary.libs@340941000.apex from data/apex/active

**Comment by j-hc** [comment]
how did you come to this conclusion

**Comment by amakuramio** [comment]
Firstly the August / September security updates of Art runtime broke lsposed, the fix was to delete apex files (now officially fixed), then similarly when I had the latest September updates YouTube revanced extended magisk from your repo stopped working but cleaning the apex files makes it work again. Now using non root with microg that one works. Btw great work

**Comment by nikhilbadyal** [comment]
Is this the reason for app crashing as soon as we open it. 

https://github.com/j-hc/revanced-magisk-module/releases/tag/20220902

**Comment by j-hc** [comment]
all the module does is mounting the modded apk at boot. pretty sure that cant get broken by some updated apex.
cant say anything without seeing logs

**Comment by nikhilbadyal** [comment]
I'll try to get the logs.  Found [this](https://t.me/LSPosedDiscussion/1172530) though.

**Comment by joinmod** [comment]
same issue with revanced crashing at startup

before i had a rvx builder from inotia00
works fine before reboot but after starts crushing

with magisk module same thing...

**Comment by j-hc** [comment]
1 month and no logs. cant fix.
