### ISSUE TITLE
Cannot update youtube-revanced-v18.38.44-all.apk from release 20220898 to release 20220904 - signature has changed?

### ISSUE THREAD

**Issue by crok** [j-hc/revanced-magisk-module#347]
Tried to update my Youtube Revanced installation from release [20220898](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220898): I use the apk [youtube-revanced-v18.38.44-all.apk](https://github.com/j-hc/revanced-magisk-module/releases/download/20220898/youtube-revanced-v18.38.44-all.apk) and trying to update to the latest version at the moment [youtube-revanced-v18.38.44-all.apk](https://github.com/j-hc/revanced-magisk-module/releases/download/20220904/youtube-revanced-v18.38.44-all.apk) from release [20220904](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220904) but I can't install it because it seems that the signature is different. Is it intentional? Has the signature changed again and we have to reinstall the whole app again?

**Comment by j-hc** [comment]
yes it was changed
