### ISSUE TITLE
Version #'s for yt going lower?

### ISSUE THREAD

**Issue by Dnominated** [j-hc/revanced-magisk-module#350]
2 weeks ago the release was 18.42.41. Now it's 18.40.34. Not sure what is going on.

**Comment by j-hc** [comment]
idk. need to ask the patch developers.

**Comment by ramanveerji** [comment]
> 2 weeks ago the release was 18.42.41. Now it's 18.40.34. Not sure what is going on.

Revanced and Revanced Extended patches are different, both patch for different yt versions.

**Comment by Dnominated** [comment]
I don't know why you just don't go look, instead of making something up: 

I am comparing the same: revanced youtube extended magisk module from two weeks ago and more recently. I've made screenshots, but this platform doesn't have the ability to do upload them.

Here's some links to the screenshots:
https://ibb.co/YXPFcTt
https://ibb.co/NWvfqqj
