### ISSUE TITLE
Request to add own archive.org 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [j-hc/revanced-magisk-module#351]
Hi j-hc,
I see n the config you put your own archive.org file hosting. Would be nice if you also add support to own archive.org as alternative link. 
My motivation to request this is:
1. I (my self) can maintain my own needed revanced apps. So, if there is an update, i can upload them as soon as possible to my own archive.org
2. Simplify you to maintain revanced apps. Likely you lil'bit late to update some revanced apps.
e.g this reddit still old ..43.0 https://archive.org/download/jhc-apks/apks/com.reddit.frontpage
There is newer version ..44.0 though

Hope you can fulfill my request above.

Sincerely,
WZT

**Comment by j-hc** [comment]
i dont upload or keep track of the apks by hand. i have a script that uploads them before build worklflow run with the updated revanced patches.
you can change the archive.org url to yours in the config: https://github.com/j-hc/revanced-magisk-module/blob/7727e7fc0891090dbb20b285bef078281737048a/config.toml#L51
it needs to be in the same format.

**Comment by What-Zit-Tooya** [comment]
How to uplaod to archive.org like your folder structure? seems archive.org does not provide create folder in their web uploader interface

**Comment by j-hc** [comment]
thats up to you to find out.
the only reason i created that archive is to stop users of rvmm builder from spamming apkmirror with constant re-builds.
if i provide the scripts i use to create that archive, im pretty sure everyone will start spamming archive.org which is what im trying to avoid.

**Comment by trmdi** [comment]
> the only reason i created that archive is to stop users of rvmm builder from spamming apkmirror with constant re-builds.

Don't you worry about spamming archive.org?

**Comment by trmdi** [comment]
https://github.com/j-hc/revanced-magisk-module/pull/384
