### ISSUE TITLE
Why are youtube versions going down?

### ISSUE THREAD

**Issue by Dnominated** [j-hc/revanced-magisk-module#352]
(https://github.com/j-hc/revanced-magisk-module/issues/350#issuecomment-1806797103)
( Comments without getting your facts straight. )

I don't know why you just don't go look, instead of making something up:

I am comparing the same revanced youtube extended magisk module from two weeks ago and more recently. I've made screenshots, but this platform doesn't have the ability to do upload them.

Here's some links to the screenshots:
https://ibb.co/YXPFcTt
https://ibb.co/NWvfqqj

**Comment by cyberboh** [comment]
Why you just don't look revanced extended changelog? It's enough to answer yours

**Comment by j-hc** [comment]
stop spamming issues
