### ISSUE TITLE
Is there a way to hide suggestions below the currently playing video, and expand comments fully?

### ISSUE THREAD

**Issue by Dnominated** [j-hc/revanced-magisk-module#353]
In place of displaying algorithm 'suggested videos' below the currently playing one: *Show the full comments*, which, to see the comments currently requires tapping to expand them partially, then tapping Read More on *every single comment* to see the full comment if it's more than a few lines.

A) An option to get rid of suggested videos. If I want to watch something new, I'll go back to the home page or subscriptions.
B) Show the comments fully instead of the A) suggested videos.
C) Expand all comments automatically, to show the full comment/reply, instead of having to tap on 'Read More' for every single comment.

Also, for compliance with Accessibility, having that feature simplifies the display, for those who have either motor neuron issues or simply have large hands that can't pinpoint the Read More. In the case of the former, it cleans-up the screen so less non-relevant garbage/noise is displayed, and eliminates an extra step of seeing what people are saying about the video, and interacting. For the latter, it can take several tries to get Read More to expand, and that has to be done for every single comment more than a few words.

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO Describe the bug of the rvmm builder or the modules
