### ISSUE TITLE
Youtube crashes with only audio playback

### ISSUE THREAD

**Issue by KBapna** [j-hc/revanced-magisk-module#354]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
I just updated the Magisk Module from the manager. Now YouTube crashes as soon as any video is played but audio playback keeps going until it is stopped(force stop).

I can provide logs but can't find the option it the app 😅.

I tried reverting to the old module(it was still in my downloads folder) but that also kept crashing.

I tried clean install with both modules:
1) Remove youtube and module
2) Reboot and check if they are gone
3) Install module again and reboot
Still same issue is there.

**Comment by j-hc** [comment]
cant say anything without a logcat

**Comment by KBapna** [comment]
Thanks for the reply @j-hc 
It literally fixed itself, I have no idea how.
But it works so no problem. I'll comment again if it crashes again.
 
BTW It's one of the best repo and module out there, and works flawlessly everytime I have used it. Great Work.
