### ISSUE TITLE
Searching multiple sources disabled?

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#355]
Hello, it's not a bug but a question, I wanted to know if this repos, when there are several sources (rv and rvx) ci.yml does not launch build / run, I can try to update the repository, check the parameters, ci.yml skip the step "should build?" until I manually start build.yml.

It's no longer possible? or it's a wrong setting on my part.

**Comment by j-hc** [comment]
they work in this repo as you can see
