### ISSUE TITLE
aapt2 optimize in config

### ISSUE THREAD

**Issue by TidalMist** [j-hc/revanced-magisk-module#359]
Thank you so much for what you did.
https://github.com/TidalMist/revanced-arm7-arm8-nonroot
I have added aapt2 optimize from build-tools in included software of ubuntu-latest https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#android
For apk and module with an excluded to not use android with it. But I didn't rename repo urls in build-termux.sh, and something else what fails build in termux, to test if it excluded, i think it will. And dont know will it build on desktop.
I found you wrote that it is not matter to reduce the size but it would still be good for slow internet, phones and many people installs mods with deleted densities, languages.
I don't want to figure out yet how to make variables densities(--target-densities xxhdpi) languages(-c it, it-rIT) from the config to the aapt2 command.
Maybe add other aapt2 and zipalign apksigner options to config.
Or comment # build-tools commands and make faq how uncomment, change options and edit utils.sh, and need remove --unsigned from "if build-mode module " if uncomment
Also i convert ks.keystore to .pk8 .x509.pem because apksigner fails
in general, I leave it to you if you want to do it for distant future "roadmap"

**Comment by j-hc** [comment]
its not really obvious what you are asking exactly. if you want to remove particular resources from apks, the ideal way is to write a revanced patche that'd remove them.

**Comment by TidalMist** [comment]
Feature request to add removing densities and languages like how riplib in config.toml
Target-densities = hdpi,xhdpi,xxhdpi,xxxhdpi (1 density or separated by commas)
Locales(or Languages) = it,it-rIT,ru,ru-rRU (it will be difficult to explain what write here, for who fork and edit confing, without info what locales in apk)
https://developer.android.com/tools#tools-build
Have you seen what I changed in the fork? It works already
I think if auto insert highest sdk version in name of directory build-tools with semver or something it will be more reliable and universal (for months, years) than patches which will need to be corrected if something fails.
And the most important thing is who will make these patches and when.
Sorry to clutter you with this information, just want to share my thoughts on how to do it if anyone wants to finish it up

**Comment by j-hc** [comment]
the patch would be like 10 lines. like i said, if you just want to remove resources, the correct way is to write a revanced patch, there is nothing non-universal about it either. apk structure is always the same. i might write the it and put it in a repo later.
