### ISSUE TITLE
Cannot set the app's battery usage to restricted mode

### ISSUE THREAD

**Issue by TrayBer** [j-hc/revanced-magisk-module#361]
In the case of vanced YouTube, for example.
when I set it to "`Restricted`" mode in "App Battery Usage" and then went back to check it again, it **automatically** changed to "`Optimized`"mode.
I don't have this problem with apps I've downloaded from Google Play.

<img width="360" alt="aohe9nhwe987weno39" src="https://github.com/j-hc/revanced-magisk-module/assets/8769077/7c0158bb-9ddd-4da6-9f8e-f5b8f80cda05">

**Comment by j-hc** [comment]
probably a rom issue
