### ISSUE TITLE
Device reboot and revanced get uninstalled 

### ISSUE THREAD

**Issue by SEAL300** [j-hc/revanced-magisk-module#362]
I have a strange behavior with revanced module with stock oos 11 on OnePlus 6 with magisk 26.4 
Everything after installing the module is ok for awhile but out of nothing the device soft reboot and revanced get uninstalled (even if it isn't opened ) i think its google play doing because if i froze it the phone doesn't reboot and i use revanced just fine ,i had the same issue with another fork of revanced but i guess its the same thing

**Comment by j-hc** [comment]
you need to fix the soft reboots. any kind of forced reboot will cause module to break and you will need to reflash.

**Comment by ruthl3sss** [comment]
> you need to fix the soft reboots. any kind of forced reboot will cause module to break and you will need to reflash.

I'm sorry, may I ask how fix them?
