### ISSUE TITLE
Releases page suggestion for MicroG

### ISSUE THREAD

**Issue by mycrowgee** [j-hc/revanced-magisk-module#363]
In the releases page, the link for the MicroG is pointing to the one used when Vanced project was still going.

![vanced microg](https://github.com/j-hc/revanced-magisk-module/assets/153394340/b356bf0d-d1b5-4874-8e5b-5ba7664f6649)

Now, it's been almost two years since the last update of it.
Meanwhile the MicroG project has had [other updates](https://github.com/microg/GmsCore/releases) as well.
Under forks, there is [YT-Advanced](https://github.com/YT-Advanced/GmsCore) as the second most starred project after Vanced fork.

![Advanced](https://github.com/j-hc/revanced-magisk-module/assets/153394340/7f8511e7-9449-4a20-aa5a-80023f82b07e)

They also have a version that is up to date with the latest changes for GmsCore and works with Revanced Extended.
Suggestion: Replace the old Vanced MicroG with YT-Advanced MicroG in the releases page.

**Comment by j-hc** [comment]
Why? The one linked doesnt work anymore?

**Comment by mycrowgee** [comment]
Because [revanced extended builds](https://github.com/j-hc/revanced-magisk-module/releases) keep coming out even tho a version from [the start of the year](https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-01-36-release/) would work just fine, if not for the fixes and improvements to MicroG since then such as:
https://github.com/microg/GmsCore/pull/2025
https://github.com/microg/GmsCore/pull/2028

**Comment by j-hc** [comment]
i wont add any other links as long as it works fine. everyone is free to download whichever. they are all the same and just implement the minimum api to keep account sign in possible.
