### ISSUE TITLE
Download failed Youtube Music

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#365]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
[+] Choosing version '6.31.55' for Music-Extended
[+] Downloading 'Music-Extended' from apkmirror
2023-12-15 05:54:45 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-31-55-release/ [257737] -> "-" [1]
[-] ERROR: Could not download 'Music-Extended' from apkmirror with version '6.31.55', arch 'all', dpi 'nodpi'
Error: utils.sh [-] ERROR: Could not download 'Music-Extended' from apkmirror with version '6.31.55', arch 'all', dpi 'nodpi'
[-] ABORT: All builds failed.

Error: utils.sh [-] ABORT: All builds failed.

Error: Process completed with exit code 1.

**Comment by j-hc** [comment]
"apkmirror-arch" is changed "arch"
