### ISSUE TITLE
How to keep Twitter out of Google play's pending updates list?

### ISSUE THREAD

**Issue by TrayBer** [j-hc/revanced-magisk-module#366]
I'm using the last version of Twitter renamed to X (don't like using X), how do I get the revanced version of Twitter to not be on the pending updates list in Google Play? (I'm not a developer)

**Comment by j-hc** [comment]
> how do I get the revanced version of Twitter to not be on the pending updates list in Google Play?

use zygisk-detach if you are rooted.

> Why is it that YouTube is customized with icons, names, and package names, but Twitter's info is all original?
Is it possible to also provide customized icons, names, package names similar to YouTube?

if there is a patch for it, yes. otherwise no. i dont know and keep track of which apps have which patches.
