### ISSUE TITLE
Non-root YouTube crashes when launched, Android 9 

### ISSUE THREAD

**Issue by KrazyLurt** [j-hc/revanced-magisk-module#370]
YouTube Revanced, apk, tested all the pre built versions available in releases, and the same issue when building and patching via Manager. 
It crashes when launched. Tried microg v0.2.24, 0.2.27 & 0.2.3 

This is on my Android 9 Lenovo M10 tablet. Flashable zips works fine. 
Have no such issues in my Android 13 phone.
 
[log.txt.zip](https://github.com/j-hc/revanced-magisk-module/files/13756908/log.txt.zip)

**Comment by KrazyLurt** [comment]
Maybe all microG related since I can get YouTube Revanced to launch with no account registered for microG. Maybe microG is crashing causing YouTube Revanced to crash as well. 

I've tried a bunch of versions and forks of microG, no luck

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO Describe the bug of the rvmm builder or the modules
