### ISSUE TITLE
Video Enhancements and Application Name Change Request

### ISSUE THREAD

**Issue by DeveloperMonuar** [j-hc/revanced-magisk-module#372]
### Issue 1: Enabling 4K and 8K Video Option for Every Phone

**Feature Request:**
I propose the implementation of an option to enable 4K and 8K video playback for every phone in YouTube Vanced. Currently, it seems that this feature might not be available on all devices.

**Details:**
Device Model: realme 9i
Android Version: 13
YouTube ReVanced Extended: 18.45.43

**Issue Description:**

I guess my phone is compatible with 4k video options. I used a YouTube Magisk module previously that can play without any hesitation to play 4k and 8k videos.
Not only my phone I think 2k, 4k, and 8k video need to enable for every phone.

**Expected Behavior:**
I expect that enabling 4K and 8K video options should be possible on all devices, providing users with the flexibility to enjoy high-resolution content based on their device capabilities.

**Screenshots:**
![issues](https://github.com/j-hc/revanced-magisk-module/assets/97757010/f1fc29b5-bd15-4fca-b141-6afa01baead7)

### Issue 2: Request for Name Change to Enhance Brand Recognition

**Feature Request:**
I am submitting a request to consider changing the current app name "ReVanced Extended" to a name that aligns more closely with the official YouTube branding. Suggested names include "YouTube," "YouTube Pro," or "YouTube Premium."

**Reasoning:**
The current name, "ReVanced Extended," may not immediately convey its association with YouTube, potentially causing confusion among users. A name that includes "YouTube" or closely resembles the official branding would enhance brand recognition and user trust.

**Benefits:**
Brand Consistency: Aligning with the official YouTube branding improves user recognition and trust.
User-Friendly: A name like "YouTube" or "YouTube Pro" is more intuitive for users.

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO Describe the bug of the rvmm builder or the modules
