### ISSUE TITLE
Add support to Youtube Revanced for Android 5 and 6

### ISSUE THREAD

**Issue by cyberboh** [j-hc/revanced-magisk-module#378]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

I'm trying to add support into my `config.toml` to support building revanced for android 5 and 6 but always ended up with error/failed.

**Error log:**

```
Unknown options: '--keystore-entry-***', '--keystore-***', '--signer=jhc', '--alias=jhc'
Possible solutions: --keystore
[-] Building 'YouTube-5-6' failed!
Error: utils.sh [-] Building 'YouTube-5-6' failed!
```

**Environtment which are i'm used:**
https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.7
https://github.com/kitadai31/revanced-integrations/releases/tag/v0.96.7
https://github.com/kitadai31/revanced-cli/releases/tag/v3.2.0

**Config:**
https://github.com/cyberboh/revanced-compile-craft/blob/41881bd42a86ce654f433914b47a129cb20ab5b0/config.toml#L42

**Comment by j-hc** [comment]
the cli you are using is old

**Comment by j-hc** [comment]
well there is nothing android version dependent in the cli. patches can be updated to use the newer ones. since the cli receives breaking changes time to time, i cant support them all. your only option is to edit the args passed to the cli in patch_apk function

**Comment by j-hc** [comment]
yes. like i said.

> ...old patches can be updated to use the newer versions of the cli... your only option is to edit the args passed to the cli in patch_apk function

im closing the issue as this is not something i can fix.
