### ISSUE TITLE
Cannot build YouTube with the latest revanced patches (v4.0.1)

### ISSUE THREAD

**Issue by Lassie111** [j-hc/revanced-magisk-module#379]
My config for YouTube is
```
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Change header' 'Custom branding'"
```
I'm getting the following error during execution of "Build Modules":
```
SEVERE: null failed:
app.revanced.patcher.patch.PatchException: 'null' raised an exception while being closed: app.revanced.patcher.patch.PatchException: temp/tmp.TXkVNV5txG/temp/tmp.TXkVNV5txG/res/values/strings.xml (No such file or directory)
```

Building apk with revanced-cli on PC works, so I think it's incompatibility of rvmm builder with the newest version of revanced patches.

**Comment by ViktorVoloshko** [comment]
I think the reason is the fact that `MicroG support` was renamed to `GmsCore support`.

**Comment by Lassie111** [comment]
> > Building apk with revanced-cli on PC works
> 
> it's the [official](https://github.com/revanced/revanced-cli/releases) one, not [j-hc's edit](https://github.com/j-hc/revanced-cli/releases) right?

Yes. I tried with `cli-source = "ReVanced/revanced-cli"` in `config.toml` but it doesn't work either.

**Comment by j-hc** [comment]
its a revanced-cli bug. workaround is to not pass temp dir.
