### ISSUE TITLE
Youtube revanced autoplay not working.

### ISSUE THREAD

**Issue by RANZN** [j-hc/revanced-magisk-module#38]
Hey I know it's not the right place as you only create build. 
But I was searching for something to solve the issue of youtube revanced autoplay not working and got the solution for that by excluding the hide-autoplay-button patch.
**-e hide-autoplay-button**
So could you please release a build once removing this patch.

**Comment by j-hc** [comment]
i already answered you here https://github.com/j-hc/revanced-magisk-module/issues/22#issuecomment-1237495027
