### ISSUE TITLE
Google Uninstall The Module Automatically

### ISSUE THREAD

**Issue by Mnshawaty** [j-hc/revanced-magisk-module#380]
Guys I have a problem in Android 14
 i had **disabled** **auto update** for YouTube

 but I don't know how google remove and uninstall it from device

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module/blob/a5f336ba7d6fe78db4b7bc48dd85996256884602/README.md?plain=1#L11

**Comment by ruthl3sss** [comment]
> https://github.com/j-hc/revanced-magisk-module/blob/a5f336ba7d6fe78db4b7bc48dd85996256884602/README.md?plain=1#L11

The issue remains after that
