### ISSUE TITLE
Premium branding

### ISSUE THREAD

**Issue by username227** [j-hc/revanced-magisk-module#381]
Hi, I love this module, makes everything easier. In the past, i've noticed or been able to apply the premium branding on the app; it helps me to make sure that the right version of youtube is still installed, but I no longer see this or see any way to apply this. Is there any way you could bring this back? Thanks!

**Comment by trmdi** [comment]
You can enable the `Custom branding` patch to change the icon. To change the top left heading, you can use the `Change heading` patch. But this patch show the Revanced logo, not the Premium one.
