### ISSUE TITLE
app has performance issues and certain settings are missing or non intuitive 

### ISSUE THREAD

**Issue by Stroov** [j-hc/revanced-magisk-module#386]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
whenever i close the screen video playback will stop after a minute or 2 , unlocking display then opening revanced solves it 

if i have closed the screen sometimes the app will be killed out of memorry (this is rare )
 
many a times sponser block and return dislike api gets timed out 2-3 times a day 
if you want to play the video on portrait mode you have to press on the display till the play pause button comes up then use the back button on android nav bar to turn the screen back to portrait this behavior is time consuming and irrating , where as stock yt will just put it in portrait or half screen mode , 
rest everything is amazing

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO

**Comment by Stroov** [comment]
where should i report revanced bugs  im new to all this , also what to do if even after zygisk detach youtube is showing in playstore i hope you dont mind showing me the steps

**Comment by j-hc** [comment]
> where should i report revanced bugs  im new to all this

to the revanced github

> also what to do if even after zygisk detach youtube is showing in playstore i hope you dont mind showing me the steps 
 
steps for zygisk-detach is in its readme
