### ISSUE TITLE
One-time update

### ISSUE THREAD

**Issue by Bahoue** [j-hc/revanced-magisk-module#387]
Hello and thank you for your work.
I use 'Youtube revanced extented magisk'.
When there is an update of Music or TikTok or other, the module proposes an update.
Is it possible that the module only suggests an update when it's for Youtube?

Maybe this is already the case, but I must admit I'm not very good with commands and I haven't found it.

Thanks

**Comment by j-hc** [comment]
that isnt possible because there is no way to determine what apps patches are updated for
