### ISSUE TITLE
YouTube builds without custom branding cant be installed

### ISSUE THREAD

**Issue by Kuuuube** [j-hc/revanced-magisk-module#388]
On some phones with youtube pre-installed and made not possible to uninstall, it is impossible (or very unreasonable) to try to get youtube revanced to install without custom branding. 

With the custom branding enabled it is treated as a separate app and this is not an issue.

I had used previous builds from this repo (roughly 6 months back) and they did have custom branding. The config file seems to have never been changed on this so I assume a default was changed somewhere. 

I ran off a build myself with this config and it works great. I think it is worth considering adding `'Custom branding'` to the included patches for your builds.
```
[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = "'Custom branding'"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
```

**Comment by j-hc** [comment]
> With the custom branding enabled it is treated as a separate app and this is not an issue

no, its the microg patch that changes the package name
