### ISSUE TITLE
Age

### ISSUE THREAD

**Issue by doobydooby72** [j-hc/revanced-magisk-module#389]
Just wanted to mention that the age restriction bypass script on greasyforks site still works so there does still seem to be methods to get around that.

Sorry this is probably the wrong place for this but im horrible at navigating git and even more so with how compartmented this app is and also couldnt see an option for discussions. Thanks

**Comment by j-hc** [comment]
i have no idea what this is about

**Comment by doobydooby72** [comment]
Since most 3rd party apps bypassed the age/varified account limit but most seem to have had issues of recent with the new requirement.
