### ISSUE TITLE
Workflow run failed

### ISSUE THREAD

**Issue by Loup-Garou911XD** [j-hc/revanced-magisk-module#39]
>Binary diffing temp/music-revanced-v5.22.54-arm-v7a.apk against temp/music-stock-v5.22.54-arm-v7a.apk
>xdelta3: file open failed: read: temp/music-revanced-v5.22.54-arm-v7a.apk: No such file or directory
>Error: Process completed with exit code 1.

**Comment by j-hc** [comment]
should be fixed now 996d5ae
