### ISSUE TITLE
Are extended patches not being maintained anymore?

### ISSUE THREAD

**Issue by Multowz** [j-hc/revanced-magisk-module#390]
The [repository](https://github.com/inotia00/revanced-patches) has been archived. And your latest release doesn't include extended versions. Does that mean aren't they getting update anymore? Do you recommend switching to non-extended ones?

**Comment by j-hc** [comment]
> Does that mean aren't they getting update anymore?

idk, it was archived so i disabled the builds

**Comment by FrenchToucan** [comment]
@j-hc YT-Advanced/ReX-patches is continuing to develop Extended. I manually patched YT, YTM, and Reddit using his most recent patches and they work well. Any interest in building?

**Comment by Multowz** [comment]
> @j-hc YT-Advanced/ReX-patches is continuing to develop Extended. I manually patched YT, YTM, and Reddit using his most recent patches and they work well. Any interest in building?

How did you patch it? I didn't see any guide in readme file of that repository.

**Comment by FrenchToucan** [comment]
> > @j-hc YT-Advanced/ReX-patches is continuing to develop Extended. I manually patched YT, YTM, and Reddit using his most recent patches and they work well. Any interest in building?
> 
> How did you patch it? I didn't see any guide in readme file of that repository.

The same as any other source. I had RVX Manager installed so I just changed the sources.

![Screenshot_20240211-123610.png](https://github.com/j-hc/revanced-magisk-module/assets/41240662/da55d637-c5f9-42d4-b392-2eb54785e110)

**Comment by FrenchToucan** [comment]
@Multowz YouTube and YouTube Music Extended based on YT-Advanced patches are [here](https://github.com/revanced-apks/build-apps). I like the Reddit Revanced Extended client which isn't in that repo so I am building it [here](https://github.com/FrenchToucan/autobuild-Reddit-ReX).
