### ISSUE TITLE
Request to Release a Build of Twitter (X ) apk without the "For You" Tab

### ISSUE THREAD

**Issue by adangoth** [j-hc/revanced-magisk-module#391]
Hi,

I have been using Twitter in mobile app for a long Time , and recently after the elon musk takeover of Twitter ( now X), I have got annoyed of many things like frequent ads, Annoying for you tab, preference to videos in Search bar etc.,

I can still see there are many ads coming in my TL occasionally. 
I would like to request to Release a seprate build whenever possible, without the for you tab. Its really impossible to catch up all tweets..

**Comment by adangoth** [comment]
Hi,

Kindly request you to help with this and close the incident

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO

**Comment by mingaldrichgan** [comment]
@adangoth You are looking for [this repo](https://github.com/ReVanced/revanced-patches/issues).
