### ISSUE TITLE
No x86 for root

### ISSUE THREAD

**Issue by Troylink** [j-hc/revanced-magisk-module#392]
Trying to flash revanced root brings up unsupported arch x86 can we get an x86 version😭

**Comment by j-hc** [comment]
what phone do you use

**Comment by Troylink** [comment]
Bliss os

**Comment by hientn** [comment]
I Have same issue with my car head unit (Teyes CC2, Andoid 8.0, CPU SC9853i)

**Comment by Yukimitsu-Tokito** [comment]
**Try Removing**
This [line](https://github.com/j-hc/revanced-magisk-module/blob/main/utils.sh#L437) or your arch i.e `-rip-lib x86` in util.sh
and build Youtube

**Comment by j-hc** [comment]
added x86 support to modules 64b9266

**Comment by Troylink** [comment]
Hey thanks for working on the problem but after trying to flash the zip it failed again I have attached a picture hope this helps
![Screenshot_20240302-232232_MRepo](https://github.com/j-hc/revanced-magisk-module/assets/104437622/65be3ba7-73c6-48af-844f-b9c74aef7e67)

**Comment by j-hc** [comment]
you said x86 in the issue. your device is x64
