### ISSUE TITLE
Question: Keep config 

### ISSUE THREAD

**Issue by likkai** [j-hc/revanced-magisk-module#4]
When I updated the module through magisk, my configuration was lost. Is it possible to keep those configurations after updating?

**Comment by j-hc** [comment]
1. did you build locally or on actions?
2. what config are you talking about?

**Comment by likkai** [comment]
1. I built the root version (17.28.34) using actions and upgraded to version 17.29.34 through magisk 
2. The config I was talking about was excluding the patches (-e packagename) in the file build.conf

**Comment by j-hc** [comment]
well that shouldnt happen. module you built on your repo will always use your build.conf file. you can have a look at workflow logs.

**Comment by likkai** [comment]
I think I wasn't clear just now so I'll explain it again 😅
The module I built on GitHub used my build.conf file (works normally) but afterwards when I update the module from the magisk update button (I didn't build it again on GitHub), the patches I excluded was included. 
For example, I built the module with `-e custom-branding`, is there a way to update the module through magisk (not building it on GitHub) with the same configurations I saved in the build.conf file? (The `-e custom-branding` patch)

**Comment by j-hc** [comment]
The thing is if you didnt build again, you cant possibly receive an update from inside magisk. I would make sure you are not using the module from my repo as that way you would receive updates from my repo. you can go to /data/adb/modules/ytrv-magisk/module.prop file and see the updatejson if it points to your repo.

**Comment by likkai** [comment]
I see, thanks for your help
