### ISSUE TITLE
Ads before video play

### ISSUE THREAD

**Issue by panosru** [j-hc/revanced-magisk-module#40]
Hi, thanks for the repo!

Occasionally, I'm getting ads before the video starts to play. I flashed the release version, then I logged in with my account, I enabled shorts in the settings and I haven't touched anything else. 

It doesn't happen always, but it does from time to time.

**Comment by Loup-Garou911XD** [comment]
I think you should ask in https://github.com/revanced/revanced-patcher for revanced related issues

**Comment by panosru** [comment]
@Loup-Garou911XD yeap, I now realise this is a wrapper script for installing a proper version of the revanced apk and patching it.
