### ISSUE TITLE
Still can't install module on x86

### ISSUE THREAD

**Issue by Troylink** [j-hc/revanced-magisk-module#401]
Just tried the latest update it seems to not install @ @
![Screenshot_20240303-123705_KernelSU](https://github.com/j-hc/revanced-magisk-module/assets/104437622/86afa640-ccb8-4686-ac64-4f73c0e72672)
Thank you

**Comment by j-hc** [comment]
should be fine now 45ac4ff

**Comment by Troylink** [comment]
Thank you do I have to wait for a new build

**Comment by j-hc** [comment]
you can fork or create a template yourself and build. its on readme

**Comment by Troylink** [comment]
Tried building but it failed 
![Screenshot_20240304-100609_Termux](https://github.com/j-hc/revanced-magisk-module/assets/104437622/56c92ba3-94ae-437b-9273-25f749db5782)
