### ISSUE TITLE
A Request to add "Sim-spoofing" to Tiktok-revanced

### ISSUE THREAD

**Issue by Cico90** [j-hc/revanced-magisk-module#404]
Hello devs,

You are very much appreciated for the hard work you have been doing, it is just that I noticed that Tiktok-revanced doesn't have in its settings the "Sim-spoof" option
 I come here so I dont have to patch apks myself but, loosing a helpful option that I need, force me to patch the app all over again. So if you dont mind it is very advisable to include the "Sim-spoof" option in Tiktok revanced so we don't miss an option.

Peace.

**Comment by j-hc** [comment]
added sim-spoof patch fca5cd0

**Comment by Cico90** [comment]
I appreciate it! 👍
