### ISSUE TITLE
Could not download Youtube Music

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#405]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
[+] Choosing version '6.42.52' for Music-Extended
[+] Downloading 'Music-Extended' from apkmirror
2024-03-06 15:58:10 URL:https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-09-37-release/youtube-19-09-37-android-apk-download/ [320470] -> "-" [1]
2024-03-06 15:58:10 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-42-52-release/ [270321] -> "-" [1]
[-] ERROR: Could not download 'Music-Extended' from apkmirror with version '6.42.52', arch 'arm64-v8a', dpi 'nodpi'
Error: utils.sh [-] ERROR: Could not download 'Music-Extended' from apkmirror with version '6.42.52', arch 'arm64-v8a', dpi 'nodpi'

**Comment by j-hc** [comment]
did you check apkmirror if there is a non-bundle apk available of that version and arch of youtube music?

**Comment by gnadgnaoh** [comment]
> did you check apkmirror if there is a non-bundle apk available of that version and arch of youtube music?

Yes

**Comment by gnadgnaoh** [comment]
Apkmirror have arm64-v8a and nodpi, non-bundle apk but cant download

https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-42-52-release/youtube-music-6-42-52-android-apk-download/

**Comment by j-hc** [comment]
thats marked as bundle by apkmirror so its a apkmirror issue. cant fix.

**Comment by IgorTHh1337** [comment]
try to use uptodown download instead of apkmirror
