### ISSUE TITLE
Support for Anddea patchs

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#406]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**

Today, YT-Advanded discontinued ReX, its spiritual successor (Anddea) is taking over the project, but, for some unknown reason, ReVanced Magisk Module can't apply patches on Youtube, it supports RV's cli and Inotia00's cli, but the 2 cli (yours and Inotia00's) have the same problem.

**Comment by j-hc** [comment]
updated my fork of cli to v4.4.1

**Comment by IgorTHh1337** [comment]
YTM does not patch normally using latest anddea's dev patches. Some patches are failing for unknown reasons...
YT works good.

**Comment by kevinr990** [comment]
> YTM does not patch normally using latest anddea's dev patches. Some patches are failing for unknown reasons... YT works good.
> 
> Upd: Set YTM version to 6.44.54, seems it works...

As this topic is closed, you may want to open another one
