### ISSUE TITLE
Workflow run fails

### ISSUE THREAD

**Issue by Loup-Garou911XD** [j-hc/revanced-magisk-module#41]
>Error: Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/OptionsContainer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)

**Comment by widyou** [comment]
I have same problem.

**Comment by E85Addict** [comment]
This is from the CLI and Patches not having the latest patcher dependency set to 4.1.3

**Comment by Loup-Garou911XD** [comment]
> This is from the CLI and Patches not having the latest patcher dependency set to 4.1.3
Can you suggest a fix

**Comment by Loup-Garou911XD** [comment]
Oh wait is the PR for this issue?

**Comment by E85Addict** [comment]
> Oh wait is the PR for this issue?

The pr is for a different issue, but Revanced needs to update their patches and CLI in which I've already made PRs for and J-HC needs to update his CLI as well

**Comment by E85Addict** [comment]
Actually after further investigation and using all of revanceds current files, J-HC just needs to update his CLI and it should work again

**Comment by j-hc** [comment]
this was a bug by revanced side, will be fixed.
