### ISSUE TITLE
Youtube 19.02.39 Magisk isn't working anymore as of today

### ISSUE THREAD

**Issue by shaft17** [j-hc/revanced-magisk-module#417]
I'm not sure if this is related to Revanced or any other thing.
As of today Youtube Revanced stopps with a message "App isn't supported, please update"
Temp solution is to disable "spoof version", but then the issue with loading screen after 30s re-appears.

In Reveanced Thread at reddit, there is a solution for non-rooted devicxes, you should update MicroG/GMSCore too.

As Magisk isn't relying on MicroG, it seems, YT Revanced Magisk can't work anymore in its current state?

**Comment by j-hc** [comment]
why dont you update then?

**Comment by DLuciano88** [comment]
> why dont you update then?

There is no update.

**Comment by DLuciano88** [comment]
> I'm not sure if this is related to Revanced or any other thing. As of today Youtube Revanced stopps with a message "App isn't supported, please update" Temp solution is to disable "spoof version", but then the issue with loading screen after 30s re-appears.
> 
> In Reveanced Thread at reddit, there is a solution for non-rooted devicxes, you should update MicroG/GMSCore too.
> 
> As Magisk isn't relying on MicroG, it seems, YT Revanced Magisk can't work anymore in its current state?

I'm having the same issue. Have their latest version but I hope they put out a new update to get this resolved.

**Comment by j-hc** [comment]
> > why dont you update then?
> 
> There is no update.

https://github.com/j-hc/revanced-magisk-module/releases/tag/20220934

"YouTube: 19.09.37"

?

**Comment by DLuciano88** [comment]
> > > why dont you update then?
> > 
> > 
> > There is no update.
> 
> https://github.com/j-hc/revanced-magisk-module/releases/tag/20220934
> 
> "YouTube: 19.09.37"
> 
> ?

Thank you so much. I couldn't find that!

**Comment by shaft17** [comment]
> why dont you update then?

Ok my bad, Magisk showed me 19.02.39 as latest update (and does it now too)
I still had "Revanced extended" installed, got confused.
Thanks for the new release!

**Comment by shaft17** [comment]
@j-hc Maybe it is of interest, that the new Magisk version doesn't work anymore also.
Either spoofing app version or not, the playback stops after 50 seconds. In the Revanced threads it is said that you need to turn spoofing off (opposite to older Revanced versions), but the new Revanced relies on the new GMSCore MicroG, so Revanced Magisk in its current state is obsolete unfortunately

**Comment by jibukeshi** [comment]
YouTube ReVanced Extended 的最新版是 19.07.40 ，Magisk 模块还会更新吗？

The latest version of YouTube Revanked Extended is 19.07.40, Will the Magisk module be updated?
