### ISSUE TITLE
Needs reflash, app not installed 

### ISSUE THREAD

**Issue by salomaoa** [j-hc/revanced-magisk-module#423]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

YouTube revanced used to work ok on my phone. Its not working anymore. No matter how many times I reflash revanced module in magisk, my YouTube is still the playstore version.

Under magisk "modules" tab, I get the info that the module needs reflash because the app is not installed.

What is wrong here? I tried several ways: unninstalling YouTube, installing playstore YouTube and even installing the apk inside the revanced zip file.

None of my attempts solved the problem.

What am I doing wrong?

**Comment by ramanveerji** [comment]
Facing same thing. Also reported.

**Comment by j-hc** [comment]
383ba81
