### ISSUE TITLE
Youtube Playback stops after 50 seconds with newest Revanced Magisk 19.09.37

### ISSUE THREAD

**Issue by shaft17** [j-hc/revanced-magisk-module#425]
I'm sorry to bring attention to this again, but as the former bug report was closed, I have to re-new the report.
It doesn't matter what settings I choose: spoof app version vs don't spoof app version, the playback stops now after 50 seconds with Revanced Magisk.
I have a non rooted device also with GMSCore support, there it works, so I suppose as Google changed something recently, that Revanced Magisk can't run as root anymore without adding GMSCore, which defeats the purpose of Magisk/root anyway.

Or did I miss something in general? Does Revanced Magisk work for you without buffering/playback issue?

**Comment by WerctFourth** [comment]
I also have this issue. I had to temporarily switch to the non-root version with Revanced MicroG (this combination works for now)

**Comment by NBruderman** [comment]
You all missed the fact you need to switch to revanced gmscore
https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.3.240913

**Comment by WerctFourth** [comment]
> You all missed the fact you need to switch to revanced gmscore https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.3.240913

This Magisk module is supposed to run without a dedicated MicroG installation. That's its main feature.

**Comment by maxflutehd** [comment]
Still having the issue, both with GMSCore + rootless revanced and magisk revanced module. Stops playing,  and getting a revanced module fail when opening the video quality settings.

**Comment by ramanveerji** [comment]
> Still having the issue, both with GMSCore + rootless revanced and magisk revanced module. Stops playing,  and getting a revanced module fail when opening the video quality settings.

Blame your internet then.

**Comment by WerctFourth** [comment]
> Still having the issue, both with GMSCore + rootless revanced and magisk revanced module. Stops playing, and getting a revanced module fail when opening the video quality settings.

That's interesting. I ran some more tests, and even the unmodified Youtube app has this problem on two of my devices (and another works as intended). Both have MicroG installed as a replacement for Google Play Services. So maybe this issue is related to MicroG itself and Google's A/B server-side configuration changes. I can't confirm this for sure, as I don't have a device with GMS to compare now.
At the same time, I've seen reports on the web that don't seem to be related to MicroG at all ([example](https://www.reddit.com/r/youtube/comments/12jywsy/my_youtube_mobile_app_has_been_buffering_forever/)), so it may be difficult to pinpoint the problem.

**Comment by maxflutehd** [comment]
> > Still having the issue, both with GMSCore + rootless revanced and magisk revanced module. Stops playing,  and getting a revanced module fail when opening the video quality settings.
> 
> Blame your device and internet then.

I'm not, because on my Apple device with uYou+, there is no such problem. Internet speed is sufficient.

**Comment by shaft17** [comment]
> rootless revanced

I'm quite sure this does not belong to the topic of my bug report, as your problem doesn't have anything to do with Magisk, or do I misunderstand something?
In your case I'd go to [reddit revanced](https://www.reddit.com/r/revancedapp/) and ask there.

**Comment by shaft17** [comment]
> Still having the issue, both with GMSCore + rootless revanced and magisk revanced module. Stops playing, and getting a revanced module fail when opening the video quality settings.

I'm quite sure this does not belong to the topic of my bug report, as your problem doesn't have anything to do with Magisk, or do I misunderstand something?
In your case I'd go to [reddit revanced](https://www.reddit.com/r/revancedapp/) and ask there.

**Comment by WerctFourth** [comment]
Some new information (mainly for MicroG users):
I compared the settings in vanilla MicroG and Revanced MicroG and saw that Safetynet is enabled by default in Revanced MicroG. So I tried to enable it, installed the unmodified Youtube app, force-closed MicroG and the Youtube app, and playback worked as it should.
So the problem has something to do with the new Youtube app checking Safetynet after a playback starts.
I later reinstalled the Magisk module and it worked again. So the combination of Revanced Youtube (root) + system-wide MicroG (non-Revanced) works now.
But if you have this problem and have GMS installed, I can't recommend anything.

**Comment by knuxyl** [comment]
I have lineageos for microg and have been having this problem since this latest update although i might have been on a much older version.
I tried Device registration and Safetynet but it did not fix the issue. Cant say for sure its related to those or not because I fail device attestation.

**Comment by ydarwish** [comment]
What worked for me is downloading revanced manager from revanced.app. apply default patches. Patching process through errors and said it failed but playback now works

**Comment by DestinyofYeet** [comment]
Cannot confirm. I downloaded Revanced Manager version 1.20.1 from revanced.app, patched the recommended YouTube version of 19.09.37, but playback still stops after 30 seconds.

**Comment by j-hc** [comment]
this is either a user issue or a revanced bug. you dont need to report here.

**Comment by Priyansh1024** [comment]
![ss](https://github.com/j-hc/revanced-magisk-module/assets/138903333/4a8c028a-89b6-4cff-abd8-5232f46268cd)
try this setting idk for which it work but i fixed playback issue in both micro and magisk

**Comment by REmerald** [comment]
> you dont need to report here.

Unfortunately, I do. I tried to reporting it with logs and everything at revanced discussions (couldn't report it in the dedicated discussion since it was locked due to different issue), but [the maintainer refused to even look at it and redirected here](https://github.com/ReVanced/revanced-discussions/discussions/1042#discussioncomment-9447419).

@j-hc Is there anything you can do about the issue, even though it may be "their bug"? Maybe look at the logs in the discussion or contact/collaborate with someone willing to look at it? Otherwise this issue will never get fixed.

**Comment by HybridShinobi** [comment]
> > you dont need to report here.
> 
> Unfortunately, I do. I tried reporting it with logs and everything at revanced discussions (couldn't report it in the dedicated discussion since it was locked due to different issue), but [the maintainer refused to even look at it and redirected here](https://github.com/ReVanced/revanced-discussions/discussions/1042#discussioncomment-9447419).
> 
> @j-hc Is there anything you can do about the issue, even though it may be "their bug"? Maybe look at the logs in the discussion or contact/collaborate with someone willing to look at it? Otherwise this issue will never get fixed. I don't know who else to ask.

I'm using a non rooted Samsung device, I installed the latest version of both the revanced YouTube and gmscore with all the patches but Even it has the same playback issue, video stops playing after 10 to 15 seconds
