### ISSUE TITLE
Is there a plan to support Apatch?

### ISSUE THREAD

**Issue by alliwang** [j-hc/revanced-magisk-module#427]
This module has been very helpful. It supports Magisk and KSU. 
I currently switched to Apatch. The module can be installed normally, but it does not take effect. 
May I ask if there is a plan to support Apatch in the future? Thank you

**Comment by j-hc** [comment]
explaon in more details. what does it mean "not take effect"? did you try flashing without rebooting? and i need the flash logs

**Comment by j-hc** [comment]
explain in more details. what does it mean to "not take effect"? did you try flashing without rebooting? and i need the flash logs

**Comment by CDzungx** [comment]
> explain in more details. what does it mean to "not take effect"? did you try flashing without rebooting? and i need the flash logs

Revanced doesnt seem to come along, it only install original youtube

**Comment by j-hc** [comment]
> Revanced doesnt seem to come along, it only install original youtube

> did you try flashing without rebooting? and i need the flash logs

**Comment by CDzungx** [comment]
> > Revanced doesnt seem to come along, it only install original youtube
> 
> > did you try flashing without rebooting? and i need the flash logs

Log look normal, no reboot and reboot both still no revanced, only original yt
![Screenshot_2024-05-20-10-43-34-718_me bmax apatch-edit](https://github.com/j-hc/revanced-magisk-module/assets/59353870/5a5e2bde-6131-4a18-97ff-6e6595c0dfa3)
