### ISSUE TITLE
Downloading prebuilt from private repos with token fails

### ISSUE THREAD

**Issue by trmdi** [j-hc/revanced-magisk-module#429]
Fetching the latest release info succeeded but downloading prebuilt fails.

```bash
[+] Getting prebuilts (ReVanced)
2024-04-09 10:46:42 URL:https://api.github.com/repos/trmdi/revanced-cli-extended/releases/latest [3936/3936] -> "-" [1]
2024-04-09 10:46:42 URL:https://api.github.com/repos/ReVanced/revanced-integrations/releases/latest [6137/6137] -> "-" [1]
2024-04-09 10:46:43 URL:https://api.github.com/repos/ReVanced/revanced-patches/releases/latest [8[19](https://github.com/trmdi/revanced-magisk-module/actions/runs/8614423219/job/23607822457#step:6:20)5/8195] -> "-" [1]
[+] Getting 'temp/trmdi-rv/revanced-cli-4.6.0-all.jar' from 'https://github.com/trmdi/revanced-cli-extended/releases/download/v4.6.0/revanced-cli-4.6.0-all.jar'
https://github.com/trmdi/revanced-cli-extended/releases/download/v4.6.0/revanced-cli-4.6.0-all.jar:
[20](https://github.com/trmdi/revanced-magisk-module/actions/runs/8614423219/job/23607822457#step:6:21)24-04-09 10:46:43 ERROR 404: Not Found.
[-] ABORT: could not download rv prebuilts
```
It seems to use `browser_download_url` instead of GitHub's API.

**Comment by j-hc** [comment]
should work now cbba95a290c7040ee62bfa1ea5721fc5797dc7d6

**Comment by trmdi** [comment]
Works perfectly. Thank you so much for the quick fix!
By the way, I have a question about `j-hc/revanced-cli`. Since I can't open a new Issue there, I'm asking here.
Currently, it seems you patch it to add "ripLibs and unsigned" locally before releasing it. What's your plan for this? Will you upstream this patch, or will you still patch it yourself but use GitHub Actions?

**Comment by j-hc** [comment]
> Works perfectly. Thank you so much for the quick fix!
> 
> By the way, I have a question about `j-hc/revanced-cli`. Since I can't open a new Issue there, I'm asking here.
> 
> Currently, it seems you patch it to add "ripLibs and unsigned" locally before releasing it. What's your plan for this? Will you upstream this patch, or will you still patch it yourself but use GitHub Actions?

its just easier to do it locally instead of fixing the merge conflicts everytime. i might get back to doing it with ci, not sure.

**Comment by trmdi** [comment]
> its just easier to do it locally instead of fixing the merge conflicts everytime. i might get back to doing it with ci, not sure.

I've come up with a method to make it as low-maintenance as possible. Would you be interested in seeing it?
https://github.com/trmdi/revanced-cli-extended/

**Comment by j-hc** [comment]
> > its just easier to do it locally instead of fixing the merge conflicts everytime. i might get back to doing it with ci, not sure.
> 
> I've come up with a method to make it as low-maintenance as possible. Would you be interested in seeing it?
> https://github.com/trmdi/revanced-cli-extended/

can you make it public

**Comment by trmdi** [comment]
> > > its just easier to do it locally instead of fixing the merge conflicts everytime. i might get back to doing it with ci, not sure.
> > 
> > 
> > I've come up with a method to make it as low-maintenance as possible. Would you be interested in seeing it?
> > https://github.com/trmdi/revanced-cli-extended/
> 
> can you make it public

Done.

**Comment by j-hc** [comment]
> > > > its just easier to do it locally instead of fixing the merge conflicts everytime. i might get back to doing it with ci, not sure.
> > > 
> > > 
> > > I've come up with a method to make it as low-maintenance as possible. Would you be interested in seeing it?
> > > https://github.com/trmdi/revanced-cli-extended/
> > 
> > 
> > can you make it public
> 
> Done.

looks like less prone to merge conflicts but duplicates the zipping of apk. i make the changes in revanced-library. will update my cli repo some time soon..
