### ISSUE TITLE
Revanced for facebook, spotify ?

### ISSUE THREAD

**Issue by nakheel77** [j-hc/revanced-magisk-module#430]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**
Can you make revanced for facebook, spotify. I find those apps but nothing. Many thank for your work!

**Comment by MIOGMIOG** [comment]
I think you are confused,
author of this project isn't the author of ReVanced (here is github org. of ReVanced - https://github.com/revanced), he just made github repo that builds it into apk files and magisk modules.
For spotify you can use this - https://github.com/Team-xManager/xManager
And for Facebook just use the web version on Firefox for Android browser with uBlock Origin extension (https://addons.mozilla.org/en-US/android/addon/ublock-origin/) to block ads.

**Comment by nakheel77** [comment]
> I think you are confused, author of this project isn't the author of ReVanced (here is github org. of ReVanced - https://github.com/revanced), he just made github repo that builds it into apk files and magisk modules. For spotify you can use this - https://github.com/Team-xManager/xManager And for Facebook just use the web version on Firefox for Android browser with uBlock Origin extension (https://addons.mozilla.org/en-US/android/addon/ublock-origin/) to block ads.

Thanks  for  your reply ! 

But i see that, why on iOs there are many app like facebook, messenger, ... they mod app very good ! But on android they did not mod app like iOs ?
