### ISSUE TITLE
Remove "Skipped Patches"

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#435]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**This is not a bug**

How remove "skipped patches" ?
When ReVanced has an New Release but Anddea doesn't, the module will only build ReVanced while skipping Anddea. I'd like to disable it, but I don't know how to proceed (if the builder allows it).
(I don't code, and I don't understand it)

**Comment by j-hc** [comment]
you can remove this step:
https://github.com/j-hc/revanced-magisk-module/blob/a0c9538c9463860769980020ea54fa34bc05d7be/.github/workflows/build.yml#L28
