### ISSUE TITLE
rvmm-config-gen does not define option variants for patches other than ReVanced

### ISSUE THREAD

**Issue by IgorTHh1337** [j-hc/revanced-magisk-module#437]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

When I try to configure patches other than ReVanced (anddea for example), the site won't let me select the patches that are in that patch set. This also prevents me from selecting the right settings when generating the config. Even if you just enter the version of the patches, it obviously tries to fetch patches from the ReVanced API.

![image](https://github.com/j-hc/revanced-magisk-module/assets/134911638/e578c0b1-a6f7-4232-83a9-790249bda876)

**Comment by j-hc** [comment]
right top corner has an option to upload custom patches.json

there is no other possible way to select 3rd party patch bundles.
