### ISSUE TITLE
Some patches fail

### ISSUE THREAD

**Issue by Lassie111** [j-hc/revanced-magisk-module#438]
https://github.com/Lassie111/revanced-magisk-module/actions/runs/9016399136/job/24772918587#step:6:119

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED BUGS IN THIS REPO Describe the bug of the rvmm builder or the modules

**Comment by Lassie111** [comment]
Patching just with revanced-cli-4.6.0 locally worked without errors, that's why I was not sure whether it is a Revanced bug or not.

**Comment by j-hc** [comment]
it fails with the stock revanced cli too

**Comment by Lassie111** [comment]
> it fails with the stock revanced cli too

Ah, that's true, it was my fault.
I tested locally with youtube, instead of youtube music, but it's the music that fails. I got confused by the mixed github actions log which prints the log for both apps simultaneously (maybe because it's running them in parallel).
