### ISSUE TITLE
19.16.39 - Daily build missing 

### ISSUE THREAD

**Issue by erdnuesse** [j-hc/revanced-magisk-module#441]
The description says, there should be new builds on changes, however on May 9th the website says there's a new release of the APK, but no magisk build 19.16.39 release as it seems. 

Idk if there's something broken or if manual intervention is necessary. 

Disregard if I missed something obvious though.

**Comment by j-hc** [comment]
its not missing

**Comment by erdnuesse** [comment]
Thanks for the reply, extended is 19.16.39, while YouTube is 19.11.43, so it's as planned they are not the same version number? just for clarity.
