### ISSUE TITLE
Instagram Download error

### ISSUE THREAD

**Issue by bookworm-coding** [j-hc/revanced-magisk-module#442]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

I want to use revanced Instagram so I used this repo as a template and added Instagram.
But, there was a problem while downloading because there are multiple versions at [apkmirror](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-331-0-0-37-90-release/)
For example, there are two Instagram that is for architecture arm64-v8a and screen nodpi but one is Android 9.0+ and other is Android 7.0+. I think there should be a way to select which APK to download. 

ERROR 429: Too Many Requests.
[-] ERROR: Could not download 'Instagram (arm-v7a)' from apkmirror with version '331.0.0.37.90', arch 'arm-v7a', dpi 'nodpi'

ERROR 429: Too Many Requests.
[-] ERROR: Could not download 'Instagram (arm64-v8a)' from apkmirror with version '331.0.0.37.90', arch 'arm64-v8a', dpi 'nodpi'

**Comment by j-hc** [comment]
> ERROR 429: Too Many Requests.

apkmirror rate limited you. use my archive from the config for downloading apks.
