### ISSUE TITLE
Not working with Vivo Phones.

### ISSUE THREAD

**Issue by atulmits** [j-hc/revanced-magisk-module#444]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**
Revanced Youtube is Not working with Vivo Phones. I tried on multiple phones. Video just do not moves. Like infinity buffering. Could you please solve this issue ? As well YT Music is crashing on Vivo phones.

**Comment by j-hc** [comment]
> DO NOT REPORT REVANCED STUFF IN THIS REPO
