### ISSUE TITLE
Reddit building failed.

### ISSUE THREAD

**Issue by belinux** [j-hc/revanced-magisk-module#445]
I tried locally and also checked the CI run, there is a problem on building the reddit package. You can check the [log on the CI](https://github.com/j-hc/revanced-magisk-module/actions/runs/9174717249/job/25226157354#step:6:1041) run from the 20220941 release.

**Comment by j-hc** [comment]
revanced thing. try with older versions of reddit.

**Comment by belinux** [comment]
Thank you for the quick response! You are right, I had to go to version "2024.17.0" in order to build it correctly.
