### ISSUE TITLE
Problem with "htmlq-x86_64" file

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#447]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**

**Describe the bug of the rvmm builder or the modules**

Hello, I seem to have a problem with the file "htmlq-x86_64" which ends with "Broken pipe" (see CI action on https://github.com/Kevinr99089/ReVanced.Builder.old/actions ).
I've tried everything (even synchronizing the files), other repositories have exactly the same files (see https://github.com/Kevinr99089/ReVanced.Builder/actions )
This repo is giving me trouble on this and I don't know how to fix it.

**Comment by nakheel77** [comment]
Sorry, this is not answer for your question! 

But, can you show me the difference between 2 version : youtube-revanced-magisk-v19.11.43-all.zip & 
youtube-revanced-extended-magisk-v19.16.39-all.zip 

What version is better for root device ? 

Many thanks  !

**Comment by kevinr990** [comment]
> But, can you show me the difference between 2 version : youtube-revanced-magisk-v19.11.43-all.zip & youtube-revanced-extended-magisk-v19.16.39-all.zip
> 
> What version is better for root device ?

As my device is not rooted, I can't test them, sorry.

**Comment by j-hc** [comment]
the error is this "utils.sh: line 231: bin/htmlq/htmlq-x86_64: Permission denied"
not the "broken pipe"

htmlq has proper permissions in this repo so its something you changed.

**Comment by kevinr990** [comment]
I've done nothing more than merge your commits, I haven't touched the code.

How do I change the permissions?

**Comment by j-hc** [comment]
just start clean with the template again
