### ISSUE TITLE
The latest doesn't work

### ISSUE THREAD

**Issue by jusendq** [j-hc/revanced-magisk-module#452]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

The latest magisk module version  19.11.43 doesn't work on my device. Youtube app still show ads as the original one and there is no revanced settings. I tried to remove and reinstall with version 19.09.37 and it still works.

**Comment by j-hc** [comment]
modules work fine. its the the other modules you use that are the problem.

**Comment by jusendq** [comment]
> modules work fine. its the the other modules you use that are the problem.

I disabled all other modules but it did not help.😣
