### ISSUE TITLE
Cannot find the option to adjust playback speed.

### ISSUE THREAD

**Issue by superandylin** [j-hc/revanced-magisk-module#453]
The recent two updates do not have the option to adjust playback speed. 
Please update as soon as possible. Thank you.

**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

**Comment by j-hc** [comment]
> if you delete these lines and proceed to report revanced stuff like patch bugs or patch requests, you will be blocked from this repo
