### ISSUE TITLE
Improve the Release page

### ISSUE THREAD

**Issue by trmdi** [j-hc/revanced-magisk-module#458]
Currently Releases are tagged with a dynamic name (202209xx), this results output APKs are separated for each run.
For example, in https://github.com/j-hc/revanced-magisk-module/releases/tag/20220945 (also the [Latest Release link](https://github.com/j-hc/revanced-magisk-module/releases/latest)), there is only YouTube Revanced Extended.
It becomes challenging to find other APKs such as YouTube, Tiktok that were built in previous runs...
I know I can search in https://github.com/j-hc/revanced-magisk-module/releases, but it's not interesting since you could have to go through multiple pages.

If you use a static tag such as "latest", all built files will be consolidated into a single location: https://github.com/j-hc/revanced-magisk-module/releases/tag/latest
That makes it easier for users to find and download APKs.

**Comment by j-hc** [comment]
if some patch source is not updated and its building is skipped then it doesnt make sense to keep its previous builds in the same release with the updated patch source. 
other options are building it nevertheless or uploading from the previous releases, both of which are unnecessary waste of resource for the sake of convenience

**Comment by trmdi** [comment]
> if some patch source is not updated and its building is skipped then it doesnt make sense to keep its previous builds in the same release with the updated patch source.

Why should users care about which version of patch APKs were built with? I think all users just want to get the latest APKs (no matter if it was built with the latest patches or not)

**Comment by j-hc** [comment]
i dont understand you, apks are already always built with latest version of patches. anyways, i already explained why i wont do that just for convenience
