### ISSUE TITLE
Triggers Anti-Root

### ISSUE THREAD

**Issue by Curve** [j-hc/revanced-magisk-module#46]
This magisk module trips the anti-root mechanisms of some banking apps ~~, I believe this is due to mindetach, is it possible to not use mindetach **without using the microg version**?~~ (see comments)

**Comment by mingaldrichgan** [comment]
Have you tried disabling/uninstalling the Mindetach module? It isn't required to run Revanced?

**Comment by Curve** [comment]
> Have you tried disabling/uninstalling the Mindetach module? It isn't required to run Revanced?

There is no additional module for mindetach, it's included in the ReVanced Magisk Module

**Comment by mingaldrichgan** [comment]
Hmmm I'm confused, as it's a separate .zip file that I flashed (but you don't have to)...

**Comment by Curve** [comment]
> Hmmm I'm confused, as it's a separate .zip file that I flashed (but you don't have to)...

Hm - It's all in one module for me - Would you mind posting your build conf?

**Comment by mingaldrichgan** [comment]
I'm using the [prebuilt ones](https://github.com/j-hc/revanced-magisk-module/releases). Sorry I misunderstood your query.

**Comment by Curve** [comment]
> I'm using the [prebuilt ones](https://github.com/j-hc/revanced-magisk-module/releases). Sorry I misunderstood your query.

Ah, don't mind me then I thought it used mindetach the whole time for whatever reason but that's not true.

Still, something in this magisk module causes my banking app to detect root - Which is strange, I doubt it's detecting that the APK was patched somehow, at first I thought that it may be the icon patch of revanced but I disabled that and it still detects root but only if the revanced modules are loaded

**Comment by j-hc** [comment]
which banking app is that?

**Comment by Curve** [comment]
> which banking app is that?

The PushTan App by Sparkasse


Another interesting observation:

ReVanced Modules **not loaded**: 
![Screenshot_20220910-103605.png](https://user-images.githubusercontent.com/37805707/189461780-2de78a0e-22ac-44c2-a8f8-18e9467495d2.png)
=> Banking app works


Revanced Modules **loaded**:
![Screenshot_20220910-103712.png](https://user-images.githubusercontent.com/37805707/189461792-dabe3fb5-a3a9-42c1-af3e-58c43673c4c3.png)
=> Banking app does not work

Other modules that I have always loaded are:
Universal Safetynet Fix 
Shamiko

Modules that once enabled cause magisk to be detected: 

YouTube ReVanced 
YouTube Music ReVanced

**Comment by j-hc** [comment]
@Curve can you test this and let me know? it should get rid of the "Found Magisk" in momo but im not sure about the banking app.

https://drive.google.com/file/d/1XzBJMEHxuZj865dU68B1SSFVMQHqfMg5/view?usp=sharing

**Comment by j-hc** [comment]
> > @Curve can you test this and let me know? it should get rid of the "Found Magisk" in momo but im not sure about the banking app.
> > https://drive.google.com/file/d/1XzBJMEHxuZj865dU68B1SSFVMQHqfMg5/view?usp=sharing
> 
> Works! Magisk is no longer detected and the banking app works perfectly :)
> 
> What was the issue? Can this be mainlined so that I can adjust the patches?

the issue was the mount point (maybe selinux context related?), now i hardlink the patched apk in another directory and bind mount from there. thats all.

**Comment by Curve** [comment]
> > > @Curve can you test this and let me know? it should get rid of the "Found Magisk" in momo but im not sure about the banking app.
> > > https://drive.google.com/file/d/1XzBJMEHxuZj865dU68B1SSFVMQHqfMg5/view?usp=sharing
> > 
> > Works! Magisk is no longer detected and the banking app works perfectly :)
> > 
> > What was the issue? Can this be mainlined so that I can adjust the patches?
> 
> the issue was the mount point (maybe selinux context related?), now i hardlink the patched apk in another directory and bind mount from there. thats all.
> 
> and im closing the issue, will merge the changes.

Thanks for the quick reply & fix!
