### ISSUE TITLE
How to disable YouTube update from Play Store?

### ISSUE THREAD

**Issue by ShamsSayied** [j-hc/revanced-magisk-module#465]
Hi i like revanced YouTube very much. I am using magisk module but the problem is that whenever Play Store update apps then revanced YouTube automatically replaced by original YouTube. As my phone is rooted so I think it is easy for developer to disable this YouTube update via magisk module. 
![Screenshot_2024-06-23-09-11-36-461_com android vending](https://github.com/j-hc/revanced-magisk-module/assets/37446192/1818f525-e0c6-4216-ad6d-b609149435d3)

**Comment by gyrorayo** [comment]
https://github.com/j-hc/zygisk-detach
