### ISSUE TITLE
Updating issue magisk

### ISSUE THREAD

**Issue by 4B3L41D** [j-hc/revanced-magisk-module#47]
![Screenshot_20220914-193351_Gestionnaire de modules Magisk de Fox](https://user-images.githubusercontent.com/113546434/190223861-b21ee445-7ddb-4837-8bc1-b0f5821e6384.png)

**Comment by 4B3L41D** [comment]
I did not have this issue before only from last update

**Comment by mingaldrichgan** [comment]
+1 me too.

**Comment by j-hc** [comment]
i cant see the full error

**Comment by j-hc** [comment]
are you using official magisk manager?

**Comment by j-hc** [comment]
im closing the issue. use magisk app.

**Comment by mingaldrichgan** [comment]
Confirmed that this works on official Magisk Manager but fails on Fox Magisk Module Manager.

**Comment by 4B3L41D** [comment]
Yes it's working within Magisk app but fails with Fox module manager.
