### ISSUE TITLE
Can't use patch with option

### ISSUE THREAD

**Issue by Fearmipan** [j-hc/revanced-magisk-module#470]
Can't use patch with option in *toml.
Example json:
        
[
  {
    "patchName": "Custom branding name for YouTube",
    "options": [
      {
        "key": "AppName",
        "value": "YouTube Extended"
      }
    ]
  }
]
       

I can put 'Custom branding name for YouTube' in *toml, but how can I input the specific AppName?
Can you please add support for option.json instead of config.toml?
Or just add option in config.toml to use option.json? (from URL/specific json folder in repo)

**Comment by j-hc** [comment]
> but how can I input the specific AppName?

you just did:
```
"key": "AppName",
"value": "YouTube Extended"
```

**Comment by Fearmipan** [comment]
Not working.
Did I miss something?

My config.toml:
[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Custom Shorts action buttons' 'Custom branding name for YouTube'"
"key": "AppName",
"value": "YouTube"
"key": "IconType",
"value": "YouTube"

**Comment by j-hc** [comment]
use options.json file
