### ISSUE TITLE
YouTube is not revanced but original. 19.16.39

### ISSUE THREAD

**Issue by Genxster1998** [j-hc/revanced-magisk-module#471]
I installed latest magisk release on KernelSu+ZygiskNext device. The app installed is vanilla without any patches. I tried reinstalling ,deleting , remove linking from store . Nothing worked. Everytime I install. It's vanilla YouTube with ads.Is there some hidden way to activate patches ?
Device: Samsung Galaxy S20 FE r8q
Android Version: 13, One UI 5.1

Regards

**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

**Comment by j-hc** [comment]
it works. the problem is with your setup.
