### ISSUE TITLE
Overheating when using YT Revanced

### ISSUE THREAD

**Issue by SeanCoLtd** [j-hc/revanced-magisk-module#473]
Since the latest versions, my S22 Ultra (SM-S908U1) overheats too much when watching 1080p videos (which should not be the reason why the phone overheats), I have searched for updates with the intention of seeing if this problem is solved, I have version 19.16.39 and on the official revanced.to page it says that there is version 19.25, but when I downloaded the APK it download the 19.16, and on Telegram there was no notice of version 19.25.

**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

**Comment by j-hc** [comment]
there is no official revanced page called revanced.to
you are using malware

**Comment by SeanCoLtd** [comment]
Well, and which page is the official one among all?
