### ISSUE TITLE
Question on fallback url's

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#474]
In the commit e7ae080 I noticed you added fallback URLs to some of the apps, my question is, when say archive is unavailable for whatever reason, is the script supposed to try the next URL in line? If so a couple times it has occurred to me where it gets hung up on Archive for whatever the reason may be, either the version not existing yet or just unable to download at the time and it just stops and fails instead of trying the next URL. I was just looking for clarification on it, and maybe I'm seeing it wrong and if its not like this already it would be nice to add in if not to difficult, Thank you and I greatly appreciate you for all your efforts!

**Comment by j-hc** [comment]
yes it tries the next one in this order: archive - apkmirror- uptodown. like here:
https://github.com/j-hc/revanced-magisk-module/actions/runs/9994894346/job/27625785149#step:6:33

**Comment by E85Addict** [comment]
> yes it tries the next one in this order: archive - apkmirror- uptodown. like here: https://github.com/j-hc/revanced-magisk-module/actions/runs/9994894346/job/27625785149#step:6:33

Interesting okay, that's exactly what I thought it would/should do, I just didn't get the same behavior when I gave a try but it must've been something on my end, appreciate the response!
