### ISSUE TITLE
Issue flashing module when using the latest Magisk Canary 27005 release

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#478]
[magisk_install_log_2024-07-23T20.37.05.log](https://github.com/user-attachments/files/16356725/magisk_install_log_2024-07-23T20.37.05.log)

Here is the install log, I installed the module perfectly fine in 27003 and upgraded to 27005 with the module installed and it worked perfectly fine, but when trying to update or install another module this error occurs.

I have a feeling it has something to do with this [d33b077](https://github.com/topjohnwu/Magisk/commit/d33b077a13b34691a7f1fd3643336e09383ced78)

**Comment by E85Addict** [comment]
I added 

> NVBASE=/data/adb

to customize.sh, service.sh and uninstall.sh and it solved the issue when installing.

**Comment by nathannxx** [comment]
Like this?
![Screenshot_20240724-124713729](https://github.com/user-attachments/assets/d4a57d7b-dfe3-43fe-9447-4882394ae9d7)

**Comment by nathannxx** [comment]
> I added
> 
> > NVBASE=/data/adb
> 
> to customize.sh, service.sh and uninstall.sh and it solved the issue when installing.

Like this ?
![Screenshot_20240724-124713729](https://github.com/user-attachments/assets/74c7c908-697f-47a1-8d34-c5bbc726437e)

**Comment by E85Addict** [comment]
> > I added
> > > NVBASE=/data/adb
> > 
> > 
> > to customize.sh, service.sh and uninstall.sh and it solved the issue when installing.
> 
> Like this ?
> 
> ![Screenshot_20240724-124713729](https://private-user-images.githubusercontent.com/84331192/351588757-74c7c908-697f-47a1-8d34-c5bbc726437e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDA4NzgsIm5iZiI6MTcyMTgwMDU3OCwicGF0aCI6Ii84NDMzMTE5Mi8zNTE1ODg3NTctNzRjN2M5MDgtNjk3Zi00N2ExLThkMzQtYzViYmM3MjY0MzdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA1NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzRhY2ZlMzFhYWU4OGM0ODIxYjEzYjQxNDg3MDBlYWRkYTFiNjFmZjVmM2RlNGVjYmZiODNhNTI2MjFkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVS0L1xMShiY2HpLNBWV__lhC7hZ6gBYGk1OR15oaZ4)

No, I added the line NVBASE=/data/adb to the top of each file.

![image](https://github.com/user-attachments/assets/8f756178-34c5-4e99-bd0a-fcc2ebeb15dd)

**Comment by nathannxx** [comment]
> > > I added
> > > > NVBASE=/data/adb
> > > 
> > > 
> > > to customize.sh, service.sh and uninstall.sh and it solved the issue when installing.
> > 
> > Like this ?
> > 
> > ![Screenshot_20240724-124713729](https://private-user-images.githubusercontent.com/84331192/351588757-74c7c908-697f-47a1-8d34-c5bbc726437e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDA4NzgsIm5iZiI6MTcyMTgwMDU3OCwicGF0aCI6Ii84NDMzMTE5Mi8zNTE1ODg3NTctNzRjN2M5MDgtNjk3Zi00N2ExLThkMzQtYzViYmM3MjY0MzdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA1NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzRhY2ZlMzFhYWU4OGM0ODIxYjEzYjQxNDg3MDBlYWRkYTFiNjFmZjVmM2RlNGVjYmZiODNhNTI2MjFkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVS0L1xMShiY2HpLNBWV__lhC7hZ6gBYGk1OR15oaZ4)
> 
> No, I added the line NVBASE=/data/adb to the top of each file.
> 
> ![image](https://github.com/user-attachments/assets/8f756178-34c5-4e99-bd0a-fcc2ebeb15dd)
> 

Thanks a lot!
it installed successfully on latest magisk canary build

**Comment by j-hc** [comment]
> I added
> 
> > NVBASE=/data/adb
> 
> to customize.sh, service.sh and uninstall.sh and it solved the issue when installing.

NVBASE env variable not existing is a bug of the canary build. magisk documents says it should exist so it should be a fix from magisk's side

**Comment by j-hc** [comment]
nvm

https://github.com/topjohnwu/Magisk/pull/8224

looks like next magisk versions will remove it completely.

**Comment by E85Addict** [comment]
If you look at the commit I linked in my first post, they seemed to have removed it indefinitely, because it's redundant.

**Comment by j-hc** [comment]
right.. i will probably wait for it to make into the release. until then this issue may be kept open.

**Comment by NBruderman** [comment]
Canary 27006 is out, and it seems like this change is not going anywhere. Anyway, it's intentional

**Comment by j-hc** [comment]
ecd919d
