### ISSUE TITLE
Check for updates on YT Music, TikTok, Reddit, Twitter, etc

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#48]
The workflow only checks for updates on the YouTube app, it would be good if it checked for all apps that has ```BUILD_NAME=true``` in the ```build.conf```

**Comment by Othmane-ElAlami** [comment]
I think it would be cool to have a ZIP file that includes all the apps.

**Comment by j-hc** [comment]
it would be excessive to constantly rebuilding same version of apps because only one of them had its version bumped. i could add options for it but i guess that would bloat the config file so for now youtube and revanced-patches version will be the priority until i can think of a better way.

**Comment by MatadorProBr** [comment]
> it would be excessive to constantly rebuilding same version of apps because only one of them had its version bumped. i could add options for it but i guess that would bloat the config file so for now youtube and revanced-patches version will be the priority until i can think of a better way.

Maybe make it only builds the one that gets the version bumped, update the latest release name, tag and replace the old apk with the new one?

**Comment by j-hc** [comment]
> Maybe make it only builds the one that gets the version bumped, update the latest release name, tag and replace the old apk with the new one?

as of now there isnt a way to edit the tag and that would break the point of versioning.

**Comment by TheRealGramdalf** [comment]
I think the best way would be to have a custom f-droid repository.  You can find an example that's hosted on gihub here: https://github.com/iodeOS/fdroid

Should be relatively simple to set up

**Comment by miguelglopes** [comment]
Can't you create separate repos for each app?

**Comment by MatadorProBr** [comment]
> Can't you create separate repos for each app?

I don't think that is a ideal solution, also the repo can't just create repos without user interaction or a token
