### ISSUE TITLE
Needs reflash: 'apk not found'

### ISSUE THREAD

**Issue by ishuya** [j-hc/revanced-magisk-module#480]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

![Screenshot Manager](https://github.com/user-attachments/assets/97bfb6b9-6604-41c1-9500-e501e3d950ae)

After updating to Android 14 qpr3 update, getting this error. Tried re-flashing module multiple times.

[magisk_install_log_2024-07-27T20.04.05.log](https://github.com/user-attachments/files/16400671/magisk_install_log_2024-07-27T20.04.05.log)

**Comment by Nitorac** [comment]
Probably the same issue as: https://github.com/j-hc/revanced-magisk-module/issues/478

**Comment by nathannxx** [comment]
What magisk do you install? Latest Canary Build ?

**Comment by j-hc** [comment]
fixed for the next release
