### ISSUE TITLE
Needs reflash. Zygote crashed

### ISSUE THREAD

**Issue by cicciocanestro** [j-hc/revanced-magisk-module#484]
Oneplus 10t with android 14 July patch rooted with magisk alpha.
I've this error like picture with YouTube revancrd  and revacend  extended 
![Screenshot_2024-08-10-17-31-37-00_45b1a0a25ddcf978280e8330ce033de6](https://github.com/user-attachments/assets/d0c24d62-d73d-467e-b721-b9d3faa8cf21)

**Comment by j-hc** [comment]
fix your rom

**Comment by cicciocanestro** [comment]
My Is originale Rom. Only root with magisk alpha

**Comment by tuftsanti** [comment]
Why was this closed? The issue doesn't appear solved and I have the same.

**Comment by ramanveerji** [comment]
> Why was this closed? The issue doesn't appear solved and I have the same.

Reflashing of module is the solution.

**Comment by tuftsanti** [comment]
> > Why was this closed? The issue doesn't appear solved and I have the same.
> 
> Reflashing of module is the solution.

Not for me, I did that and it led to the also unresolved INSTALL_FAILED_VERSION_DOWNGRADE issue

**Comment by ramanveerji** [comment]
> > > Why was this closed? The issue doesn't appear solved and I have the same.
> > 
> > Reflashing of module is the solution.
> 
> Not for me, I did that and it led to the also unresolved INSTALL_FAILED_VERSION_DOWNGRADE issue

After getting a zygote error, uninstall the youtube app or music from your device manually, then flash the module and reboot.

**Comment by tuftsanti** [comment]
> After getting a zygote error, uninstall the youtube app or music from your device manually, then flash the module and reboot.

It uninstalls just fine, it then won't install the downgraded version, giving the error. This is all in the open issue: 
https://github.com/j-hc/revanced-magisk-module/issues/489

**Comment by ramanveerji** [comment]
> > After getting a zygote error, uninstall the youtube app or music from your device manually, then flash the module and reboot.
> 
> It uninstalls just fine, it then won't install the downgraded version, giving the error. This is all in the open issue: 
> https://github.com/j-hc/revanced-magisk-module/issues/489

When you have uninstalled already that means there is no youtube or music in your device. After flashing you should not get any downgrade error.

**Comment by tuftsanti** [comment]
> > It uninstalls just fine, it then won't install the downgraded version, giving the error. This is all in the open issue:
> > #489
> 
> When you have uninstalled already that means there is no youtube or music in your device. After flashing you should not get any downgrade error.

It's a system app, do I need to uninstall the updates or the app entirely?

**Comment by ramanveerji** [comment]
> > > It uninstalls just fine, it then won't install the downgraded version, giving the error. This is all in the open issue:
> > > #489
> > 
> > When you have uninstalled already that means there is no youtube or music in your device. After flashing you should not get any downgrade error.
> 
> It's a system app, do I need to uninstall the updates or the app entirely? 

If you are having a root device why don't you uninstall that system app first.

**Comment by tuftsanti** [comment]
> If you are having a root device why don't you uninstall that system app first.

That appears to have done it, thank you

**Comment by ramanveerji** [comment]
> > If you are having a root device why don't you uninstall that system app first.
> 
> That appears to have done it, thank you

Thank god you did it.
