### ISSUE TITLE
Anyway to make a module with original brand/icon? 

### ISSUE THREAD

**Issue by peter9811** [j-hc/revanced-magisk-module#485]
I tried the manager, but after 3 uses, the app stopped working... So, I ended using the module, but the name is no YouTube is "RVX" and the icon is different

I know that on the manager is possible change it, but when I mount the apk, don't work. Close the app, show "account not found", crash, etc.

Can be possible a extra version with the original branding? Thanks

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module?tab=readme-ov-file#to-includeexclude-patches-or-patch-other-apps

**Comment by peter9811** [comment]
> https://github.com/j-hc/revanced-magisk-module?tab=readme-ov-file#to-includeexclude-patches-or-patch-other-apps

Love u, bro
Sorry. No very experienced on github, I never seen a repo like "template"

I'll do. Thanks
