### ISSUE TITLE
Youtube disappears

### ISSUE THREAD

**Issue by Louis-htmlcss** [j-hc/revanced-magisk-module#486]
when I installed the module, it was perfect. But then my phone rebooted without doing anything and youtube disappeared. The only way for it to work is to reinstall the module.

**Comment by j-hc** [comment]
you should fix your phone so it doesnt randomly reboot

**Comment by Louis-htmlcss** [comment]
I installed it on 4 different phones, it worked for a few days, then the phone rebooted and uninstalled youtube.

**Comment by Louis-htmlcss** [comment]
without the module my phone won't restart by itself
