### ISSUE TITLE
libzygisk.so failed with 2: No such file or directory

### ISSUE THREAD

**Issue by remco1271** [j-hc/revanced-magisk-module#488]
Since the latest release [20220959](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220959) I get the following error message:
```
08-18 00:30:51.946   857   859 E :  mount /debug_ramdisk/magisk32 -> /debug_ramdisk/.magisk/worker/system/lib/libzygisk.so failed with 2: No such file or directory
08-18 00:30:51.946   857   859 E :  mount (null) -> /debug_ramdisk/.magisk/worker/system/lib/libzygisk.so failed with 22: Invalid argument
```

Downgrading to the older version [20220958](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220958) made Zygisk  and Youtube working again.

Did also found this issue that reports the same issue.
chiteroman/PlayIntegrityFix#402

My log:
[magisk_log_2024-08-18T00.32.15.log](https://github.com/user-attachments/files/16648142/magisk_log_2024-08-18T00.32.15.log)

**Comment by j-hc** [comment]
irrrlevant to rvmm

**Comment by phydelity** [comment]
UNSUBSCRIBE

Respectfully,
                                                  Jae
