### ISSUE TITLE
Autoplay next song stopped working 

### ISSUE THREAD

**Issue by Matrix-sudo** [j-hc/revanced-magisk-module#49]
Hey
Using the latest version, for some reason the autoplay next song isn't working even if it's toggled in the settings.

**Comment by Matrix-sudo** [comment]
I disabled in the ads section:
1) remove personal suggestions
2) hide suggestions
3) hide latest posts

And autoplay is working!
I'm guessing that option #2 is the curl pit since the autoplay works with the suggested next video to show

**Comment by j-hc** [comment]
i toggle on _show autoplay button_ from revanced settings and it works. regardless, if anything this is a revanced bug so im closing the issue.

**Comment by pocohiter** [comment]
@j-hc I have disabled all options in the ads but still can't autonext
