### ISSUE TITLE
How to include latest patches in template?

### ISSUE THREAD

**Issue by gyrorayo** [j-hc/revanced-magisk-module#494]
Hi, I'm trying to include/exclude some patches by following this instructions:
https://github.com/j-hc/revanced-magisk-module#to-includeexclude-patches-or-patch-other-apps

The problem is that I'm not able to apply the latest patches as in the original repo:

```
CLI: j-hc/revanced-cli-4.6.0-all.jar
Integrations: ReVanced/revanced-integrations-1.13.0.apk
Patches: ReVanced/revanced-patches-4.13.3.jar
[Changelog](https://github.com/ReVanced/revanced-patches/releases/tag/v4.13.3)
```

Skipped:
Patches: inotia00/revanced-patches-4.12.3.jar

 I'm getting these instead:

`CLI: inotia00/revanced-cli-4.6.1-all.jar
Integrations: inotia00/revanced-integrations-1.12.3.apk
Patches: inotia00/revanced-patches-4.12.3.jar
`

What settings do I need to change for the latest patches to get applied?

**Comment by j-hc** [comment]
latest patches is already the default selection

**Comment by gyrorayo** [comment]
So the output in releases really doesn't matter?

![image](https://github.com/user-attachments/assets/eb7c0504-4d80-4867-a367-d39dd7299dab)

I assume I have applied the latest patches as in your original repo?

**Comment by j-hc** [comment]
> So the output in releases really doesn't matter?
> I assume I have applied the latest patches as in your original repo?

those are the latest versions, same as in this repo, its literally in front of you.
yes, the text in release matters, why wouldnt it matter?
