### ISSUE TITLE
"Needs reflash: zygote crashed" on OnePlus OxygenOS

### ISSUE THREAD

**Issue by PKMNPlatin** [j-hc/revanced-magisk-module#495]
Hi,

I have two OnePlus Devices. A OnePlus 12 and a Pad 2.

On my OnePlus 12 I used the module flawlessly over months, never having a issue or something, but after I rooted the Pad, I noticed that I get this error on there.

Today I got a new Oxygen OS Update on my 12 and after I installed it I got the same error on that device too.

The weird thing about that is that the Version I was on my 12 before has the same Version Number as the new one, except that there is the Security Patch for August instead the July one included.

The Pad 2 came with the latest version and also the Security Patch of August, but I don't know if these things are related, its just my observation.

I already read the other issues addressing this problem, but there was no helping answer.

I would really appreciate if you could look into this or at least guide me in a direction, and maybe let me now if you need any logs or something that helps.

**Comment by j-hc** [comment]
there is nothing to fix from the side of the module. its something wrong with your setup and module is only reporting it.

**Comment by PKMNPlatin** [comment]
I got it fixed after some tinkering.

Had to debloat the YouTube App to a user app, and after reflashing the module it works again.

Was also able to get it running on my Pad btw.

I think it could be related to the use of core patch to skip  the INSTALL_FAILED_VERSION_DOWNGRADE error what normally shouldn't happen.
