### ISSUE TITLE
Magisk installed modules are overwritten by Google every morning. 

### ISSUE THREAD

**Issue by SaltedNinja** [j-hc/revanced-magisk-module#498]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

Magisk installed modules are overwritten by Google every morning. 
I have never had this issue previously until I updated to the latest Modules found here. 
Running magisk 270007, Zygist Next, Zygist Deteach, Zygist Assistant.
When the phone is left alone for hours or just plugged in overnight somehow Google is updating the YT & YTM modules to normal versions. Not entirely sure how this is happening. I have even tried using HMA to blacklist Playstore.
Is anyone else experiencing this or is this solely just me.?

**Comment by j-hc** [comment]
zygisk-detach works fine. there is something wrong with your setupm

**Comment by marcocancarini** [comment]
I recommend using update blocker for lsposed and add YouTube to the list
