### ISSUE TITLE
After 19.16.39 Problem with INSTALL_FAILED_VERSION_DOWNGRADE
I tried installing 19.25.39 with this stange error

### ISSUE THREAD

**Issue by fanaticsurf** [j-hc/revanced-magisk-module#499]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

- Copying zip to temp directory
- Installing youtube-revanced-extended-magisk-v19.25.39-all.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***************************
 YouTube ReVanced Extended 
 by j-hc 
***************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh
  inflating: customize.sh
  inflating: com.google.android.youtube.apk
  inflating: service.sh
  inflating: base.apk
  inflating: module.prop
  inflating: config
   creating: bin/
   creating: bin/x86/
  inflating: bin/x86/cmpr
   creating: bin/x64/
  inflating: bin/x64/cmpr
   creating: bin/arm64/
  inflating: bin/arm64/cmpr
   creating: bin/arm/
  inflating: bin/arm/cmpr

* com.google.android.youtube is up-to-date
* Setting Permissions
* Mounting com.google.android.youtube
mkdir: can't create directory '/rvhc': Read-only file system
mv: can't rename '/data/adb/modules_update/youtube-extended-jhc/base.apk': No such file or directory
ERROR: Mount failed!
mount: '/rvhc/youtube-extended-jhc.apk'->'/data/app/~~MUBbJzoYRnFgKDtn0857dg==/com.google.android.youtube-LgPGnAD6ljXKdtdNxHQd_w==/base.apk': No such file or directory
* Optimizing com.google.android.youtube
* Cleanup
* Done
  by j-hc (github.com/j-hc)
 
- Done

I have this issue on OnePlus 8T and 10 with Android 14. Same Version is working fine on Xiaomi Pad 6 with Android 14.

I'm using Magisk 27.007

What can I do do get it back running?

**Comment by j-hc** [comment]
old module
