### ISSUE TITLE
YouTube player control bug

### ISSUE THREAD

**Issue by Iamaj5** [j-hc/revanced-magisk-module#5]
YouTube pause button (player control doesn't go away 
Even if we tap or automatically after sometime)
It stays there until we close and open the video again
Please fix this bug as it is annoying

**Comment by j-hc** [comment]
please refrain from opening issues related to the revanced itself rather than the builder scripts or gh workflow configurations in this repo.

**Comment by Iamaj5** [comment]
> 

I don't much about that

**Comment by SirLouen** [comment]
> I don't much about that

This is just a revanced build for magisk. The author cannot do much about the software itself. Check https://github.com/revanced
