### ISSUE TITLE
Youtube freeze 

### ISSUE THREAD

**Issue by romiero** [j-hc/revanced-magisk-module#50]
Youtube freeze when open a video, the video is playing but the other not responding. It takes time  to load. And it make ui lag. All loaded and then ui responding

![Screenshot_20220917-171647_YouTube](https://user-images.githubusercontent.com/108507531/190849666-fb7073cd-0a24-4304-800b-32111b1d303a.png)

**Comment by j-hc** [comment]
try clearing the data. regardless, if anything this is a revanced bug.

**Comment by romiero** [comment]
> try clearing the data. regardless, if anything this is a revanced bug.

i think i found something, when i disable the Mindetach module. The Freeze problem gone.
