### ISSUE TITLE
YT Music - playing a song forces phone to reboot and uninstalling RVX Version

### ISSUE THREAD

**Issue by fanaticsurf** [j-hc/revanced-magisk-module#500]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

- Copying zip to temp directory
- Installing music-revanced-extended-magisk-v7.17.51-arm64-v8a.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*************************
 Music ReVanced Extended 
 by j-hc 
*************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: base.apk
  inflating: module.prop
  inflating: config
   creating: bin/
   creating: bin/arm64/
  inflating: bin/arm64/cmpr
   creating: bin/arm/
  inflating: bin/arm/cmpr
   creating: bin/x86/
  inflating: bin/x86/cmpr
   creating: bin/x64/
  inflating: bin/x64/cmpr
  inflating: customize.sh
  inflating: uninstall.sh
  inflating: com.google.android.apps.youtube.music.apk
  inflating: service.sh

* Un-mount
* com.google.android.apps.youtube.music is up-to-date
* Setting Permissions
* Mounting com.google.android.apps.youtube.music
* Optimizing com.google.android.apps.youtube.music
* Cleanup
* Done
  by j-hc (github.com/j-hc)
 
- Done

Seems to install fine even after reinstalling.
RVX Music Icon showing 
Trying to play a song reboots the phone immediatly.
After that normal Youtube App without revanced is installed again (YT Music Icon)

I'm using Magisk 27.007 with OnePlus 8t an 10 with latest Android 14 Release. Both have this Problem, while Xiaomi Pad 6 with Android 14 an equal version works fine. 

Any ideas?

**Comment by j-hc** [comment]
unrelated to the module. the reboot is what should be fixed
