### ISSUE TITLE
Magisk modules do not persist after reboot on APatch with KernelPatch 0.11.x

### ISSUE THREAD

**Issue by V0latyle** [j-hc/revanced-magisk-module#501]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**  
> if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo
> 
> Use issues only to report bugs of the rvmm builder or the modules

Device: Pixel 5
Stock ROM
Stock kernel

With Magisk 27.0, modules work perfectly

With APatch using KernelPatch, modules only work with KernelPatch 0.10.7 or lower - 0.11+ results in failure to mount post reboot with warning message "Needs reflash: app not installed"

**Comment by j-hc** [comment]
did you try latest builds?

**Comment by badabing2005** [comment]
It worked for me, though interestingly, on a rooted device, it needed microg

**Comment by V0latyle** [comment]
> did you try latest builds?

Yes. Just tried yesterday's release on Pixel 5, KernelPatch 0.11.1-dev, aPatch manager 10930. After flashing modules and reboot, YouTube and YT Music do not have ReVanced features and show ads.

It appears that the modules fail to bind the system YouTube and Music apps to /*/each/app.apk at boot. Again, this only happens on KernelPatch 0.11.x; the modules work normally on 0.10.7 (which does not boot on Pixel 5)

**Comment by j-hc** [comment]
> > did you try latest builds?
> 
> Yes. Just tried yesterday's release on Pixel 5, KernelPatch 0.11.1-dev, aPatch manager 10930. After flashing modules and reboot, YouTube and YT Music do not have ReVanced features and show ads.
> 
> It appears that the modules fail to bind the system YouTube and Music apps to /*/rvhc/app.apk at boot. Again, this only happens on KernelPatch 0.11.x; the modules work normally on 0.10.7 (which does not boot on Pixel 5)

it is hardcoded /data/adb/rvch/app.apk in latest builds, not /rvhc/..

**Comment by V0latyle** [comment]
> does it work when you flash the module and dont reboot? 
Yes
>and are you sure you dont have any residue mount scripts from revanced manager inside post-fs-data or service.d folders?
Yes, never had ReVanced Manager installed, and this happens with clean /ADB/ (all files/folders removed prior to aPatch setup)

**Comment by j-hc** [comment]
add this add the top of the service.sh in the module. then flash, reboot and see the logs.

`exec >/data/adb/rvlog.txt
exec 2>&1
set -x`

**Comment by V0latyle** [comment]
> add this add the top of the service.sh in the module. then flash, reboot and see the logs.
> 
> ```
> exec >/data/adb/rvlog.txt
> exec 2>&1
> set -x
> ```

Hmm. Just set up aPatch on my Pixel 3 test article - aPatch 10930, KernelPatch 0.11.1. Had some trouble where the module wouldn't complete installation, but finally got everything sorted, and the module seems to be working properly. So maybe it's just an issue with my specific setup on my Pixel 5 and previous versions of RVHC?

@badabing2005 mentioned it's working for him on his Pixel 5 so maybe it's just me. At some point I'll try to get this working on my setup again, if I run into issues I'll modify service.sh and report back.

**Comment by V0latyle** [comment]
Here's the result, but it looks to be working on the Pixel 3...just dealing with other aPatch bugs like modules disappearing after a reboot
`+ MODDIR=/data/adb/modules/youtube-jhc
+ RVPATH=/data/adb/rvhc/youtube-jhc.apk
+ . /data/adb/modules/youtube-jhc/config
+ PKG_NAME=com.google.android.youtube
+ PKG_VER=19.34.42
+ MODULE_ARCH=
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '['  '=' 1 ]
+ sleep 1
+ getprop sys.boot_completed
+ '[' 1 '=' 1 ]
+ '[' -d /sdcard/Android ]
+ pm path com.google.android.youtube
+ BASEPATH='package:/data/app/~~8_95kSOTOS57HgEeZLtMaw==/com.google.android.youtube-t5xE_aKe1YC9b2cTiUd6FA==/base.apk'
+ svcl=0
+ '[' 0 '=' 20 ]
+ sleep 5
+ '[' 0 '!=' 0 ]
+ BASEPATH='/data/app/~~8_95kSOTOS57HgEeZLtMaw==/com.google.android.youtube-t5xE_aKe1YC9b2cTiUd6FA==/base.apk' BASEPATH='/data/app/~~8_95kSOTOS57HgEeZLtMaw==/com.google.android.youtube-t5xE_aKe1YC9b2cTiUd6FA=='
+ '[' '!' -d '/data/app/~~8_95kSOTOS57HgEeZLtMaw==/com.google.android.youtube-t5xE_aKe1YC9b2cTiUd6FA==/lib' ]
+ rm /data/adb/modules/youtube-jhc/log.txt
rm: can't remove '/data/adb/modules/youtube-jhc/log.txt': No such file or directory
+ + grep -m1 versionName
dumpsys package com.google.android.youtube
Failed to write while dumping service package: Broken pipe
+ VERSION='    versionName=19.34.42' VERSION=19.34.42
+ '[' 19.34.42 '!=' 19.34.42 ]
+ grep com.google.android.youtube /proc/mounts
+ read -r line
+ chcon u:object_r:apk_data_file:s0 /data/adb/rvhc/youtube-jhc.apk
+ mount -o bind /data/adb/rvhc/youtube-jhc.apk '/data/app/~~8_95kSOTOS57HgEeZLtMaw==/com.google.android.youtube-t5xE_aKe1YC9b2cTiUd6FA==/base.apk'
+ am force-stop com.google.android.youtube
cmd: Failure calling service activity: Failed transaction (2147483646)
+ '[' -f /data/adb/modules/youtube-jhc/err ]


`

**Comment by V0latyle** [comment]
Ok, here is the failure.
[rvlog.txt](https://github.com/user-attachments/files/17530739/rvlog.txt)

**Comment by j-hc** [comment]
> Ok, here is the failure.
> [rvlog.txt](https://github.com/user-attachments/files/17530739/rvlog.txt)
> 

there is no failure in these logs. it successfully mounted.

**Comment by V0latyle** [comment]
> > Ok, here is the failure.
> > [rvlog.txt](https://github.com/user-attachments/files/17530739/rvlog.txt)
> 
> there is no failure in these logs. it successfully mounted.

Weird, because when I launched YouTube, I was getting ads and no Revanced option in settings.

**Comment by j-hc** [comment]
> > > Ok, here is the failure.
> > > [rvlog.txt](https://github.com/user-attachments/files/17530739/rvlog.txt)
> > 
> > 
> > there is no failure in these logs. it successfully mounted.
> 
> Weird, because when I launched YouTube, I was getting ads and no Revanced option in settings. At this point though I don't think it's a problem with your modules, I think it's a problem with how KernelPatch 0.11.x handles mounts. Thanks for checking.

try giving youtube root access
