### ISSUE TITLE
youtube version 19.16.39 is too old

### ISSUE THREAD

**Issue by qinvalerio** [j-hc/revanced-magisk-module#502]
Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.

**Comment by ramanveerji** [comment]
> Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> 

You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.

**Comment by kdejeqq** [comment]
> > Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> 
> You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.

And you are really a kid. This user is just asking for help and doesn't need to receive judgment. Moreover, he is right: I have the impression that you are just lazy to update your module with the latest YouTube. It's a shame to neglect maintenance.

**Comment by ramanveerji** [comment]
> > > Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> > 
> > You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.
> 
> And you are really a kid. This user is just asking for help and doesn't need to receive judgment. Moreover, he is right: I have the impression that you are just lazy to update your module with the latest YouTube. It's a shame to neglect maintenance.

You are dumber also. The latest version of YouTube supported by revanced patches is v19.16.39. Atleast check revanced page before saying anything.

**Comment by kdejeqq** [comment]
> > > > Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> > > 
> > > 
> > > You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.
> > 
> > 
> > And you are really a kid. This user is just asking for help and doesn't need to receive judgment. Moreover, he is right: I have the impression that you are just lazy to update your module with the latest YouTube. It's a shame to neglect maintenance.
> 
> You are dumber also. The latest version of YouTube supported by revanced patches is v19.16.39. Atleast check revanced page before saying anything.

that's what I'm saying, another toxic kid

**Comment by kdejeqq** [comment]
@qinvalerio let it go they are too lazy to update their module and they prefer to ignore user requests

**Comment by ramanveerji** [comment]
> > > > > Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> > > > 
> > > > 
> > > > You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.
> > > 
> > > 
> > > And you are really a kid. This user is just asking for help and doesn't need to receive judgment. Moreover, he is right: I have the impression that you are just lazy to update your module with the latest YouTube. It's a shame to neglect maintenance.
> > 
> > You are dumber also. The latest version of YouTube supported by revanced patches is v19.16.39. Atleast check revanced page before saying anything.
> 
> that's what I'm saying, another toxic kid + lazy 

Stop crying here, tell revanced team to support newer versions, This is not revanced repo. You don't even know the revanced repo how can you do something.

**Comment by ramanveerji** [comment]
> @qinvalerio let it go they are too lazy to update their module and they prefer to ignore user requests

Dumb users don't have brain to go and check revanced website or their repo to check the version supported by them.

**Comment by kdejeqq** [comment]
> > > > > > Pls update the youtube to a newer version, the v19.16.39 is older than the built-in one of my device (oneplus) after an OTA. Therefore I have to install the YouTube-Extended v19.25.39 magisk module released in July.
> > > > > 
> > > > > 
> > > > > You are really dumb. If you have root then just uninstall the stock YouTube app. And flash the yt magisk module. If you are non rooted then the package name of apk is different.
> > > > 
> > > > 
> > > > And you are really a kid. This user is just asking for help and doesn't need to receive judgment. Moreover, he is right: I have the impression that you are just lazy to update your module with the latest YouTube. It's a shame to neglect maintenance.
> > > 
> > > 
> > > You are dumber also. The latest version of YouTube supported by revanced patches is v19.16.39. Atleast check revanced page before saying anything.
> > 
> > 
> > that's what I'm saying, another toxic kid + lazy
> 
> Stop crying here, tell revanced team to support newer versions, This is not revanced repo. You don't even know the revanced repo how can you do something.
lol. In life you have to know how to stop maintaining things that you don't even know about. It's true he's still a kid

**Comment by ramanveerji** [comment]
> There is no point in closing this issue. You must take responsibility.

Use some brain 🧠. Atleast try to search the version supported by revanced team.

**Comment by kdejeqq** [comment]
> > There is no point in closing this issue. You must take responsibility.
> 
> Use some brain 🧠. Atleast try to search the version supported by revanced team.

Yes my kids

**Comment by kdejeqq** [comment]
> > > There is no point in closing this issue. You must take responsibility.
> > 
> > 
> > Use some brain 🧠. Atleast try to search the version supported by revanced team.
> 
> Yes my kids

Start by meeting our requirements

**Comment by ramanveerji** [comment]
Dumb will remain dumb

**Comment by kdejeqq** [comment]
> Dumb will remain dumb

ha I see you like it... well still be a child

**Comment by kdejeqq** [comment]
Fix Brain @ramanveerji

**Comment by ramanveerji** [comment]
> Fix Brain @ramanveerji 

I'm not going to talk with ill brained and dumber kids.

**Comment by kdejeqq** [comment]
> > Fix Brain @ramanveerji
> 
> I'm not going to talk with ill brained and dumber kids.

and yet you can't help but do it. It's that you must love your toxicity and your youth

**Comment by kdejeqq** [comment]
Otherwise it would be good if the latest version of YouTube and YouTube Music were updated in the Magisk module
