### ISSUE TITLE
Issue with ci and build.md

### ISSUE THREAD

**Issue by E85Addict** [j-hc/revanced-magisk-module#504]
https://github.com/j-hc/revanced-magisk-module/blob/b621def2c56953e1cb4f18a8f98f14275d2721d9/utils.sh#L92

After the new changes that added dev as an option on prebuilt version (amazing btw) it seems that this line here is duplicating the versions and source that already exist in the changelog.md. 

This also made me realize that the config_update() function should probably check if it should look for latest release or prerelease aka "dev"

**Comment by j-hc** [comment]
should be fine now
