### ISSUE TITLE
Incorrectly Detects New Patches/Integrations when using "dev" Versions

### ISSUE THREAD

**Issue by Zonkerus** [j-hc/revanced-magisk-module#505]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**  
> if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo
> 
> Use issues only to report bugs of the rvmm builder or the modules

Hi! If I use patches-version = "dev" and/or integrations-version = "dev", then when checking for new versions, a new module will be built even though there are no new versions. This is because this part of the code:
```
if ! last_patches=$(gh_req "https://api.github.com/repos/${PATCHES_SRC}/releases/latest" - |
	jq -e -r '.assets[] | select(.name | endswith("jar")) | .name'); then
```
Checks "releases/latest", which does not include prerelease versions (i.e., "dev").

I fixed this for myself like this:
```
if ! last_patches=$(gh_req "https://api.github.com/repos/${PATCHES_SRC}/releases" - |
	jq -e -r '.[0] | .assets[] | select(.name | endswith("jar")) | .name'); then
```
But this obviously won't work for those who use release versions because then they will have the same bug as I do with prerelease versions...

**Comment by j-hc** [comment]
fixed 3e3cf49
