### ISSUE TITLE
Incorrect zygote crash detection

### ISSUE THREAD

**Issue by enfJoao** [j-hc/revanced-magisk-module#507]
Using these modules for magisk for quite a while with no issues.

A week ago it suddently started detecting a zygote crash, but there is no crash or any other issue on log. 
Zygisk and all other apps are working fine, including yt music.

Tryed removing the magisk module, the app and starting again, but the issue persists.

![Screenshot_20240927_190112](https://github.com/user-attachments/assets/9ebeeb4e-05e3-42c4-b02f-cc85fdfcc27b)

Using Samsung S21FE rooted with the magisk method (flashed through odin).

**Comment by j-hc** [comment]
zygote is not an app. and no, its no incorrect. it crashed and broke the module. you need to fix your rom.
