### ISSUE TITLE
I can't install Revanced YouTube 

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [j-hc/revanced-magisk-module#51]
I can't install it even though I uninstalled the original
![Screenshot_2022-09-17-17-12-19-630_com google android googlequicksearchbox](https://user-images.githubusercontent.com/94727017/190851774-2a5ed126-a10d-4e9a-ad9a-6476d0dc446a.jpg)

**Comment by j-hc** [comment]
its a module, not an installable apk. nowhere in the readme is telling you to extract the apk out of the zip.
also stop copy-pasting my repositories and rebranding them
