### ISSUE TITLE
Google Play may forcefully uninstall the revanced extend version of YouTube Music even use zygisk-detach, and may cause the phone to freeze and reboot

### ISSUE THREAD

**Issue by greenredstone** [j-hc/revanced-magisk-module#512]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

The device crashed and rebooted several times at unspecified times and device conditions. After the reboot, the rvx music app was uninstalled, but the magisk module was still there. This also happened when using zygisk-detach. I suspect that Google Play forcefully uninstalled the modified version of YouTube music. Strangely, the rvx version of YouTube would not be forcefully uninstalled.

---------Device------------
Device name: Galaxy S23 Ultra
Model: SM-S9180
Manufacturer: samsung
Device: dm3q
Motherboard: kalama
Platform: qcom
Brand: samsung
Version name: Android 14 Upside Down Cake
API version: 34
System version number: UP1A.231005.007.S9180ZHS4CXG2
Build time: 04 July 2024 16:52:08 GMT+08:00
Device version number: UP1A.231005.007
Program security patch level: 2024-07-01
Bootloader: S9180ZHS4CXG2
Baseband version: S9180ZCS4CXFC,S9180ZCS4CXFC

**Comment by j-hc** [comment]
this has nothing to do with play store or zygisk-detach. your phone force-reboots and breaks the module.

**Comment by aHqeem94** [comment]
I just got this bug after flashing new update of vanced zip. Youtube back to normal. Device will stuck on screen logo after restart or poweroff device.
