### ISSUE TITLE
(question) give root permission to youtube, but how?!

### ISSUE THREAD

**Issue by FurhadTheNerd** [j-hc/revanced-magisk-module#515]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

i apologize if this is the wrong place to ask a question

after installing the youtube revanced module, it says on the magisk terminal "give root permission to com.google.android.youtube"
but there is no explanation on how to do it, RVX or youtube don't ask for root permission upon opening them, and they don't show up as an option in magisk's superuser tab
i tried using magisk's CLI in termux but there isn't any option to manually give root permission to an app
I'm at a loss here, i again sincerely apologize if this is the wrong place or of my question is dumb or if I'm missing something out

**Comment by j-hc** [comment]
its only for kernelsu
