### ISSUE TITLE
Needs reflash: 'system force-rebooted (fix your ROM)'

### ISSUE THREAD

**Issue by drandrew1983** [j-hc/revanced-magisk-module#516]
the latest YouTube revanced extended module doesn't work, the application still the official app not the revanced app. on checking magisk the module shows 'Needs reflash: 'system force-rebooted (fix your ROM)'
the problem started after updating my pixel 8 to android 15 just today.
I tried uninstalling and reinstalling the revanced YouTube magisk module or install it again over the old module, restarting, updating with the official YouTube and then uninstalling the update, but nothing worked so far.

**Comment by aHqeem94** [comment]
Same problem here. Now i use old version and never update. Work fine til now
