### ISSUE TITLE
Install failed (INSTALL_FAILED_VERSION_DOWNGRADE)

### ISSUE THREAD

**Issue by thatsupnow** [j-hc/revanced-magisk-module#517]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

Says it installed but Youtube just vanishes. I'm not sure what the deal is. Music works just fine. Seems like an Android 15 thing

**Comment by j-hc** [comment]
send flash logs

**Comment by mingaldrichgan** [comment]
I think you have to flash it a second time after rebooting. I remember seeing a message (when flashing the fixed version) to that effect. The first flash removed the factory version, and the second flash installed the patched version.

**Comment by thatsupnow** [comment]
> send flash logs



> I think you have to flash it a second time after rebooting. I remember seeing a message (when flashing the fixed version) to that effect. The first flash removed the factory version, and the second flash installed the patched version.

It's all good now. I flashed the July 5 release, reboot, then flashed the latest release twice and it's working as it should now. Thanks
