### ISSUE TITLE
Extended: unable to apply a patch

### ISSUE THREAD

**Issue by kevinr990** [j-hc/revanced-magisk-module#518]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

I'm not reporting a patch bug, but a bug when applying a patch (which doesn't happen on RVX Manager).
The Builder refuses to apply `Return YouTube Username` despite manual addition in [config.toml](https://github.com/Kevinr99089/Ex.Builder/blob/main/config.toml).

Log: https://github.com/Kevinr99089/Ex.Builder/actions/runs/11478033044/job/31941377096 .
Moreover, it has the -m argument, unlike all other patches, which have the -i or -e argument (for included or excluded, I suppose).

I tried to apply the same patches from RVX Manager, all patches apply correctly.

Did I forget to change something somewhere?

**Comment by j-hc** [comment]
"Return YouTube Username" is a revanced-extended patch. you are building regular revanced in your config

**Comment by kevinr990** [comment]
No, I'm building with ReVanced Extended patches (see [build.sh](https://github.com/Kevinr99089/Ex.Builder/blob/main/build.sh) lines 28 to 30).

**Comment by j-hc** [comment]
dont report issue with your own edits in the source.

its on you if you go and edit the source when you can do the same thing in the config with 2 lines

**Comment by kevinr990** [comment]
All right, so I did as you said, modified config.toml, restored build.sh, the problem remains the same:
https://github.com/Kevinr99089/Ex.Builder/actions/runs/11484914596/job/31963810007

**Comment by j-hc** [comment]
> All right, so I did as you said, modified config.toml, restored build.sh, the problem remains the same: https://github.com/Kevinr99089/Ex.Builder/actions/runs/11484914596/job/31963810007

i run your config and it included the patch just fine. start with a clean fork, you have many meaningless changes in the source.

**Comment by kevinr990** [comment]
In the logs, despite noting that this patch is excluded, the patch still applies. Thank you for answering my questions.
