### ISSUE TITLE
RVX on Android 15 with KSU doesn't install 

### ISSUE THREAD

**Issue by azcolgatewhite** [j-hc/revanced-magisk-module#519]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules
I'm trying to add log, attaching file but I can't.

>   _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 197.76 MB
- Mounting image
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
***************************
 YouTube ReVanced eXtended 
 by NoName-exe 
***************************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: com.google.android.youtube.apk
  inflating: service.sh
  inflating: config
  inflating: uninstall.sh
   creating: bin/
   creating: bin/x64/
  inflating: bin/x64/cmpr
   creating: bin/arm/
  inflating: bin/arm/cmpr
   creating: bin/x86/
  inflating: bin/x86/cmpr
   creating: bin/arm64/
  inflating: bin/arm64/cmpr
  inflating: module.prop
  inflating: customize.sh
  inflating: base.apk

- Updating com.google.android.youtube to 19.16.39
- INSTALL_FAILED_VERSION_DOWNGRADE. Uninstalling...
Failure [not installed for 0]

- Error: Failed to install module script
Error: Failed to install module script

**Comment by belinux** [comment]
I had the same issue, uninstalled the module, then installed it and it worked.

**Comment by j-hc** [comment]
```
YouTube ReVanced eXtended
by NoName-exe
```

?
dont use modules from renamers and report issues here

**Comment by azcolgatewhite** [comment]
I'm sorry, I've chosen the wrong log... By the way I could make working the RVX rebooting manually and re installing.... But I still can't watch my saved films....

**Comment by marcocancarini** [comment]
If you're using ksu and zygisk you need to give root permissions to YouTube
