### ISSUE TITLE
Build fails after the breaking changes made by Revanced

### ISSUE THREAD

**Issue by Lassie111** [j-hc/revanced-magisk-module#525]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

After Revanced merged integrations into the patches repo, it looks like the builder will need some rework.

**Comment by j-hc** [comment]
53f738b

**Comment by trmdi** [comment]
How to specify patch options now?

**Comment by j-hc** [comment]
> How to specify patch options now?

i dont know and dont care tbh so didnt add it. make a pr if you find out.

**Comment by Lassie111** [comment]
> [53f738b](https://github.com/j-hc/revanced-magisk-module/commit/53f738bc4167fd7ae164dc69df0916c21bd998f7)

In order not to break revanced-extended, I guess it would be better if you can control it by some key in `config.toml`. For example, if `integrations-source` is not set, there is no integrations. Probably the differences in the CLI make it hard to implement? (Though, it looks to me that it will be possible, in the worst case with code duplication unfortunately).

**Comment by j-hc** [comment]
> > [53f738b](https://github.com/j-hc/revanced-magisk-module/commit/53f738bc4167fd7ae164dc69df0916c21bd998f7)
> 
> In order not to break revanced-extended, I guess it would be better if you can control it by some key in `config.toml`. For example, if `integrations-source` is not set, there is no integrations. Probably the differences in the CLI make it hard to implement? (Though, it looks to me that it will be possible, in the worst case with code duplication unfortunately).

revanced extended patches will need to be updated to be used with rvmm
