### ISSUE TITLE
version in auto is not working properly

### ISSUE THREAD

**Issue by ramanveerji** [j-hc/revanced-magisk-module#526]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

When version is set to auto in config file it is taking the latest and not the one which is supported by patch.
[+] Choosing version '19.44.37' for YouTube
[+] Downloading 'YouTube' from apkmirror

[YouTube]
enabled = true 
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "'Custom branding'"                                  # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "'Predictive back gesture'"                          # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
riplib = true

I have to edit it to 19.43.41 to manually

**Comment by j-hc** [comment]
d9078f2
