### ISSUE TITLE
What is the current way to use options?

### ISSUE THREAD

**Issue by kazimmt** [j-hc/revanced-magisk-module#528]
If i want premium header, how can I apply it?

```
-e "Change header" -Oheader=premium*header
```

This is the latest command, but where to use it as there is no options

**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

**Comment by j-hc** [comment]
added patcher-args options on config
8281608
