### ISSUE TITLE
patcher-args

### ISSUE THREAD

**Issue by TidalMist** [j-hc/revanced-magisk-module#529]
https://github.com/j-hc/revanced-magisk-module/blob/828160801d6a11b468b2f71c145861f77c08cc24/utils.sh#L13
grep -o '^[^#]*'  removes #FF0F0F0F from -e 'Theme' -OdarkThemeBackgroundColor=#FF0F0F0F and it shows -e "Theme" -OdarkThemeBackgroundColor= -e "GmsCore support" in pr "$cmd"
https://github.com/j-hc/revanced-magisk-module/blob/828160801d6a11b468b2f71c145861f77c08cc24/CONFIG.md?plain=1#L30
Option not work if -e "Theme" -e "Change version code" -OdarkThemeBackgroundColor=#FF0F0F0F
Better patcher-args =  "-e 'Patch name' -Okey=value"

**Comment by j-hc** [comment]
9b696e8
