### ISSUE TITLE
Add Spotify Music build

### ISSUE THREAD

**Issue by rabilrbl** [j-hc/revanced-magisk-module#53]
The revanced patches now support spotify music.
![image](https://user-images.githubusercontent.com/63334479/192079675-a051224e-4439-461f-a67a-5d60ea3528ae.png)

**Comment by j-hc** [comment]
that looks like a pretty useless patch. i dont think i will include spotify.
revanced-patcher cant patch spotify with premium anyways as it would need to be able to patch native code which it cant as of now.

**Comment by rabilrbl** [comment]
In case if someone want to add, spotify music is not found in apkmirror.
