### ISSUE TITLE
RVMM Config Generator not working

### ISSUE THREAD

**Issue by sneedger** [j-hc/revanced-magisk-module#530]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

![image](https://github.com/user-attachments/assets/a4c047ab-13c9-4e6a-a48c-7b93c1dd7f61)

**The RVMM Config Generator at https://j-hc.github.io/rvmm-config-gen/ is not working as of now, it doesn't load at all, tried both on desktop and mobile on several browsers.**

**Comment by j-hc** [comment]
3bc290b
