### ISSUE TITLE
Can't get package name - empty

### ISSUE THREAD

**Issue by HpNoTiQ56** [j-hc/revanced-magisk-module#532]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

I'm trying to compile strava apk but utils fails in retrieving package name saying it's empty.

My config : 
[Strava]
build-mode = "module"
#arch = "arm64-v8a"
version = "385.14"
dpi="120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps"

**Comment by j-hc** [comment]
apkmirror is blocking.
try uptodown
