### ISSUE TITLE
Patches Fail

### ISSUE THREAD

**Issue by TeaqariaWTF** [j-hc/revanced-magisk-module#542]
Hi ,

These are my settings

[YouTube-Extended]
app-name = "YouTube"
build-mode = "both"
version = "19.16.39"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.231.0"
integrations-version = "v0.158.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
included-patches = "'Custom branding' 'Change header'"
patcher-args = " -OappName=YouTube -OiconPath=MMT -Oheader=Premium "
arch = "arm64-v8a"

I wonder if you can tell me where I went wrong.

**Comment by j-hc** [comment]
> integrations-source = "anddea/revanced-integrations"

integrations as a seperate apk is not a thing anymore and not supported by the rvmm

**Comment by TeaqariaWTF** [comment]
> > integrations-source = "anddea/revanced-integrations"
> 
> integrations as a seperate apk is not a thing anymore and not supported by the rvmm

I don't quite understand what you mean, is it not possible?

**Comment by j-hc** [comment]
> > > integrations-source = "anddea/revanced-integrations"
> > 
> > integrations as a seperate apk is not a thing anymore and not supported by the rvmm
> 
> I don't quite understand what you mean, is it not possible?

seperate integrations apk doesnt exist anymore. rvmm doesnt support any patches bundle that still hasnt updated with the latest changes from revanced.
