### ISSUE TITLE
Music-revanced  doesn't seem to work.

### ISSUE THREAD

**Issue by daniloy** [j-hc/revanced-magisk-module#544]
Installed music-revaned-magisk and zygisk-decath, but can't find the revanced option like youtube.
What should I do to use music-revanced correctly.

**DO NOT REPORT REVANCED STUFF IN THIS REPO **  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

**Comment by j-hc** [comment]
it works fine. check your other modules
