### ISSUE TITLE
Newest RVX inotia00 release not launching

### ISSUE THREAD

**Issue by frutejuise** [j-hc/revanced-magisk-module#546]
When I try to update RVX from the previous build, the app won't launch until I downgrade again. It kinda just crashes at launch.

**Comment by mingaldrichgan** [comment]
FWIW I have tried building this using my own configuration, both with `cli-source = "inotia00/revanced-cli"` and without (i.e. defaulting to `"j-hc/revanced-cli"`, and the result is the same. This has been true of YouTube and YT Music (both built as Magisk modules) and Reddit (built as APK), all with `patches-source = "inotia00/revanced-patches"`.

**Comment by frutejuise** [comment]
I just use the apk, not rooted sadly.

**Comment by frutejuise** [comment]
And I only go with inotia00 builds, I just like the design better 😅

**Comment by Pocarai** [comment]
> FWIW I have tried building this using my own configuration, both with `cli-source = "inotia00/revanced-cli"` and without (i.e. defaulting to `"j-hc/revanced-cli"`, and the result is the same. This has been true of YouTube and YT Music (both built as Magisk modules) and Reddit (built as APK), all with `patches-source = "inotia00/revanced-patches"`.

Where did you get inotia00 apk patches? I want to apply it to Obtainium updater

**Comment by mingaldrichgan** [comment]
> Where did you get inotia00 apk patches? I want to apply it to Obtainium updater

I build my own using a clone of this repo, but those builds aren't currently working.

**Comment by j-hc** [comment]
https://github.com/j-hc/revanced-magisk-module/issues/545
