### ISSUE TITLE
Request: Include Revanced patch version in filenames

### ISSUE THREAD

**Issue by V0latyle** [j-hc/revanced-magisk-module#548]
Modules and APKs are currently named by original app version but do not include Revanced/RVX version. This can cause some confusion when the app/module is updated with new Revanced version but app version remains the same.

Example: music-revanced-v7.29.51 has been patched by 5.2.0, 5.2.1, 5.2.2, 5.2.3, and 5.3.0, yet the filenames all remain the same.

Recommend including Revanced patch version in filename, example music-v7.29.51-revanced-5.3.0

**Comment by j-hc** [comment]
i can add it to the "version" string of modules but it'd make the file names too long.

**Comment by j-hc** [comment]
e65a296
