### ISSUE TITLE
KSU + zygisk assistant permissions

### ISSUE THREAD

**Issue by marcocancarini** [j-hc/revanced-magisk-module#549]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

I installed the module in kernelsu, I have zygisk assistant. While installing the module says:
"If you are using zygisk-assistant, you need to give root permissions to com.google.android.youtube"
Im trying to set a custom profile for the permissions, I set group root, system and capability sysadmin, uid gid 1000,u:r:su:s0. It seems to work. 
Is it fine or am I missing something? Thank you

**Comment by j-hc** [comment]
not an issue
