### ISSUE TITLE
getting ERROR: Mount failed! while Installing

### ISSUE THREAD

**Issue by kamilmirza** [j-hc/revanced-magisk-module#55]
as per title getting the following:
![Screenshot_20220925-192026_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/6561475/192148948-a78f9d20-f56c-4ac4-9008-d089964e4830.png)

**Comment by j-hc** [comment]
use official magisk manager

**Comment by Neucher** [comment]
I get this exact error using the official magisk manager everytime I reflash the module.

**Comment by j-hc** [comment]
@Neucher do you use miui?

**Comment by Neucher** [comment]
Tried both aosp a11 and miui a12

**Comment by j-hc** [comment]
@Neucher can you send an ss of the error

**Comment by Neucher** [comment]
it's the exact same as above. I can only flash the module if I manually create the tmp folder above. Though that one gets deleted every reboot so I have to reflash every reboot.

**Comment by j-hc** [comment]
@Neucher did you try with the recent versions. it should be ok now.

**Comment by Neucher** [comment]
Yes it works now thanks
