### ISSUE TITLE
Version error in latest music revanced module build

### ISSUE THREAD

**Issue by ertmuirm** [j-hc/revanced-magisk-module#550]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

Header says install 7.16.53, but actual version installed is 7.29.52

**Comment by j-hc** [comment]
elaborate more then we can reopen the issue.

maybe starting with what "Header" is

**Comment by ertmuirm** [comment]
After installing, it says version incompatible. There seem to be two version numbers in the build. One is 7.16.53 (old code that may not have been updated), the other is 7.29.52 (this should be the correct version)
