### ISSUE TITLE
Module get randomly disabled

### ISSUE THREAD

**Issue by RYSKLE** [j-hc/revanced-magisk-module#551]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules
Hello,
Some random issue happen make the phone reboot then modules yt music and youtube get disabled. 
I said random because both app arent even in use when this happen. 
Also, doesnt affect any other modules as have 10+ other module installed but for other purpose not affecting this 2 concerned here.
Configuration : mi 11 ultra, miui 14 android 13
Kitsune mask + zynsk detach 

I also notice this usually happen when an update in the 2 module is available but not sure about this point.

Thanks

**Comment by j-hc** [comment]
"disabled"?

**Comment by JakubZ0** [comment]
yeah, it reverting back/updating youtube with ads etc. and only reinstall of module helps for me. Happends randomly with detaching enabled for me, idk what's wrong. Any ideas? thanks

**Comment by j-hc** [comment]
what does the module description in magisk/kernelsu say?

**Comment by RYSKLE** [comment]
Disabled i mean switch off in magisk module management. 
Description just have the name of your module and the version nothing more

**Comment by j-hc** [comment]
> Disabled i mean switch off in magisk module management.

thats not possible. its something do to with your setup.
