### ISSUE TITLE
RVX patches again crash when built with rvmm

### ISSUE THREAD

**Issue by peternmuller** [j-hc/revanced-magisk-module#554]
As of today, when patching with latest RVX 5.1.1 patches, apps crash like last time... https://paste.crdroid.net/fVNHTU
Might seem like it's deliberate, although please check once again his repo to find why it is the case.

**Comment by j-hc** [comment]
too bad. i wont bother myself more for something i dont use.

**Comment by E85Addict** [comment]
Latest release of patches v5.1.3 seem to be working once again using github actions and this repo. He has removed the partial/public code that caused the crash initially and even made a commit to help with the usage of Revancify, which is another 3rd party revanced tool/builder. I'm assuming that it should be okay now to re-enable but that is up to you, there's no telling if something will be done in the future to disable/crash 3rd party builds.

**Comment by tanishqmanuja** [comment]
Can someone suggest, how to get latest rvx build (with dark splash animation like december build) as the normal revanced version is burning my eyes with white splash animation 😭

**Comment by sms1sis** [comment]
Is there any codec selection option in YouTube revached?
