### ISSUE TITLE
[Request] Hide revanced base.apk mountpoint

### ISSUE THREAD

**Issue by HuskyDG** [j-hc/revanced-magisk-module#56]
Many banking apps detect the mountpoint of `base.apk` for no reason. You should find a way to hide mountpoint of revanced.
https://t.me/magiskdelta/314

**Comment by j-hc** [comment]
that issue was already fixed https://github.com/j-hc/revanced-magisk-module/issues/46
it doesnt work for you?

**Comment by HuskyDG** [comment]
> that issue was already fixed #46 it doesnt work for you?

Remember it is always a cat-mouse game, your solution is temporary and later some banking apps will update and detect `base.apk` mountpoint, you can check:
```
magisk --denylist grep base.apk /proc/mounts
```

**Comment by HuskyDG** [comment]
https://github.com/revanced/revanced-cli/pull/122

**Comment by j-hc** [comment]
> [revanced/revanced-cli#122](https://github.com/revanced/revanced-cli/pull/122)

this doesnt even fix the issue. are you even using the module? if not, do not create issues blindly.

**Comment by HuskyDG** [comment]
why not use another location than `/data/local/tmp`, you know it can be scanned by any app ¯\_(ツ)_/¯

**Comment by j-hc** [comment]
any app can view the mounts in the global mount namespace including those from the base dir of magisk. so anywhere without the mention of magisk looks ok so far. the commit you sent literally doesnt work, i dont get what you are wanting me to change here from something that actually works and doesnt trip any magisk detection?

**Comment by HuskyDG** [comment]
> any app can view all the mounts in the global mount namespace including those from the base dir of magisk.
Wrong, you might not know due to the nature of mount namespace, every app will see different `/proc/mounts`, what is what MagiskHide rely on. And about the internal implementation of MagiskHide, I will not explain here.

**Comment by j-hc** [comment]
> > any app can view all the mounts in the global mount namespace including those from the base dir of magisk.
> 
> Nah, you might not know due to the nature of mount namespace, every app will see different `/proc/mounts`, that is what MagiskHide used to rely on and why app are not in hide list can still get root access.

well im pretty sure almost all processes can see the bind mounts. if there is something magisk internal that can hide that from everything but gms idk. but i tested both revanced cli's mount and mounting from /data/local/tmp and mine worked so i keep it as is rn.
i might write a zygisk module some time later that could get rid of all this, i will see.

**Comment by HuskyDG** [comment]
> well im pretty sure almost all processes can see the bind mounts. if there is something magisk internal that can hide that idk. but i tested both revanced cli's mount and mounting from /data/local/tmp and mine worked so i keep it as is rn. i might write a zygisk module, that will hook into pm and fake the signature, some time later that could get rid of all this, i will see.

How about dynamic bind mount?

**Comment by j-hc** [comment]
i dont think the overhead of that kind of thing would be worth it

**Comment by HuskyDG** [comment]
> i might write a zygisk module, that will hook into pm and fake the signature, some time later that could get rid of all this, i will see.

remember that inject zygote will make it more detectable than hidden, especially there are the big holes in zygisk.
