### ISSUE TITLE
Updating protocol 

### ISSUE THREAD

**Issue by SirLouen** [j-hc/revanced-magisk-module#6]
In the readme.md it says:

> The modules support Magisk update which means you will receive updates from your Magisk app, downloading from github releases and reflashing is not necessary.
>To be able to update YouTube version, you will need to:

> Disable the module
> Reboot
> Install the APK of the new YouTube
> Update the module and reboot again

What Í'm currently doing is:

> Install the APK of the new YT/YT Music but don't open it.
> Update module without disabling 
> Rebooting

Everything works fine, with fewer steps. Theoretically, on how filesystems are built this should be working.

**Comment by j-hc** [comment]
those steps are required if you have youtube installed as a system app. i should clarify that in the readme.

**Comment by SirLouen** [comment]
> those steps are required if you have youtube installed as a system app. i should clarify that in the readme.

👍 Did not consider that. I don't have them as system app, but installed.

**Comment by j-hc** [comment]
should be good now faf6900
