### ISSUE TITLE
[Feature Request] Add support to Spotify

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#64]
Recently, ReVanced team added support to Spotify and it would be good to add to this repo too, I know Spotify apks are not available on [APKMirror](https://www.apkmirror.com/?post_type=app_release&searchtype=app&s=spotify) but seems to be available on [Uptodown](https://spotify.en.uptodown.com/android) and it could be possible to make something like [this python script did](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/main.py).

**Comment by j-hc** [comment]
spotify patches are pretty useless so they are not a priority right now. i will write a play store downloader once the revanced patcher and cli starts supporting split apks.

**Comment by j-hc** [comment]
in the meantime. i added spotify support anyways 4db583e
