### ISSUE TITLE
YouTube version update

### ISSUE THREAD

**Issue by 4B3L41D** [j-hc/revanced-magisk-module#66]
Firstly I would like to thank you for your work !
Now my question is why I have a youtube revanced update tagged 17.36.37 as of 10/06 and youtube playstore is tagged 17.39.34 as of 10/06 ? Seems like youtube revanced stagnate at version 17.36.37.

**Comment by j-hc** [comment]
read build.conf. you can build always the latest version with --experimental flag. other than that, only the supported version will be built.
