### ISSUE TITLE
More detailed Readme 

### ISSUE THREAD

**Issue by nadiration** [j-hc/revanced-magisk-module#7]
First ot all thank you for the great work you have done, you really helped us here. everything is cool I'm just here to give my feedback about the readme. It could use some more details like that this project (modules) support more than just YouTube and that it supports Reddit, Twitter... With the features the modules provide or what they patch.

Thank you for reading.

**Comment by j-hc** [comment]
modules do not provide anything other than bypassing things like signature so its possible to login with a google account. patched twitter or reddit wouldnt benefit from that as they dont have google login (well they do but nobody uses it). i guess that clarifies things?
