### ISSUE TITLE
I have to uninstall YT before flashing the update

### ISSUE THREAD

**Issue by panosru** [j-hc/revanced-magisk-module#70]
Hey, when a new update appears for either YT and YT Music, I'm unable to update it directly, I'm receiving the following error:

![Screenshot_20221009-163231_Fox's Magisk Module Manager.png](https://user-images.githubusercontent.com/400362/194759773-fa228397-c312-4347-9a57-2118c0bfa030.png)

And similar error for YT. The only way to update the apps for me is to uninstall the previously installed apps, then flash the updates.

While that works, I lose all my settings and I have to re do them every time...

Any workaround or a solution is appreciated! Thanks!

**Comment by j-hc** [comment]
use official magisk manager

**Comment by panosru** [comment]
@j-hc yeap, that worked, I thought that the process was the same between fox and the magisk manager, thanks!
