### ISSUE TITLE
App shows not installed after reboot

### ISSUE THREAD

**Issue by Rtizer-9** [j-hc/revanced-magisk-module#73]
Earlier everything was working perfectly without any error in magisk log or elsewhere.

Even now the ytmusic module works perfectly.

The issue is that if I flash vanced module then app shows in the drawer and works perfectly but as soon as I reboot the app goes away.

I tried removing module completely from both magisk and the data/adb/modules folder to start from a clean state but same results. In one of my root app manager a greyed entry shows about vanced but it says the app's not installed.

Vanced music module working perfectly though.

**Comment by j-hc** [comment]
what is the output of this command. you need to execute it your phone using something like termux:
`su -c ls -l $(pm path com.google.android.youtube | sed 's/package://g' | sed 's/\/base\.apk//g')`

**Comment by j-hc** [comment]
what is the output of this command. you need to execute on your phone using something like termux:
`su -c ls -l $(pm path com.google.android.youtube | sed 's/package://g' | sed 's/\/base\.apk//g')`

**Comment by Rtizer-9** [comment]
![Screenshot_20221011-221427~2.png](https://user-images.githubusercontent.com/35103368/195152812-18af1a4c-3cf4-4be4-a2a0-a5646ef3b9a4.png)

This is after I reboot.

**Comment by Rtizer-9** [comment]
![Screenshot_20221011-220919_Termux~2.png](https://user-images.githubusercontent.com/35103368/195154404-ab4eb85e-2b83-4402-b244-f4b7900011b1.png)

This is after installing the module but before the reboot.

**Comment by j-hc** [comment]
im not sure whats the issue. for nowyou can install the stock apk from inside the module before flashing.

**Comment by Rtizer-9** [comment]
I found out what the issue was - the latest version of Dolby magisk module was causing the problem because it has some huge changes. If that module is active, vanced doesn't show up in launcher.

**Comment by halal-beef** [comment]
i was having the same issue, glad to see it was dolby... looks like im gonna stay with non root :(

**Comment by Rtizer-9** [comment]
@halal-beef well you can simply install the previous last third version of Dolby magisk module to make them work together without any conflict. By the way just to be on the same page I was talking about Dolby magisk module made ryuki available on pling website; I assume you're not confusing it with stock or any other dolby.

**Comment by halal-beef** [comment]
i also use ryuki's module

**Comment by j-hc** [comment]
can you send me a link to this "dolby magisk module"

**Comment by halal-beef** [comment]
heres one of them https://github.com/reiryuki/Dolby-Audio-Moto-G6-Magisk-Module

**Comment by Rtizer-9** [comment]
@j-hc the specific one which I had issue with is the latest version here - https://www.pling.com/p/1461991/

**Comment by j-hc** [comment]
@Rtizer-9 @halal-beef fyi, the fix is to increase the mount delay. then you can use the module with latest dolby:
https://github.com/j-hc/revanced-magisk-module/blob/5b204e83cfb9c7db88a90880353006734d589f6e/build.conf#L17

you can change it in your own fork or do it manually on your device.

**Comment by j-hc** [comment]
@Rtizer-9 latest changes have issue right now. other than that what you should do is to fork the repo and change mount delay to 20 and every update you get will have it as 20.

**Comment by Rtizer-9** [comment]
I tried using your build instead of mine delay=20 build and app was still there, maybe something changed in Dolby latest release. Is that apk now provided in releases non-root?

**Comment by Rtizer-9** [comment]
I can confirm at this point that the latest Dolby builds do not cause any conflicts with this module and working without increase in mount delay.
