### ISSUE TITLE
Can't build modules anymore after last two commits

### ISSUE THREAD

**Issue by achyutde13** [j-hc/revanced-magisk-module#74]
Everytime I try to build modules now it always fails to upload the files, i synced the fork and made changes to the build.conf as i always do but now it always fails. I have attached a screeshot of the step it fails at.

![image](https://user-images.githubusercontent.com/38592400/195464535-80950f48-4916-4e24-ba68-e78c2c6e46b5.png)

**Comment by j-hc** [comment]
your tags are messed up. start with a clean fork.
