### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by Vucko130** [j-hc/revanced-magisk-module#76]
Getting prebuilts
https://api.github.com/repos/j-hc/revanced-cli/releases/latest:
2022-[10](https://github.com/Vucko130/revanced-magisk-module/actions/runs/3254137833/jobs/5342062196#step:5:11)-15 02:43:02 ERROR 404: Not Found.
Error: Process completed with exit code 8.

![image](https://user-images.githubusercontent.com/92352731/195965725-37f2b325-4ba6-49fe-9288-adfc86a28619.png)

**Comment by j-hc** [comment]
fixed
