### ISSUE TITLE
After new update both variant YouTube revanced crashing. I have attached Screenshot of it.

### ISSUE THREAD

**Issue by EternalYogee** [j-hc/revanced-magisk-module#79]
![Screenshot_2022-10-21-19-00-19-795_com.miui.home.jpg](https://user-images.githubusercontent.com/116342128/197208232-8037fe16-1552-4fa8-b368-97b708813f8a.jpg)

**Comment by Spythonion** [comment]
![Screenshot_2022-10-21-19-05-42-919_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/116342128/197208765-b5c620d0-787d-43c3-9b6f-a15718ca81c9.jpg)

**Comment by j-hc** [comment]
i reverted the update for now. will see later.

**Comment by E85Addict** [comment]
Was also having the issue, not related to magisk module, see here https://github.com/revanced/revanced-patches/issues/825

**Comment by biscober** [comment]
Just want to say latest update still crashing me (my phone and OS is OP8 with OOS12 C.35 update).  I know it's not the fault of the magisk module but rather the revanced patches, just wanted to say it here.  Went back to my previous ver (from Oct 14) and its fine.

**Comment by j-hc** [comment]
yeah the issue was with the hide-create-button patch. latest update.no longer crashes.
