### ISSUE TITLE
Add ability to include patches on build.conf

### ISSUE THREAD

**Issue by MatadorProBr** [j-hc/revanced-magisk-module#82]
For now, you can only exclude patches using build.conf, but there is some patches that are excluded by default (like the ``enable-debugging`` and ``compact-header`` patch), and there is no way to include then using the build.conf, so maybe it would be cool to make a separate config to include patches like these.

**Comment by nkoc6a15** [comment]
Have you try with -i patch name?

**Comment by nkoc6a15** [comment]
https://github.com/j-hc/revanced-magisk-module/commit/b995d480ad89f4ccfc0b12981dc2f5d775a5b719
 https://github.com/j-hc/revanced-magisk-module/commit/880bb0b0c9e0ded91a9fdc3b8bd30b12580bde54
 
 I tested and its working fine but i dont know how to make a PR

**Comment by j-hc** [comment]
added i the latest update

**Comment by tgw314** [comment]
https://github.com/j-hc/revanced-magisk-module/blob/ffd2fa8da44cc5574311a8b670dbc7c7d875b9f0/utils.sh#L279
It doesn't work because the `--exclusive` option is missing.

**Comment by j-hc** [comment]
INCLUDED_PATCHES variable is to include patches that are not included by default

**Comment by tgw314** [comment]
Sorry, I misunderstood.
