### ISSUE TITLE
Updating Magisk module through Fox MMM fails (mounting error)

### ISSUE THREAD

**Issue by zgfg** [j-hc/revanced-magisk-module#84]
Hi

I have observed the same problem with updating YT maagisk module truugh Fox Magisk Module Manager:
- Fox MMM app shows that Update for the module is available
- I click to update (install)
- Installation/update fails with mounting error:
_ERROR: Mount failed!
mount '/data/adb/com.google.android.youtube_rv.apk'->'/data/app/~~XDl3ipA9-0pQngs4ZRXWjQ==/com.google.android.youtube-HKjHbV8qnI3mNjkiMg3ALg==/base.apk' : No such file or directory_

I tested and obtained the same failure for the last three module updates (didn't test with earlier module versions), on my two phones (Xiaomi, MIUI 12.5/A11 and MIUI 13/A12).

However, when I update the module from Magisk app, it updates with no error (mounting from customize.sh does not report any error).

I have tried updating other modules from Fox MMM, they update with no problem

LogCat is attached and screenshots - from today, when tried to update to _YouTube_ReVanced-v17.36.37(20220794)_

I have also checked (when update from Fox MMM failed, without rebooting) and both files exist:
_/data/app/~~XDl3ipA9-0pQngs4ZRXWjQ==/com.google.android.youtube-HKjHbV8qnI3mNjkiMg3ALg==/base.apk_
_/data/adb/com.google.android.youtube_rv.apk_

but their sizes are different, hence indeed mounting did not execute (successfully)

_$: ls -l /data/app/~~XDl3ipA9-0pQngs4ZRXWjQ==/com.google.android.youtube-HKjHbV8qnI3mNjkiMg3ALg==
-rw-r--r-- 1 system system  72826546 2022-10-25 23:05 base.apk
drwxr-xr-x 3 system system      3452 2022-10-18 09:38 lib
drwxrwx--x 3 system install     3452 2022-10-18 09:38 oat_

_$: ls -l /data/adb
total 71292
drwxrwxrwx  4 root   root       3452 1970-11-23 12:31 aml
-rw-r--r--  1 system system 72860866 2022-10-27 09:40 com.google.android.youtube_rv.apk
drwxr-xr-x  5 root   root       3452 2022-10-25 23:05 lspd
drwxr-xr-x  3 root   root       3452 2022-10-21 10:48 magisk
-rw-------  1 root   root      40960 2022-10-26 20:31 magisk.db
drwxr-xr-x 16 root   root       3452 1970-11-23 12:31 modules
drwxr-xr-x  2 root   root       3452 2022-10-27 09:40 modules_update
drwxr-xr-x  2 root   root       3452 1970-09-24 10:19 post-fs-data.d
drwxr-xr-x  2 root   root       3452 2022-09-30 16:24 service.d
drwxr-xr-x  2 root   root       3452 2022-10-25 23:05 shamiko_

![Fox_MMM-Upgradable](https://user-images.githubusercontent.com/51943147/198257833-3d36f8fe-c76b-4006-a1f3-163c1c377918.jpg)
![Fox_MMM-Install](https://user-images.githubusercontent.com/51943147/198257898-71f1aa68-7322-47ed-8670-bc646b6ac980.jpg)
![Fox_MMM-Mount_Failed](https://user-images.githubusercontent.com/51943147/198257939-9ff3389d-c600-4f0d-ad52-f493e10c2c94.jpg)
![Magisk_app-no-problem](https://user-images.githubusercontent.com/51943147/198257979-eddddb77-b0fc-4ef0-88f9-41c8e1429313.jpg)
[logcat.txt](https://github.com/j-hc/revanced-magisk-module/files/9878324/logcat.txt)

**Comment by zgfg** [comment]
Sorry for bolding, etc - its hard to properly edit the text (mobile phone)

**Comment by zgfg** [comment]
I have also checked (when update from Fox MMM failed, without rebooting) and both files exist:
/data/app/~~XDl3ipA9-0pQngs4ZRXWjQ==/com.google.android.youtube-HKjHbV8qnI3mNjkiMg3ALg==/base.apk
/data/adb/com.google.android.youtube_rv.apk

but their sizes are different, hence indeed mounting did not execute (successfully)

# ls -l /data/app/~~XDl3ipA9-0pQngs4ZRXWjQ==/com.google.android.youtube-HKjHbV8qnI3mNjkiMg3ALg==
-rw-r--r-- 1 system system  72826546 2022-10-25 23:05 base.apk
drwxr-xr-x 3 system system      3452 2022-10-18 09:38 lib
drwxrwx--x 3 system install     3452 2022-10-18 09:38 oat

# ls -l /data/adb
total 71292
drwxrwxrwx  4 root   root       3452 1970-11-23 12:31 aml
-rw-r--r--  1 system system 72860866 2022-10-27 09:40 com.google.android.youtube_rv.apk
drwxr-xr-x  5 root   root       3452 2022-10-25 23:05 lspd
drwxr-xr-x  3 root   root       3452 2022-10-21 10:48 magisk
-rw-------  1 root   root      40960 2022-10-26 20:31 magisk.db
drwxr-xr-x 16 root   root       3452 1970-11-23 12:31 modules
drwxr-xr-x  2 root   root       3452 2022-10-27 09:40 modules_update
drwxr-xr-x  2 root   root       3452 1970-09-24 10:19 post-fs-data.d
drwxr-xr-x  2 root   root       3452 2022-09-30 16:24 service.d
drwxr-xr-x  2 root   root       3452 2022-10-25 23:05 shamiko

**Comment by j-hc** [comment]
Use the magisk app then, there is nothing I can do.

Also do not download my module from 3rd party websites, only from here: https://github.com/j-hc/revanced-magisk-module/releases

**Comment by zgfg** [comment]
Of course that I originally downloaded from your GitHub

I'm just saying that after that I use your jsonUpdate feature that shows Update button and downloads again from your GitHub, by using the URL in your updateJson

However, somehow customize.sh fails to mount if it is executed from the Fox MMM

Btw, you could try yourself

But anyway if you Closed

**Comment by j-hc** [comment]
I know that it throws an mount fail error when flashed from other module managers. There have been other issue reports before. There is nothing I can do.

**Comment by zgfg** [comment]
In fact, the fix is very simple

In customize.sh, instead of:
su -Mc mount -o bind

Please use:
su -mc mount -o bind

I have unzipped your
YouTube_ReVanced-v17.36.37(20220794).zip

Made that simple change in customize sh, zipped again

And used to Install from storage option

With -mc it successfully mounts and does not report the error

I put again -Mc, zipped, tried to install from local storage, mounting failed again with the same error

And I tried with -mc also from Magisk app, it works (from Magisk app it works with -Mc as well)

Attaching the screenshot from Fox showing successful installation and attaching my zip file (with that -mc change
![IMG_20221027_165459](https://user-images.githubusercontent.com/51943147/198324880-6269c03a-2e97-47df-ac25-854629de00f0.jpg)
![IMG_20221027_165307](https://user-images.githubusercontent.com/51943147/198325050-ac842e77-3d27-45ba-85c3-7f23746746f0.jpg)
 in customize.sh) - you can check and test (no other change)

**Comment by zgfg** [comment]
:/ $ magisk su --help
MagiskSU

Usage: su [options] [-] [user [argument...]]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        preserve the entire environment
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit
  -mm, -M,
  --mount-master                force run in the global mount namespace

**Comment by j-hc** [comment]
> For su -m it preserves environment, for -M it executes in global namespace (if I understood correctly)

Yes correct. Thats why I use -M, to mount in the global mountspace.

**Comment by zgfg** [comment]
The true fact is that it works excellent with:
su -mc
su -c

Only su -Mc calls for troubles :+

---

Moreover, you don't need su at all since the customize.sh script is executed with the root privileges
(as well as post-fs-data.sh, service sh and uninstall.sh)

It works simply with (test in Magisk app, but it also works in Fox):

if ! op=$(mount -o bind $RVPATH $BASEPATH 2>&1); then
	ui_print "ERROR: Mount failed!"
	abort "$op"
fi

Indeed, without root privileges, all those other commands in customize.sh like:
rm -r $MODPATH/bin $MODPATH/com.google.android.youtube.apk
ln -f $MODPATH/base.apk $RVPATH

would fail since without the root, script would have no privileges to write to /data/adb

Without root, you could not even read:
ls /data/adb
![IMG_20221027_181709](https://user-images.githubusercontent.com/51943147/198345768-b5b4ad0f-452c-4888-bd0a-3f8c58952dcf.jpg)

**Comment by j-hc** [comment]
lol thanks for the lecture. i will keep -M flag to force global mount space in case user changes the default to isolated.

**Comment by zgfg** [comment]
lol unsubscring from this 

btw, for mindetach.zip, disabling or even uninstalling the module does not un-detach.
but ok, i will not bother to report

**Comment by j-hc** [comment]
uninstalling mindetach described here with 2 steps: https://github.com/j-hc/mindetach-magisk#uninstall
reading is the key.
