### ISSUE TITLE
What features did revanced Spotify offer?

### ISSUE THREAD

**Issue by romiero** [j-hc/revanced-magisk-module#86]
I need to know because i see no difference between the play store version and revanced version.

**Comment by EternalYogee** [comment]
Indeed, because it can't block ads in Spotify.
It's just like play store version.

**Comment by j-hc** [comment]
list of patches is linked in the readme

revanced wont have a patch of ads for spotify in near time. it requires patching of the native modules which revanced patcher cannot do as of now.

**Comment by EternalYogee** [comment]
Yeah I saw list of patches later, it doesn't include adblock related something.
