### ISSUE TITLE
Add Repo for Fox's Magisk Module Manager

### ISSUE THREAD

**Issue by DCCXX** [j-hc/revanced-magisk-module#91]
Would you be able to make a repository for [FMMM](https://github.com/Fox2Code/FoxMagiskModuleManager#i-want-to-add-my-own-repo)?
That would make distribution and updates way easier, also far more comfortable.

**Comment by j-hc** [comment]
i see no way that it would make updates easier or comfortable. so not interested no.

**Comment by DCCXX** [comment]
Not for you, for the users. But ok o.0

**Comment by j-hc** [comment]
any other module manager than the offical magisk app is bloat.

just grab modules once from here and you consistently get updates from the app anyways.

**Comment by DCCXX** [comment]
Well, I sure didn't know that. Thank you for telling me; I absolutely agree then.

**Comment by mingaldrichgan** [comment]
Fox's MMM fails to install these modules anyway, so I'm forced to use the
official Magisk app regardless.
