### ISSUE TITLE
[Youtube] Video won't auto-rotate after turning screen back on.

### ISSUE THREAD

**Issue by Finley-Krauss** [j-hc/revanced-magisk-module#97]
Issue is present in version 17.43.36, but not in 17.41.37.

If I watch a video with the screen turned off, and turn the screen on, Youtube stops auto-rotating until I tap the fullscreen icon in the bottom right corner. Once I change rotation manually, it starts working automatically too.

**Comment by j-hc** [comment]
revanced bug
